//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class Actuator_ : Force {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Actuator_(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.Actuator__SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Actuator_ obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Actuator_() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_Actuator_(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static Actuator_ safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.Actuator__safeDownCast(Object.getCPtr(obj));
    Actuator_ ret = (cPtr == global::System.IntPtr.Zero) ? null : new Actuator_(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.Actuator__assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.Actuator__getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.Actuator__clone(swigCPtr);
    Actuator_ ret = (cPtr == global::System.IntPtr.Zero) ? null : new Actuator_(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.Actuator__getConcreteClassName(swigCPtr);
    return ret;
  }

  public virtual int numControls() {
    int ret = osimwrapPINVOKE.Actuator__numControls(swigCPtr);
    return ret;
  }

  public virtual SWIGTYPE_p_SimTK__Vector getDefaultControls() {
    SWIGTYPE_p_SimTK__Vector ret = new SWIGTYPE_p_SimTK__Vector(osimwrapPINVOKE.Actuator__getDefaultControls(swigCPtr), true);
    return ret;
  }

  public virtual void getControls(SWIGTYPE_p_SimTK__Vector modelControls, SWIGTYPE_p_SimTK__Vector actuatorControls) {
    osimwrapPINVOKE.Actuator__getControls(swigCPtr, SWIGTYPE_p_SimTK__Vector.getCPtr(modelControls), SWIGTYPE_p_SimTK__Vector.getCPtr(actuatorControls));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setControls(SWIGTYPE_p_SimTK__Vector actuatorControls, SWIGTYPE_p_SimTK__Vector modelControls) {
    osimwrapPINVOKE.Actuator__setControls(swigCPtr, SWIGTYPE_p_SimTK__Vector.getCPtr(actuatorControls), SWIGTYPE_p_SimTK__Vector.getCPtr(modelControls));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void addInControls(SWIGTYPE_p_SimTK__Vector actuatorControls, SWIGTYPE_p_SimTK__Vector modelControls) {
    osimwrapPINVOKE.Actuator__addInControls(swigCPtr, SWIGTYPE_p_SimTK__Vector.getCPtr(actuatorControls), SWIGTYPE_p_SimTK__Vector.getCPtr(modelControls));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double computeActuation(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Actuator__computeActuation(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void computeEquilibrium(SWIGTYPE_p_SimTK__State s) {
    osimwrapPINVOKE.Actuator__computeEquilibrium(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
