//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class Actuator : Actuator_ {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Actuator(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.Actuator_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Actuator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Actuator() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_Actuator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static Actuator safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.Actuator_safeDownCast(Object.getCPtr(obj));
    Actuator ret = (cPtr == global::System.IntPtr.Zero) ? null : new Actuator(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.Actuator_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.Actuator_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.Actuator_clone(swigCPtr);
    Actuator ret = (cPtr == global::System.IntPtr.Zero) ? null : new Actuator(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.Actuator_getConcreteClassName(swigCPtr);
    return ret;
  }

  public void copyProperty_min_control(Actuator source) {
    osimwrapPINVOKE.Actuator_copyProperty_min_control(swigCPtr, Actuator.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_min_control(int i) {
    double ret = osimwrapPINVOKE.Actuator_get_min_control__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_min_control(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Actuator_upd_min_control__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_min_control(int i, double value) {
    osimwrapPINVOKE.Actuator_set_min_control__SWIG_0(swigCPtr, i, value);
  }

  public int append_min_control(double value) {
    int ret = osimwrapPINVOKE.Actuator_append_min_control(swigCPtr, value);
    return ret;
  }

  public void constructProperty_min_control(double initValue) {
    osimwrapPINVOKE.Actuator_constructProperty_min_control(swigCPtr, initValue);
  }

  public double get_min_control() {
    double ret = osimwrapPINVOKE.Actuator_get_min_control__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_min_control() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Actuator_upd_min_control__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_min_control(double value) {
    osimwrapPINVOKE.Actuator_set_min_control__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_max_control(Actuator source) {
    osimwrapPINVOKE.Actuator_copyProperty_max_control(swigCPtr, Actuator.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_max_control(int i) {
    double ret = osimwrapPINVOKE.Actuator_get_max_control__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_max_control(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Actuator_upd_max_control__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_max_control(int i, double value) {
    osimwrapPINVOKE.Actuator_set_max_control__SWIG_0(swigCPtr, i, value);
  }

  public int append_max_control(double value) {
    int ret = osimwrapPINVOKE.Actuator_append_max_control(swigCPtr, value);
    return ret;
  }

  public void constructProperty_max_control(double initValue) {
    osimwrapPINVOKE.Actuator_constructProperty_max_control(swigCPtr, initValue);
  }

  public double get_max_control() {
    double ret = osimwrapPINVOKE.Actuator_get_max_control__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_max_control() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Actuator_upd_max_control__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_max_control(double value) {
    osimwrapPINVOKE.Actuator_set_max_control__SWIG_1(swigCPtr, value);
  }

  public virtual double getControl(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Actuator_getControl(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int numControls() {
    int ret = osimwrapPINVOKE.Actuator_numControls(swigCPtr);
    return ret;
  }

  public virtual void setForce(SWIGTYPE_p_SimTK__State s, double aForce) {
    osimwrapPINVOKE.Actuator_setForce(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), aForce);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double getForce(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Actuator_getForce(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setSpeed(SWIGTYPE_p_SimTK__State s, double aspeed) {
    osimwrapPINVOKE.Actuator_setSpeed(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), aspeed);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double getSpeed(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Actuator_getSpeed(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double getPower(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Actuator_getPower(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double getStress(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Actuator_getStress(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double getOptimalForce() {
    double ret = osimwrapPINVOKE.Actuator_getOptimalForce(swigCPtr);
    return ret;
  }

  public void setMinControl(double aMinControl) {
    osimwrapPINVOKE.Actuator_setMinControl(swigCPtr, aMinControl);
  }

  public double getMinControl() {
    double ret = osimwrapPINVOKE.Actuator_getMinControl(swigCPtr);
    return ret;
  }

  public void setMaxControl(double aMaxControl) {
    osimwrapPINVOKE.Actuator_setMaxControl(swigCPtr, aMaxControl);
  }

  public double getMaxControl() {
    double ret = osimwrapPINVOKE.Actuator_getMaxControl(swigCPtr);
    return ret;
  }

  public void overrideForce(SWIGTYPE_p_SimTK__State s, bool flag) {
    osimwrapPINVOKE.Actuator_overrideForce(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), flag);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isForceOverriden(SWIGTYPE_p_SimTK__State s) {
    bool ret = osimwrapPINVOKE.Actuator_isForceOverriden(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setOverrideForce(SWIGTYPE_p_SimTK__State s, double value) {
    osimwrapPINVOKE.Actuator_setOverrideForce(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getOverrideForce(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Actuator_getOverrideForce(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
