//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class CMC_Point : CMC_Task {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CMC_Point(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.CMC_Point_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CMC_Point obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CMC_Point() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_CMC_Point(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static CMC_Point safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.CMC_Point_safeDownCast(Object.getCPtr(obj));
    CMC_Point ret = (cPtr == global::System.IntPtr.Zero) ? null : new CMC_Point(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.CMC_Point_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.CMC_Point_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.CMC_Point_clone(swigCPtr);
    CMC_Point ret = (cPtr == global::System.IntPtr.Zero) ? null : new CMC_Point(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.CMC_Point_getConcreteClassName(swigCPtr);
    return ret;
  }

  public CMC_Point(SWIGTYPE_p_SimTK__Vec3 aPoint) : this(osimwrapPINVOKE.new_CMC_Point__SWIG_0(SWIGTYPE_p_SimTK__Vec3.getCPtr(aPoint)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public CMC_Point() : this(osimwrapPINVOKE.new_CMC_Point__SWIG_1(), true) {
  }

  public CMC_Point(CMC_Point aTask) : this(osimwrapPINVOKE.new_CMC_Point__SWIG_2(CMC_Point.getCPtr(aTask)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void setModel(Model aModel) {
    osimwrapPINVOKE.CMC_Point_setModel(swigCPtr, Model.getCPtr(aModel));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setPoint(SWIGTYPE_p_SimTK__Vec3 aPoint) {
    osimwrapPINVOKE.CMC_Point_setPoint(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(aPoint));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 getPoint() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.CMC_Point_getPoint(swigCPtr), true);
    return ret;
  }

  public override void computeErrors(SWIGTYPE_p_SimTK__State s, double aT) {
    osimwrapPINVOKE.CMC_Point_computeErrors(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), aT);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeDesiredAccelerations(SWIGTYPE_p_SimTK__State s, double aT) {
    osimwrapPINVOKE.CMC_Point_computeDesiredAccelerations__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), aT);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeDesiredAccelerations(SWIGTYPE_p_SimTK__State s, double aTI, double aTF) {
    osimwrapPINVOKE.CMC_Point_computeDesiredAccelerations__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), aTI, aTF);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeAccelerations(SWIGTYPE_p_SimTK__State s) {
    osimwrapPINVOKE.CMC_Point_computeAccelerations(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode, int versionNumber) {
    osimwrapPINVOKE.CMC_Point_updateFromXMLNode__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode), versionNumber);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode) {
    osimwrapPINVOKE.CMC_Point_updateFromXMLNode__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
