//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class ContactGeometry : ModelComponent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ContactGeometry(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.ContactGeometry_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ContactGeometry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ContactGeometry() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_ContactGeometry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static ContactGeometry safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.ContactGeometry_safeDownCast(Object.getCPtr(obj));
    ContactGeometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new ContactGeometry(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.ContactGeometry_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.ContactGeometry_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.ContactGeometry_clone(swigCPtr);
    ContactGeometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new ContactGeometry(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.ContactGeometry_getConcreteClassName(swigCPtr);
    return ret;
  }

  public void copyProperty_body_name(ContactGeometry source) {
    osimwrapPINVOKE.ContactGeometry_copyProperty_body_name(swigCPtr, ContactGeometry.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_body_name(int i) {
    string ret = osimwrapPINVOKE.ContactGeometry_get_body_name__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_std__string upd_body_name(int i) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(osimwrapPINVOKE.ContactGeometry_upd_body_name__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_body_name(int i, string value) {
    osimwrapPINVOKE.ContactGeometry_set_body_name__SWIG_0(swigCPtr, i, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_body_name(string value) {
    int ret = osimwrapPINVOKE.ContactGeometry_append_body_name(swigCPtr, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_body_name(string initValue) {
    osimwrapPINVOKE.ContactGeometry_constructProperty_body_name(swigCPtr, initValue);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_body_name() {
    string ret = osimwrapPINVOKE.ContactGeometry_get_body_name__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string upd_body_name() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(osimwrapPINVOKE.ContactGeometry_upd_body_name__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_body_name(string value) {
    osimwrapPINVOKE.ContactGeometry_set_body_name__SWIG_1(swigCPtr, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_location(ContactGeometry source) {
    osimwrapPINVOKE.ContactGeometry_copyProperty_location(swigCPtr, ContactGeometry.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_location(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_get_location__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_location(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_upd_location__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_location(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.ContactGeometry_set_location__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_location(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.ContactGeometry_append_location(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_location(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.ContactGeometry_constructProperty_location(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_location() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_get_location__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_location() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_upd_location__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_location(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.ContactGeometry_set_location__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_orientation(ContactGeometry source) {
    osimwrapPINVOKE.ContactGeometry_copyProperty_orientation(swigCPtr, ContactGeometry.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_orientation(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_get_orientation__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_orientation(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_upd_orientation__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_orientation(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.ContactGeometry_set_orientation__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_orientation(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.ContactGeometry_append_orientation(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_orientation(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.ContactGeometry_constructProperty_orientation(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_orientation() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_get_orientation__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_orientation() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_upd_orientation__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_orientation(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.ContactGeometry_set_orientation__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_display_preference(ContactGeometry source) {
    osimwrapPINVOKE.ContactGeometry_copyProperty_display_preference(swigCPtr, ContactGeometry.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int get_display_preference(int i) {
    int ret = osimwrapPINVOKE.ContactGeometry_get_display_preference__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_int upd_display_preference(int i) {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(osimwrapPINVOKE.ContactGeometry_upd_display_preference__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_display_preference(int i, int value) {
    osimwrapPINVOKE.ContactGeometry_set_display_preference__SWIG_0(swigCPtr, i, value);
  }

  public int append_display_preference(int value) {
    int ret = osimwrapPINVOKE.ContactGeometry_append_display_preference(swigCPtr, value);
    return ret;
  }

  public void constructProperty_display_preference(int initValue) {
    osimwrapPINVOKE.ContactGeometry_constructProperty_display_preference(swigCPtr, initValue);
  }

  public int get_display_preference() {
    int ret = osimwrapPINVOKE.ContactGeometry_get_display_preference__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_int upd_display_preference() {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(osimwrapPINVOKE.ContactGeometry_upd_display_preference__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_display_preference(int value) {
    osimwrapPINVOKE.ContactGeometry_set_display_preference__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_color(ContactGeometry source) {
    osimwrapPINVOKE.ContactGeometry_copyProperty_color(swigCPtr, ContactGeometry.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_color(int i) {
    double ret = osimwrapPINVOKE.ContactGeometry_get_color(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_color(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.ContactGeometry_upd_color(swigCPtr, i), false);
    return ret;
  }

  public void set_color(int i, double value) {
    osimwrapPINVOKE.ContactGeometry_set_color(swigCPtr, i, value);
  }

  public int append_color(double value) {
    int ret = osimwrapPINVOKE.ContactGeometry_append_color(swigCPtr, value);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 getLocation() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_getLocation(swigCPtr), false);
    return ret;
  }

  public void setLocation(SWIGTYPE_p_SimTK__Vec3 location) {
    osimwrapPINVOKE.ContactGeometry_setLocation(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(location));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 getOrientation() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.ContactGeometry_getOrientation(swigCPtr), false);
    return ret;
  }

  public void setOrientation(SWIGTYPE_p_SimTK__Vec3 orientation) {
    osimwrapPINVOKE.ContactGeometry_setOrientation(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(orientation));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Body getBody() {
    Body ret = new Body(osimwrapPINVOKE.ContactGeometry_getBody(swigCPtr), false);
    return ret;
  }

  public void setBody(Body body) {
    osimwrapPINVOKE.ContactGeometry_setBody(swigCPtr, Body.getCPtr(body));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getBodyName() {
    string ret = osimwrapPINVOKE.ContactGeometry_getBodyName(swigCPtr);
    return ret;
  }

  public void setBodyName(string name) {
    osimwrapPINVOKE.ContactGeometry_setBodyName(swigCPtr, name);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getDisplayPreference() {
    int ret = osimwrapPINVOKE.ContactGeometry_getDisplayPreference(swigCPtr);
    return ret;
  }

  public void setDisplayPreference(int dispPref) {
    osimwrapPINVOKE.ContactGeometry_setDisplayPreference(swigCPtr, dispPref);
  }

  public virtual SWIGTYPE_p_SimTK__ContactGeometry createSimTKContactGeometry() {
    SWIGTYPE_p_SimTK__ContactGeometry ret = new SWIGTYPE_p_SimTK__ContactGeometry(osimwrapPINVOKE.ContactGeometry_createSimTKContactGeometry(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Transform getTransform() {
    SWIGTYPE_p_SimTK__Transform ret = new SWIGTYPE_p_SimTK__Transform(osimwrapPINVOKE.ContactGeometry_getTransform(swigCPtr), true);
    return ret;
  }

  public virtual void scale(ScaleSet aScaleSet) {
    osimwrapPINVOKE.ContactGeometry_scale(swigCPtr, ScaleSet.getCPtr(aScaleSet));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override VisibleObject getDisplayer() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.ContactGeometry_getDisplayer(swigCPtr);
    VisibleObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new VisibleObject(cPtr, false);
    return ret;
  }

  public override VisibleObject updDisplayer() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.ContactGeometry_updDisplayer(swigCPtr);
    VisibleObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new VisibleObject(cPtr, false);
    return ret;
  }

  public virtual void updateGeometry() {
    osimwrapPINVOKE.ContactGeometry_updateGeometry(swigCPtr);
  }

}

}
