//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class ControlConstant : Control {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ControlConstant(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.ControlConstant_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ControlConstant obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ControlConstant() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_ControlConstant(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static ControlConstant safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.ControlConstant_safeDownCast(Object.getCPtr(obj));
    ControlConstant ret = (cPtr == global::System.IntPtr.Zero) ? null : new ControlConstant(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.ControlConstant_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.ControlConstant_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.ControlConstant_clone(swigCPtr);
    ControlConstant ret = (cPtr == global::System.IntPtr.Zero) ? null : new ControlConstant(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.ControlConstant_getConcreteClassName(swigCPtr);
    return ret;
  }

  public override int getNumParameters() {
    int ret = osimwrapPINVOKE.ControlConstant_getNumParameters(swigCPtr);
    return ret;
  }

  public override void setParameterMin(int aI, double aMin) {
    osimwrapPINVOKE.ControlConstant_setParameterMin(swigCPtr, aI, aMin);
  }

  public override double getParameterMin(int aI) {
    double ret = osimwrapPINVOKE.ControlConstant_getParameterMin(swigCPtr, aI);
    return ret;
  }

  public override void setParameterMax(int aI, double aMax) {
    osimwrapPINVOKE.ControlConstant_setParameterMax(swigCPtr, aI, aMax);
  }

  public override double getParameterMax(int aI) {
    double ret = osimwrapPINVOKE.ControlConstant_getParameterMax(swigCPtr, aI);
    return ret;
  }

  public override double getParameterTime(int aI) {
    double ret = osimwrapPINVOKE.ControlConstant_getParameterTime(swigCPtr, aI);
    return ret;
  }

  public override void getParameterNeighborhood(int aI, SWIGTYPE_p_double rTLower, SWIGTYPE_p_double rTUpper) {
    osimwrapPINVOKE.ControlConstant_getParameterNeighborhood(swigCPtr, aI, SWIGTYPE_p_double.getCPtr(rTLower), SWIGTYPE_p_double.getCPtr(rTUpper));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getParameterList(double aT, SWIGTYPE_p_OpenSim__ArrayT_int_t rList) {
    int ret = osimwrapPINVOKE.ControlConstant_getParameterList__SWIG_0(swigCPtr, aT, SWIGTYPE_p_OpenSim__ArrayT_int_t.getCPtr(rList));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int getParameterList(double aT1, double aT2, SWIGTYPE_p_OpenSim__ArrayT_int_t rList) {
    int ret = osimwrapPINVOKE.ControlConstant_getParameterList__SWIG_1(swigCPtr, aT1, aT2, SWIGTYPE_p_OpenSim__ArrayT_int_t.getCPtr(rList));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void setParameterValue(int aI, double aX) {
    osimwrapPINVOKE.ControlConstant_setParameterValue(swigCPtr, aI, aX);
  }

  public override double getParameterValue(int aI) {
    double ret = osimwrapPINVOKE.ControlConstant_getParameterValue(swigCPtr, aI);
    return ret;
  }

  public override void setControlValue(double aT, double aX) {
    osimwrapPINVOKE.ControlConstant_setControlValue(swigCPtr, aT, aX);
  }

  public override double getControlValue(double aT) {
    double ret = osimwrapPINVOKE.ControlConstant_getControlValue(swigCPtr, aT);
    return ret;
  }

  public override double getControlValueMin(double aT) {
    double ret = osimwrapPINVOKE.ControlConstant_getControlValueMin__SWIG_0(swigCPtr, aT);
    return ret;
  }

  public override double getControlValueMin() {
    double ret = osimwrapPINVOKE.ControlConstant_getControlValueMin__SWIG_1(swigCPtr);
    return ret;
  }

  public override void setControlValueMin(double aT, double aX) {
    osimwrapPINVOKE.ControlConstant_setControlValueMin(swigCPtr, aT, aX);
  }

  public override double getControlValueMax(double aT) {
    double ret = osimwrapPINVOKE.ControlConstant_getControlValueMax__SWIG_0(swigCPtr, aT);
    return ret;
  }

  public override double getControlValueMax() {
    double ret = osimwrapPINVOKE.ControlConstant_getControlValueMax__SWIG_1(swigCPtr);
    return ret;
  }

  public override void setControlValueMax(double aT, double aX) {
    osimwrapPINVOKE.ControlConstant_setControlValueMax(swigCPtr, aT, aX);
  }

}

}
