//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class FunctionBasedBushingForce : Force {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FunctionBasedBushingForce(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.FunctionBasedBushingForce_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FunctionBasedBushingForce obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FunctionBasedBushingForce() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_FunctionBasedBushingForce(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static FunctionBasedBushingForce safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.FunctionBasedBushingForce_safeDownCast(Object.getCPtr(obj));
    FunctionBasedBushingForce ret = (cPtr == global::System.IntPtr.Zero) ? null : new FunctionBasedBushingForce(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.FunctionBasedBushingForce_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.FunctionBasedBushingForce_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.FunctionBasedBushingForce_clone(swigCPtr);
    FunctionBasedBushingForce ret = (cPtr == global::System.IntPtr.Zero) ? null : new FunctionBasedBushingForce(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.FunctionBasedBushingForce_getConcreteClassName(swigCPtr);
    return ret;
  }

  public void copyProperty_body_1(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_body_1(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_body_1(int i) {
    string ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_body_1__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_std__string upd_body_1(int i) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(osimwrapPINVOKE.FunctionBasedBushingForce_upd_body_1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_body_1(int i, string value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_body_1__SWIG_0(swigCPtr, i, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_body_1(string value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_body_1(swigCPtr, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_body_1() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_body_1__SWIG_0(swigCPtr);
  }

  public void constructProperty_body_1(string initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_body_1__SWIG_1(swigCPtr, initValue);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_body_1() {
    string ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_body_1__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string upd_body_1() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(osimwrapPINVOKE.FunctionBasedBushingForce_upd_body_1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_body_1(string value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_body_1__SWIG_1(swigCPtr, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_body_2(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_body_2(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_body_2(int i) {
    string ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_body_2__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_std__string upd_body_2(int i) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(osimwrapPINVOKE.FunctionBasedBushingForce_upd_body_2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_body_2(int i, string value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_body_2__SWIG_0(swigCPtr, i, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_body_2(string value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_body_2(swigCPtr, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_body_2() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_body_2__SWIG_0(swigCPtr);
  }

  public void constructProperty_body_2(string initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_body_2__SWIG_1(swigCPtr, initValue);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_body_2() {
    string ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_body_2__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string upd_body_2() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(osimwrapPINVOKE.FunctionBasedBushingForce_upd_body_2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_body_2(string value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_body_2__SWIG_1(swigCPtr, value);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_location_body_1(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_location_body_1(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_location_body_1(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_location_body_1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_location_body_1(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_location_body_1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_location_body_1(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_location_body_1__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_location_body_1(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_location_body_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_location_body_1(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_location_body_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_location_body_1() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_location_body_1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_location_body_1() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_location_body_1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_location_body_1(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_location_body_1__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_orientation_body_1(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_orientation_body_1(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_orientation_body_1(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_orientation_body_1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_orientation_body_1(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_orientation_body_1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_orientation_body_1(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_orientation_body_1__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_orientation_body_1(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_orientation_body_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_orientation_body_1(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_orientation_body_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_orientation_body_1() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_orientation_body_1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_orientation_body_1() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_orientation_body_1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_orientation_body_1(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_orientation_body_1__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_location_body_2(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_location_body_2(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_location_body_2(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_location_body_2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_location_body_2(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_location_body_2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_location_body_2(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_location_body_2__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_location_body_2(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_location_body_2(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_location_body_2(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_location_body_2(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_location_body_2() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_location_body_2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_location_body_2() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_location_body_2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_location_body_2(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_location_body_2__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_orientation_body_2(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_orientation_body_2(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_orientation_body_2(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_orientation_body_2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_orientation_body_2(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_orientation_body_2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_orientation_body_2(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_orientation_body_2__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_orientation_body_2(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_orientation_body_2(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_orientation_body_2(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_orientation_body_2(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_orientation_body_2() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_orientation_body_2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_orientation_body_2() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_orientation_body_2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_orientation_body_2(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_orientation_body_2__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_m_x_theta_x_function(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_m_x_theta_x_function(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_m_x_theta_x_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_m_x_theta_x_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public Function upd_m_x_theta_x_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_m_x_theta_x_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_m_x_theta_x_function(int i, Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_m_x_theta_x_function__SWIG_0(swigCPtr, i, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_m_x_theta_x_function(Function value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_m_x_theta_x_function(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_m_x_theta_x_function() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_m_x_theta_x_function__SWIG_0(swigCPtr);
  }

  public void constructProperty_m_x_theta_x_function(Function initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_m_x_theta_x_function__SWIG_1(swigCPtr, Function.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_m_x_theta_x_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_m_x_theta_x_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public Function upd_m_x_theta_x_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_m_x_theta_x_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_m_x_theta_x_function(Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_m_x_theta_x_function__SWIG_1(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_m_y_theta_y_function(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_m_y_theta_y_function(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_m_y_theta_y_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_m_y_theta_y_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public Function upd_m_y_theta_y_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_m_y_theta_y_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_m_y_theta_y_function(int i, Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_m_y_theta_y_function__SWIG_0(swigCPtr, i, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_m_y_theta_y_function(Function value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_m_y_theta_y_function(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_m_y_theta_y_function() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_m_y_theta_y_function__SWIG_0(swigCPtr);
  }

  public void constructProperty_m_y_theta_y_function(Function initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_m_y_theta_y_function__SWIG_1(swigCPtr, Function.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_m_y_theta_y_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_m_y_theta_y_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public Function upd_m_y_theta_y_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_m_y_theta_y_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_m_y_theta_y_function(Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_m_y_theta_y_function__SWIG_1(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_m_z_theta_z_function(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_m_z_theta_z_function(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_m_z_theta_z_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_m_z_theta_z_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public Function upd_m_z_theta_z_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_m_z_theta_z_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_m_z_theta_z_function(int i, Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_m_z_theta_z_function__SWIG_0(swigCPtr, i, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_m_z_theta_z_function(Function value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_m_z_theta_z_function(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_m_z_theta_z_function() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_m_z_theta_z_function__SWIG_0(swigCPtr);
  }

  public void constructProperty_m_z_theta_z_function(Function initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_m_z_theta_z_function__SWIG_1(swigCPtr, Function.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_m_z_theta_z_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_m_z_theta_z_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public Function upd_m_z_theta_z_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_m_z_theta_z_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_m_z_theta_z_function(Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_m_z_theta_z_function__SWIG_1(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_f_x_delta_x_function(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_f_x_delta_x_function(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_f_x_delta_x_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_f_x_delta_x_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public Function upd_f_x_delta_x_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_f_x_delta_x_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_f_x_delta_x_function(int i, Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_f_x_delta_x_function__SWIG_0(swigCPtr, i, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_f_x_delta_x_function(Function value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_f_x_delta_x_function(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_f_x_delta_x_function() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_f_x_delta_x_function__SWIG_0(swigCPtr);
  }

  public void constructProperty_f_x_delta_x_function(Function initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_f_x_delta_x_function__SWIG_1(swigCPtr, Function.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_f_x_delta_x_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_f_x_delta_x_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public Function upd_f_x_delta_x_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_f_x_delta_x_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_f_x_delta_x_function(Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_f_x_delta_x_function__SWIG_1(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_f_y_delta_y_function(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_f_y_delta_y_function(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_f_y_delta_y_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_f_y_delta_y_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public Function upd_f_y_delta_y_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_f_y_delta_y_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_f_y_delta_y_function(int i, Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_f_y_delta_y_function__SWIG_0(swigCPtr, i, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_f_y_delta_y_function(Function value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_f_y_delta_y_function(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_f_y_delta_y_function() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_f_y_delta_y_function__SWIG_0(swigCPtr);
  }

  public void constructProperty_f_y_delta_y_function(Function initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_f_y_delta_y_function__SWIG_1(swigCPtr, Function.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_f_y_delta_y_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_f_y_delta_y_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public Function upd_f_y_delta_y_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_f_y_delta_y_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_f_y_delta_y_function(Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_f_y_delta_y_function__SWIG_1(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_f_z_delta_z_function(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_f_z_delta_z_function(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_f_z_delta_z_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_f_z_delta_z_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public Function upd_f_z_delta_z_function(int i) {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_f_z_delta_z_function__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_f_z_delta_z_function(int i, Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_f_z_delta_z_function__SWIG_0(swigCPtr, i, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_f_z_delta_z_function(Function value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_f_z_delta_z_function(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_f_z_delta_z_function() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_f_z_delta_z_function__SWIG_0(swigCPtr);
  }

  public void constructProperty_f_z_delta_z_function(Function initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_f_z_delta_z_function__SWIG_1(swigCPtr, Function.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Function get_f_z_delta_z_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_get_f_z_delta_z_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public Function upd_f_z_delta_z_function() {
    Function ret = new Function(osimwrapPINVOKE.FunctionBasedBushingForce_upd_f_z_delta_z_function__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_f_z_delta_z_function(Function value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_f_z_delta_z_function__SWIG_1(swigCPtr, Function.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_visual_aspect_ratio(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_visual_aspect_ratio(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_visual_aspect_ratio(int i) {
    double ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_visual_aspect_ratio__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_visual_aspect_ratio(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.FunctionBasedBushingForce_upd_visual_aspect_ratio__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_visual_aspect_ratio(int i, double value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_visual_aspect_ratio__SWIG_0(swigCPtr, i, value);
  }

  public int append_visual_aspect_ratio(double value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_visual_aspect_ratio(swigCPtr, value);
    return ret;
  }

  public void constructProperty_visual_aspect_ratio() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_visual_aspect_ratio__SWIG_0(swigCPtr);
  }

  public void constructProperty_visual_aspect_ratio(double initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_visual_aspect_ratio__SWIG_1(swigCPtr, initValue);
  }

  public double get_visual_aspect_ratio() {
    double ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_visual_aspect_ratio__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_visual_aspect_ratio() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.FunctionBasedBushingForce_upd_visual_aspect_ratio__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_visual_aspect_ratio(double value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_visual_aspect_ratio__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_moment_visual_scale(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_moment_visual_scale(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_moment_visual_scale(int i) {
    double ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_moment_visual_scale__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_moment_visual_scale(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.FunctionBasedBushingForce_upd_moment_visual_scale__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_moment_visual_scale(int i, double value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_moment_visual_scale__SWIG_0(swigCPtr, i, value);
  }

  public int append_moment_visual_scale(double value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_moment_visual_scale(swigCPtr, value);
    return ret;
  }

  public void constructProperty_moment_visual_scale() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_moment_visual_scale__SWIG_0(swigCPtr);
  }

  public void constructProperty_moment_visual_scale(double initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_moment_visual_scale__SWIG_1(swigCPtr, initValue);
  }

  public double get_moment_visual_scale() {
    double ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_moment_visual_scale__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_moment_visual_scale() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.FunctionBasedBushingForce_upd_moment_visual_scale__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_moment_visual_scale(double value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_moment_visual_scale__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_force_visual_scale(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_force_visual_scale(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_force_visual_scale(int i) {
    double ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_force_visual_scale__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_force_visual_scale(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.FunctionBasedBushingForce_upd_force_visual_scale__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_force_visual_scale(int i, double value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_force_visual_scale__SWIG_0(swigCPtr, i, value);
  }

  public int append_force_visual_scale(double value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_force_visual_scale(swigCPtr, value);
    return ret;
  }

  public void constructProperty_force_visual_scale() {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_force_visual_scale__SWIG_0(swigCPtr);
  }

  public void constructProperty_force_visual_scale(double initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_force_visual_scale__SWIG_1(swigCPtr, initValue);
  }

  public double get_force_visual_scale() {
    double ret = osimwrapPINVOKE.FunctionBasedBushingForce_get_force_visual_scale__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_force_visual_scale() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.FunctionBasedBushingForce_upd_force_visual_scale__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_force_visual_scale(double value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_force_visual_scale__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_rotational_damping(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_rotational_damping(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_rotational_damping(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_rotational_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_rotational_damping(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_rotational_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_rotational_damping(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_rotational_damping__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_rotational_damping(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_rotational_damping(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_rotational_damping(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_rotational_damping(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_rotational_damping() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_rotational_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_rotational_damping() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_rotational_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_rotational_damping(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_rotational_damping__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_translational_damping(FunctionBasedBushingForce source) {
    osimwrapPINVOKE.FunctionBasedBushingForce_copyProperty_translational_damping(swigCPtr, FunctionBasedBushingForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_translational_damping(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_translational_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_translational_damping(int i) {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_translational_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_translational_damping(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_translational_damping__SWIG_0(swigCPtr, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_translational_damping(SWIGTYPE_p_SimTK__Vec3 value) {
    int ret = osimwrapPINVOKE.FunctionBasedBushingForce_append_translational_damping(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_translational_damping(SWIGTYPE_p_SimTK__Vec3 initValue) {
    osimwrapPINVOKE.FunctionBasedBushingForce_constructProperty_translational_damping(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vec3 get_translational_damping() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_get_translational_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_translational_damping() {
    SWIGTYPE_p_SimTK__Vec3 ret = new SWIGTYPE_p_SimTK__Vec3(osimwrapPINVOKE.FunctionBasedBushingForce_upd_translational_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_translational_damping(SWIGTYPE_p_SimTK__Vec3 value) {
    osimwrapPINVOKE.FunctionBasedBushingForce_set_translational_damping__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public FunctionBasedBushingForce() : this(osimwrapPINVOKE.new_FunctionBasedBushingForce__SWIG_0(), true) {
  }

  public FunctionBasedBushingForce(string body1Name, SWIGTYPE_p_SimTK__Vec3 point1, SWIGTYPE_p_SimTK__Vec3 orientation1, string body2Name, SWIGTYPE_p_SimTK__Vec3 point2, SWIGTYPE_p_SimTK__Vec3 orientation2) : this(osimwrapPINVOKE.new_FunctionBasedBushingForce__SWIG_1(body1Name, SWIGTYPE_p_SimTK__Vec3.getCPtr(point1), SWIGTYPE_p_SimTK__Vec3.getCPtr(orientation1), body2Name, SWIGTYPE_p_SimTK__Vec3.getCPtr(point2), SWIGTYPE_p_SimTK__Vec3.getCPtr(orientation2)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public FunctionBasedBushingForce(string body1Name, SWIGTYPE_p_SimTK__Vec3 point1, SWIGTYPE_p_SimTK__Vec3 orientation1, string body2Name, SWIGTYPE_p_SimTK__Vec3 point2, SWIGTYPE_p_SimTK__Vec3 orientation2, SWIGTYPE_p_SimTK__Vec3 transStiffness, SWIGTYPE_p_SimTK__Vec3 rotStiffness, SWIGTYPE_p_SimTK__Vec3 transDamping, SWIGTYPE_p_SimTK__Vec3 rotDamping) : this(osimwrapPINVOKE.new_FunctionBasedBushingForce__SWIG_2(body1Name, SWIGTYPE_p_SimTK__Vec3.getCPtr(point1), SWIGTYPE_p_SimTK__Vec3.getCPtr(orientation1), body2Name, SWIGTYPE_p_SimTK__Vec3.getCPtr(point2), SWIGTYPE_p_SimTK__Vec3.getCPtr(orientation2), SWIGTYPE_p_SimTK__Vec3.getCPtr(transStiffness), SWIGTYPE_p_SimTK__Vec3.getCPtr(rotStiffness), SWIGTYPE_p_SimTK__Vec3.getCPtr(transDamping), SWIGTYPE_p_SimTK__Vec3.getCPtr(rotDamping)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBody1ByName(string aBodyName) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setBody1ByName(swigCPtr, aBodyName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBody1BushingLocation(SWIGTYPE_p_SimTK__Vec3 location, SWIGTYPE_p_SimTK__Vec3 orientation) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setBody1BushingLocation__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(location), SWIGTYPE_p_SimTK__Vec3.getCPtr(orientation));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBody1BushingLocation(SWIGTYPE_p_SimTK__Vec3 location) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setBody1BushingLocation__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(location));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBody2ByName(string aBodyName) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setBody2ByName(swigCPtr, aBodyName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBody2BushingLocation(SWIGTYPE_p_SimTK__Vec3 location, SWIGTYPE_p_SimTK__Vec3 orientation) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setBody2BushingLocation__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(location), SWIGTYPE_p_SimTK__Vec3.getCPtr(orientation));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBody2BushingLocation(SWIGTYPE_p_SimTK__Vec3 location) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setBody2BushingLocation__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(location));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setMomentVisualScale(double scale) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setMomentVisualScale(swigCPtr, scale);
  }

  public void setForceVisualScale(double scale) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setForceVisualScale(swigCPtr, scale);
  }

  public void setVisualAspectRatio(double ratio) {
    osimwrapPINVOKE.FunctionBasedBushingForce_setVisualAspectRatio(swigCPtr, ratio);
  }

  public virtual SWIGTYPE_p_SimTK__Vec6 computeDeflection(SWIGTYPE_p_SimTK__State s) {
    SWIGTYPE_p_SimTK__Vec6 ret = new SWIGTYPE_p_SimTK__Vec6(osimwrapPINVOKE.FunctionBasedBushingForce_computeDeflection(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s)), true);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void computeForce(SWIGTYPE_p_SimTK__State s, SWIGTYPE_p_SimTK__Vector_T_SimTK__SpatialVec_t bodyForces, SWIGTYPE_p_SimTK__Vector generalizedForces) {
    osimwrapPINVOKE.FunctionBasedBushingForce_computeForce(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), SWIGTYPE_p_SimTK__Vector_T_SimTK__SpatialVec_t.getCPtr(bodyForces), SWIGTYPE_p_SimTK__Vector.getCPtr(generalizedForces));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double computePotentialEnergy(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.FunctionBasedBushingForce_computePotentialEnergy(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override ArrayOfStrings getRecordLabels() {
    ArrayOfStrings ret = new ArrayOfStrings(osimwrapPINVOKE.FunctionBasedBushingForce_getRecordLabels(swigCPtr), true);
    return ret;
  }

  public override SWIGTYPE_p_OpenSim__ArrayT_double_t getRecordValues(SWIGTYPE_p_SimTK__State state) {
    SWIGTYPE_p_OpenSim__ArrayT_double_t ret = new SWIGTYPE_p_OpenSim__ArrayT_double_t(osimwrapPINVOKE.FunctionBasedBushingForce_getRecordValues(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(state)), true);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
