//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class GCVSpline : Function {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal GCVSpline(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.GCVSpline_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GCVSpline obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GCVSpline() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_GCVSpline(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static GCVSpline safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.GCVSpline_safeDownCast(Object.getCPtr(obj));
    GCVSpline ret = (cPtr == global::System.IntPtr.Zero) ? null : new GCVSpline(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.GCVSpline_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.GCVSpline_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.GCVSpline_clone(swigCPtr);
    GCVSpline ret = (cPtr == global::System.IntPtr.Zero) ? null : new GCVSpline(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.GCVSpline_getConcreteClassName(swigCPtr);
    return ret;
  }

  public GCVSpline() : this(osimwrapPINVOKE.new_GCVSpline__SWIG_0(), true) {
  }

  public GCVSpline(int aDegree, int aN, SWIGTYPE_p_double aTimes, SWIGTYPE_p_double aValues, string aName, double aErrorVariance) : this(osimwrapPINVOKE.new_GCVSpline__SWIG_1(aDegree, aN, SWIGTYPE_p_double.getCPtr(aTimes), SWIGTYPE_p_double.getCPtr(aValues), aName, aErrorVariance), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public GCVSpline(int aDegree, int aN, SWIGTYPE_p_double aTimes, SWIGTYPE_p_double aValues, string aName) : this(osimwrapPINVOKE.new_GCVSpline__SWIG_2(aDegree, aN, SWIGTYPE_p_double.getCPtr(aTimes), SWIGTYPE_p_double.getCPtr(aValues), aName), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public GCVSpline(int aDegree, int aN, SWIGTYPE_p_double aTimes, SWIGTYPE_p_double aValues) : this(osimwrapPINVOKE.new_GCVSpline__SWIG_3(aDegree, aN, SWIGTYPE_p_double.getCPtr(aTimes), SWIGTYPE_p_double.getCPtr(aValues)), true) {
  }

  public GCVSpline(GCVSpline aSpline) : this(osimwrapPINVOKE.new_GCVSpline__SWIG_4(GCVSpline.getCPtr(aSpline)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode, int versionNumber) {
    osimwrapPINVOKE.GCVSpline_updateFromXMLNode__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode), versionNumber);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode) {
    osimwrapPINVOKE.GCVSpline_updateFromXMLNode__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setDegree(int aDegree) {
    osimwrapPINVOKE.GCVSpline_setDegree(swigCPtr, aDegree);
  }

  public int getDegree() {
    int ret = osimwrapPINVOKE.GCVSpline_getDegree(swigCPtr);
    return ret;
  }

  public int getOrder() {
    int ret = osimwrapPINVOKE.GCVSpline_getOrder(swigCPtr);
    return ret;
  }

  public int getHalfOrder() {
    int ret = osimwrapPINVOKE.GCVSpline_getHalfOrder(swigCPtr);
    return ret;
  }

  public int getSize() {
    int ret = osimwrapPINVOKE.GCVSpline_getSize(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_OpenSim__ArrayT_double_t getX() {
    SWIGTYPE_p_OpenSim__ArrayT_double_t ret = new SWIGTYPE_p_OpenSim__ArrayT_double_t(osimwrapPINVOKE.GCVSpline_getX__SWIG_0(swigCPtr), false);
    return ret;
  }

  public virtual SWIGTYPE_p_double getXValues() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.GCVSpline_getXValues(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public virtual SWIGTYPE_p_double getYValues() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.GCVSpline_getYValues(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_OpenSim__ArrayT_double_t getCoefficients() {
    SWIGTYPE_p_OpenSim__ArrayT_double_t ret = new SWIGTYPE_p_OpenSim__ArrayT_double_t(osimwrapPINVOKE.GCVSpline_getCoefficients(swigCPtr), false);
    return ret;
  }

  public virtual int getNumberOfPoints() {
    int ret = osimwrapPINVOKE.GCVSpline_getNumberOfPoints(swigCPtr);
    return ret;
  }

  public virtual double getX(int aIndex) {
    double ret = osimwrapPINVOKE.GCVSpline_getX__SWIG_1(swigCPtr, aIndex);
    return ret;
  }

  public virtual double getY(int aIndex) {
    double ret = osimwrapPINVOKE.GCVSpline_getY(swigCPtr, aIndex);
    return ret;
  }

  public virtual double getZ(int aIndex) {
    double ret = osimwrapPINVOKE.GCVSpline_getZ(swigCPtr, aIndex);
    return ret;
  }

  public virtual void setX(int aIndex, double aValue) {
    osimwrapPINVOKE.GCVSpline_setX(swigCPtr, aIndex, aValue);
  }

  public virtual void setY(int aIndex, double aValue) {
    osimwrapPINVOKE.GCVSpline_setY(swigCPtr, aIndex, aValue);
  }

  public virtual double getMinX() {
    double ret = osimwrapPINVOKE.GCVSpline_getMinX(swigCPtr);
    return ret;
  }

  public virtual double getMaxX() {
    double ret = osimwrapPINVOKE.GCVSpline_getMaxX(swigCPtr);
    return ret;
  }

  public virtual bool deletePoint(int aIndex) {
    bool ret = osimwrapPINVOKE.GCVSpline_deletePoint(swigCPtr, aIndex);
    return ret;
  }

  public virtual bool deletePoints(SWIGTYPE_p_OpenSim__ArrayT_int_t indices) {
    bool ret = osimwrapPINVOKE.GCVSpline_deletePoints(swigCPtr, SWIGTYPE_p_OpenSim__ArrayT_int_t.getCPtr(indices));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int addPoint(double aX, double aY) {
    int ret = osimwrapPINVOKE.GCVSpline_addPoint(swigCPtr, aX, aY);
    return ret;
  }

  public override SWIGTYPE_p_SimTK__Function createSimTKFunction() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.GCVSpline_createSimTKFunction(swigCPtr);
    SWIGTYPE_p_SimTK__Function ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_SimTK__Function(cPtr, false);
    return ret;
  }

}

}
