//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class HuntCrossleyForce : Force {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal HuntCrossleyForce(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.HuntCrossleyForce_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HuntCrossleyForce obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HuntCrossleyForce() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_HuntCrossleyForce(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static HuntCrossleyForce safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.HuntCrossleyForce_safeDownCast(Object.getCPtr(obj));
    HuntCrossleyForce ret = (cPtr == global::System.IntPtr.Zero) ? null : new HuntCrossleyForce(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.HuntCrossleyForce_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.HuntCrossleyForce_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.HuntCrossleyForce_clone(swigCPtr);
    HuntCrossleyForce ret = (cPtr == global::System.IntPtr.Zero) ? null : new HuntCrossleyForce(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.HuntCrossleyForce_getConcreteClassName(swigCPtr);
    return ret;
  }

  public void copyProperty_contact_parameters(HuntCrossleyForce source) {
    osimwrapPINVOKE.HuntCrossleyForce_copyProperty_contact_parameters(swigCPtr, HuntCrossleyForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet get_contact_parameters(int i) {
    SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet ret = new SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet(osimwrapPINVOKE.HuntCrossleyForce_get_contact_parameters__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet upd_contact_parameters(int i) {
    SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet ret = new SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet(osimwrapPINVOKE.HuntCrossleyForce_upd_contact_parameters__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_contact_parameters(int i, SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet value) {
    osimwrapPINVOKE.HuntCrossleyForce_set_contact_parameters__SWIG_0(swigCPtr, i, SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public int append_contact_parameters(SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet value) {
    int ret = osimwrapPINVOKE.HuntCrossleyForce_append_contact_parameters(swigCPtr, SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void constructProperty_contact_parameters(SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet initValue) {
    osimwrapPINVOKE.HuntCrossleyForce_constructProperty_contact_parameters(swigCPtr, SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet.getCPtr(initValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet get_contact_parameters() {
    SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet ret = new SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet(osimwrapPINVOKE.HuntCrossleyForce_get_contact_parameters__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet upd_contact_parameters() {
    SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet ret = new SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet(osimwrapPINVOKE.HuntCrossleyForce_upd_contact_parameters__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_contact_parameters(SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet value) {
    osimwrapPINVOKE.HuntCrossleyForce_set_contact_parameters__SWIG_1(swigCPtr, SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet.getCPtr(value));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyProperty_transition_velocity(HuntCrossleyForce source) {
    osimwrapPINVOKE.HuntCrossleyForce_copyProperty_transition_velocity(swigCPtr, HuntCrossleyForce.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_transition_velocity(int i) {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_get_transition_velocity__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_transition_velocity(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.HuntCrossleyForce_upd_transition_velocity__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_transition_velocity(int i, double value) {
    osimwrapPINVOKE.HuntCrossleyForce_set_transition_velocity__SWIG_0(swigCPtr, i, value);
  }

  public int append_transition_velocity(double value) {
    int ret = osimwrapPINVOKE.HuntCrossleyForce_append_transition_velocity(swigCPtr, value);
    return ret;
  }

  public void constructProperty_transition_velocity(double initValue) {
    osimwrapPINVOKE.HuntCrossleyForce_constructProperty_transition_velocity(swigCPtr, initValue);
  }

  public double get_transition_velocity() {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_get_transition_velocity__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_transition_velocity() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.HuntCrossleyForce_upd_transition_velocity__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_transition_velocity(double value) {
    osimwrapPINVOKE.HuntCrossleyForce_set_transition_velocity__SWIG_1(swigCPtr, value);
  }

  public HuntCrossleyForce() : this(osimwrapPINVOKE.new_HuntCrossleyForce(), true) {
  }

  public SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet updContactParametersSet() {
    SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet ret = new SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet(osimwrapPINVOKE.HuntCrossleyForce_updContactParametersSet(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet getContactParametersSet() {
    SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet ret = new SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParametersSet(osimwrapPINVOKE.HuntCrossleyForce_getContactParametersSet(swigCPtr), false);
    return ret;
  }

  public void addContactParameters(SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParameters arg0) {
    osimwrapPINVOKE.HuntCrossleyForce_addContactParameters(swigCPtr, SWIGTYPE_p_OpenSim__HuntCrossleyForce__ContactParameters.getCPtr(arg0));
  }

  public double getTransitionVelocity() {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_getTransitionVelocity(swigCPtr);
    return ret;
  }

  public void setTransitionVelocity(double velocity) {
    osimwrapPINVOKE.HuntCrossleyForce_setTransitionVelocity(swigCPtr, velocity);
  }

  public double getStiffness() {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_getStiffness(swigCPtr);
    return ret;
  }

  public void setStiffness(double stiffness) {
    osimwrapPINVOKE.HuntCrossleyForce_setStiffness(swigCPtr, stiffness);
  }

  public double getDissipation() {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_getDissipation(swigCPtr);
    return ret;
  }

  public void setDissipation(double dissipation) {
    osimwrapPINVOKE.HuntCrossleyForce_setDissipation(swigCPtr, dissipation);
  }

  public double getStaticFriction() {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_getStaticFriction(swigCPtr);
    return ret;
  }

  public void setStaticFriction(double friction) {
    osimwrapPINVOKE.HuntCrossleyForce_setStaticFriction(swigCPtr, friction);
  }

  public double getDynamicFriction() {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_getDynamicFriction(swigCPtr);
    return ret;
  }

  public void setDynamicFriction(double friction) {
    osimwrapPINVOKE.HuntCrossleyForce_setDynamicFriction(swigCPtr, friction);
  }

  public double getViscousFriction() {
    double ret = osimwrapPINVOKE.HuntCrossleyForce_getViscousFriction(swigCPtr);
    return ret;
  }

  public void setViscousFriction(double friction) {
    osimwrapPINVOKE.HuntCrossleyForce_setViscousFriction(swigCPtr, friction);
  }

  public void addGeometry(string name) {
    osimwrapPINVOKE.HuntCrossleyForce_addGeometry(swigCPtr, name);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override ArrayOfStrings getRecordLabels() {
    ArrayOfStrings ret = new ArrayOfStrings(osimwrapPINVOKE.HuntCrossleyForce_getRecordLabels(swigCPtr), true);
    return ret;
  }

  public override SWIGTYPE_p_OpenSim__ArrayT_double_t getRecordValues(SWIGTYPE_p_SimTK__State state) {
    SWIGTYPE_p_OpenSim__ArrayT_double_t ret = new SWIGTYPE_p_OpenSim__ArrayT_double_t(osimwrapPINVOKE.HuntCrossleyForce_getRecordValues(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(state)), true);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
