//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class IKTask : Object {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IKTask(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.IKTask_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKTask obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IKTask() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_IKTask(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static IKTask safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.IKTask_safeDownCast(Object.getCPtr(obj));
    IKTask ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKTask(cPtr, false);
    return ret;
  }

  public virtual void assign(Object aObject) {
    osimwrapPINVOKE.IKTask_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.IKTask_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.IKTask_clone(swigCPtr);
    IKTask ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKTask(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.IKTask_getConcreteClassName(swigCPtr);
    return ret;
  }

  public bool getApply() {
    bool ret = osimwrapPINVOKE.IKTask_getApply(swigCPtr);
    return ret;
  }

  public void setApply(bool aApply) {
    osimwrapPINVOKE.IKTask_setApply(swigCPtr, aApply);
  }

  public double getWeight() {
    double ret = osimwrapPINVOKE.IKTask_getWeight(swigCPtr);
    return ret;
  }

  public void setWeight(double weight) {
    osimwrapPINVOKE.IKTask_setWeight(swigCPtr, weight);
  }

}

}
