//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class MarkersReference : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MarkersReference(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MarkersReference obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MarkersReference() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_MarkersReference(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static MarkersReference safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.MarkersReference_safeDownCast(Object.getCPtr(obj));
    MarkersReference ret = (cPtr == global::System.IntPtr.Zero) ? null : new MarkersReference(cPtr, false);
    return ret;
  }

  public virtual void assign(Object aObject) {
    osimwrapPINVOKE.MarkersReference_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public static string getClassName() {
    string ret = osimwrapPINVOKE.MarkersReference_getClassName();
    return ret;
  }

  public MarkersReference clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.MarkersReference_clone(swigCPtr);
    MarkersReference ret = (cPtr == global::System.IntPtr.Zero) ? null : new MarkersReference(cPtr, false);
    return ret;
  }

  public string getConcreteClassName() {
    string ret = osimwrapPINVOKE.MarkersReference_getConcreteClassName(swigCPtr);
    return ret;
  }

  public MarkersReference() : this(osimwrapPINVOKE.new_MarkersReference__SWIG_0(), true) {
  }

  public MarkersReference(string filename, Units modelUnits) : this(osimwrapPINVOKE.new_MarkersReference__SWIG_1(filename, Units.getCPtr(modelUnits)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public MarkersReference(string filename) : this(osimwrapPINVOKE.new_MarkersReference__SWIG_2(filename), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public MarkersReference(MarkerData aMarkerData, SWIGTYPE_p_OpenSim__SetT_OpenSim__MarkerWeight_t aMarkerWeightSet) : this(osimwrapPINVOKE.new_MarkersReference__SWIG_3(MarkerData.getCPtr(aMarkerData), SWIGTYPE_p_OpenSim__SetT_OpenSim__MarkerWeight_t.getCPtr(aMarkerWeightSet)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public MarkersReference(MarkerData aMarkerData) : this(osimwrapPINVOKE.new_MarkersReference__SWIG_4(MarkerData.getCPtr(aMarkerData)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyData(MarkersReference aRef) {
    osimwrapPINVOKE.MarkersReference_copyData(swigCPtr, MarkersReference.getCPtr(aRef));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void loadMarkersFile(string markerFile, Units modelUnits) {
    osimwrapPINVOKE.MarkersReference_loadMarkersFile__SWIG_0(swigCPtr, markerFile, Units.getCPtr(modelUnits));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void loadMarkersFile(string markerFile) {
    osimwrapPINVOKE.MarkersReference_loadMarkersFile__SWIG_1(swigCPtr, markerFile);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual int getNumRefs() {
    int ret = osimwrapPINVOKE.MarkersReference_getNumRefs(swigCPtr);
    return ret;
  }

  public virtual SWIGTYPE_p_SimTK__Vec2 getValidTimeRange() {
    SWIGTYPE_p_SimTK__Vec2 ret = new SWIGTYPE_p_SimTK__Vec2(osimwrapPINVOKE.MarkersReference_getValidTimeRange(swigCPtr), true);
    return ret;
  }

  public virtual SWIGTYPE_p_SimTK__Array_T_std__string_t getNames() {
    SWIGTYPE_p_SimTK__Array_T_std__string_t ret = new SWIGTYPE_p_SimTK__Array_T_std__string_t(osimwrapPINVOKE.MarkersReference_getNames(swigCPtr), false);
    return ret;
  }

  public virtual void getValues(SWIGTYPE_p_SimTK__State s, SWIGTYPE_p_SimTK__Array_T_SimTK__Vec3_t values) {
    osimwrapPINVOKE.MarkersReference_getValues(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), SWIGTYPE_p_SimTK__Array_T_SimTK__Vec3_t.getCPtr(values));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void getSpeedValues(SWIGTYPE_p_SimTK__State s, SWIGTYPE_p_SimTK__Array_T_SimTK__Vec3_t speedValues) {
    osimwrapPINVOKE.MarkersReference_getSpeedValues(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), SWIGTYPE_p_SimTK__Array_T_SimTK__Vec3_t.getCPtr(speedValues));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void getAccelerationValues(SWIGTYPE_p_SimTK__State s, SWIGTYPE_p_SimTK__Array_T_SimTK__Vec3_t accValues) {
    osimwrapPINVOKE.MarkersReference_getAccelerationValues(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), SWIGTYPE_p_SimTK__Array_T_SimTK__Vec3_t.getCPtr(accValues));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void getWeights(SWIGTYPE_p_SimTK__State s, SWIGTYPE_p_SimTK__Array_T_double_t weights) {
    osimwrapPINVOKE.MarkersReference_getWeights(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), SWIGTYPE_p_SimTK__Array_T_double_t.getCPtr(weights));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getSamplingFrequency() {
    double ret = osimwrapPINVOKE.MarkersReference_getSamplingFrequency(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_OpenSim__SetT_OpenSim__MarkerWeight_t updMarkerWeightSet() {
    SWIGTYPE_p_OpenSim__SetT_OpenSim__MarkerWeight_t ret = new SWIGTYPE_p_OpenSim__SetT_OpenSim__MarkerWeight_t(osimwrapPINVOKE.MarkersReference_updMarkerWeightSet(swigCPtr), false);
    return ret;
  }

  public void setMarkerWeightSet(SWIGTYPE_p_OpenSim__SetT_OpenSim__MarkerWeight_t markerWeights) {
    osimwrapPINVOKE.MarkersReference_setMarkerWeightSet(swigCPtr, SWIGTYPE_p_OpenSim__SetT_OpenSim__MarkerWeight_t.getCPtr(markerWeights));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setDefaultWeight(double weight) {
    osimwrapPINVOKE.MarkersReference_setDefaultWeight(swigCPtr, weight);
  }

}

}
