//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class PathPointSet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PathPointSet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PathPointSet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PathPointSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_PathPointSet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static PathPointSet safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PathPointSet_safeDownCast(Object.getCPtr(obj));
    PathPointSet ret = (cPtr == global::System.IntPtr.Zero) ? null : new PathPointSet(cPtr, false);
    return ret;
  }

  public virtual void assign(Object aObject) {
    osimwrapPINVOKE.PathPointSet_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public static string getClassName() {
    string ret = osimwrapPINVOKE.PathPointSet_getClassName();
    return ret;
  }

  public PathPointSet clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PathPointSet_clone(swigCPtr);
    PathPointSet ret = (cPtr == global::System.IntPtr.Zero) ? null : new PathPointSet(cPtr, false);
    return ret;
  }

  public string getConcreteClassName() {
    string ret = osimwrapPINVOKE.PathPointSet_getConcreteClassName(swigCPtr);
    return ret;
  }

  public PathPointSet() : this(osimwrapPINVOKE.new_PathPointSet__SWIG_0(), true) {
  }

  public PathPointSet(PathPointSet aPathPointSet) : this(osimwrapPINVOKE.new_PathPointSet__SWIG_1(PathPointSet.getCPtr(aPathPointSet)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
