//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class PolynomialFunction : Function {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PolynomialFunction(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.PolynomialFunction_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PolynomialFunction obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PolynomialFunction() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_PolynomialFunction(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static PolynomialFunction safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PolynomialFunction_safeDownCast(Object.getCPtr(obj));
    PolynomialFunction ret = (cPtr == global::System.IntPtr.Zero) ? null : new PolynomialFunction(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.PolynomialFunction_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.PolynomialFunction_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PolynomialFunction_clone(swigCPtr);
    PolynomialFunction ret = (cPtr == global::System.IntPtr.Zero) ? null : new PolynomialFunction(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.PolynomialFunction_getConcreteClassName(swigCPtr);
    return ret;
  }

  public PolynomialFunction() : this(osimwrapPINVOKE.new_PolynomialFunction__SWIG_0(), true) {
  }

  public PolynomialFunction(SWIGTYPE_p_SimTK__Vector coefficients) : this(osimwrapPINVOKE.new_PolynomialFunction__SWIG_1(SWIGTYPE_p_SimTK__Vector.getCPtr(coefficients)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setCoefficients(SWIGTYPE_p_SimTK__Vector coefficients) {
    osimwrapPINVOKE.PolynomialFunction_setCoefficients(swigCPtr, SWIGTYPE_p_SimTK__Vector.getCPtr(coefficients));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SimTK__Vector getCoefficients() {
    SWIGTYPE_p_SimTK__Vector ret = new SWIGTYPE_p_SimTK__Vector(osimwrapPINVOKE.PolynomialFunction_getCoefficients(swigCPtr), true);
    return ret;
  }

  public override SWIGTYPE_p_SimTK__Function createSimTKFunction() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PolynomialFunction_createSimTKFunction(swigCPtr);
    SWIGTYPE_p_SimTK__Function ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_SimTK__Function(cPtr, false);
    return ret;
  }

}

}
