//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class PropertyStrArray : Property_Deprecated {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PropertyStrArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.PropertyStrArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PropertyStrArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PropertyStrArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_PropertyStrArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PropertyStrArray() : this(osimwrapPINVOKE.new_PropertyStrArray__SWIG_0(), true) {
  }

  public PropertyStrArray(string aName, ArrayOfStrings aArray) : this(osimwrapPINVOKE.new_PropertyStrArray__SWIG_1(aName, ArrayOfStrings.getCPtr(aArray)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public PropertyStrArray(string aName, int aSize, SWIGTYPE_p_std__string aArray) : this(osimwrapPINVOKE.new_PropertyStrArray__SWIG_2(aName, aSize, SWIGTYPE_p_std__string.getCPtr(aArray)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public PropertyStrArray(PropertyStrArray aProperty) : this(osimwrapPINVOKE.new_PropertyStrArray__SWIG_3(PropertyStrArray.getCPtr(aProperty)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool isArrayProperty() {
    bool ret = osimwrapPINVOKE.PropertyStrArray_isArrayProperty(swigCPtr);
    return ret;
  }

  public override AbstractProperty clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertyStrArray_clone(swigCPtr);
    PropertyStrArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new PropertyStrArray(cPtr, false);
    return ret;
  }

  public override int getNumValues() {
    int ret = osimwrapPINVOKE.PropertyStrArray_getNumValues(swigCPtr);
    return ret;
  }

  public override string getTypeName() {
    string ret = osimwrapPINVOKE.PropertyStrArray_getTypeName(swigCPtr);
    return ret;
  }

  public override void setValue(ArrayOfStrings aArray) {
    osimwrapPINVOKE.PropertyStrArray_setValue__SWIG_0(swigCPtr, ArrayOfStrings.getCPtr(aArray));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void setValue(int aSize, SWIGTYPE_p_std__string aArray) {
    osimwrapPINVOKE.PropertyStrArray_setValue__SWIG_1(swigCPtr, aSize, SWIGTYPE_p_std__string.getCPtr(aArray));
  }

  public override ArrayOfStrings getValueStrArray() {
    ArrayOfStrings ret = new ArrayOfStrings(osimwrapPINVOKE.PropertyStrArray_getValueStrArray__SWIG_0(swigCPtr), false);
    return ret;
  }

  public override int getArraySize() {
    int ret = osimwrapPINVOKE.PropertyStrArray_getArraySize(swigCPtr);
    return ret;
  }

  public override string toString() {
    string ret = osimwrapPINVOKE.PropertyStrArray_toString(swigCPtr);
    return ret;
  }

  public override void clearValues() {
    osimwrapPINVOKE.PropertyStrArray_clearValues(swigCPtr);
  }

}

}
