//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class PropertyGroup : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PropertyGroup(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PropertyGroup obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PropertyGroup() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_PropertyGroup(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PropertyGroup() : this(osimwrapPINVOKE.new_PropertyGroup__SWIG_0(), true) {
  }

  public PropertyGroup(SWIGTYPE_p_std__string aName) : this(osimwrapPINVOKE.new_PropertyGroup__SWIG_1(SWIGTYPE_p_std__string.getCPtr(aName)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public PropertyGroup(PropertyGroup aGroup) : this(osimwrapPINVOKE.new_PropertyGroup__SWIG_2(PropertyGroup.getCPtr(aGroup)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual PropertyGroup clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertyGroup_clone(swigCPtr);
    PropertyGroup ret = (cPtr == global::System.IntPtr.Zero) ? null : new PropertyGroup(cPtr, false);
    return ret;
  }

  public void copyData(PropertyGroup aGroup) {
    osimwrapPINVOKE.PropertyGroup_copyData(swigCPtr, PropertyGroup.getCPtr(aGroup));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void clear() {
    osimwrapPINVOKE.PropertyGroup_clear(swigCPtr);
  }

  public bool contains(string aName) {
    bool ret = osimwrapPINVOKE.PropertyGroup_contains(swigCPtr, aName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void add(Property_Deprecated aProperty) {
    osimwrapPINVOKE.PropertyGroup_add(swigCPtr, Property_Deprecated.getCPtr(aProperty));
  }

  public void remove(Property_Deprecated aProperty) {
    osimwrapPINVOKE.PropertyGroup_remove(swigCPtr, Property_Deprecated.getCPtr(aProperty));
  }

  public Property_Deprecated get(int aIndex) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertyGroup_get(swigCPtr, aIndex);
    Property_Deprecated ret = (cPtr == global::System.IntPtr.Zero) ? null : new Property_Deprecated(cPtr, false);
    return ret;
  }

  public int getPropertyIndex(Property_Deprecated aProperty) {
    int ret = osimwrapPINVOKE.PropertyGroup_getPropertyIndex(swigCPtr, Property_Deprecated.getCPtr(aProperty));
    return ret;
  }

  public void setName(string aName) {
    osimwrapPINVOKE.PropertyGroup_setName(swigCPtr, aName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getName() {
    string ret = osimwrapPINVOKE.PropertyGroup_getName(swigCPtr);
    return ret;
  }

}

}
