//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class PropertySet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PropertySet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PropertySet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PropertySet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_PropertySet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_OpenSim__ArrayPtrsT_OpenSim__Property_Deprecated_t _array {
    set {
      osimwrapPINVOKE.PropertySet__array_set(swigCPtr, SWIGTYPE_p_OpenSim__ArrayPtrsT_OpenSim__Property_Deprecated_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = osimwrapPINVOKE.PropertySet__array_get(swigCPtr);
      SWIGTYPE_p_OpenSim__ArrayPtrsT_OpenSim__Property_Deprecated_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_OpenSim__ArrayPtrsT_OpenSim__Property_Deprecated_t(cPtr, false);
      return ret;
    } 
  }

  public PropertySet() : this(osimwrapPINVOKE.new_PropertySet__SWIG_0(), true) {
  }

  public PropertySet(PropertySet aSet) : this(osimwrapPINVOKE.new_PropertySet__SWIG_1(PropertySet.getCPtr(aSet)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isEmpty() {
    bool ret = osimwrapPINVOKE.PropertySet_isEmpty(swigCPtr);
    return ret;
  }

  public int getSize() {
    int ret = osimwrapPINVOKE.PropertySet_getSize(swigCPtr);
    return ret;
  }

  public virtual Property_Deprecated get(int i) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertySet_get__SWIG_0(swigCPtr, i);
    Property_Deprecated ret = (cPtr == global::System.IntPtr.Zero) ? null : new Property_Deprecated(cPtr, false);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual Property_Deprecated get(string aName) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertySet_get__SWIG_1(swigCPtr, aName);
    Property_Deprecated ret = (cPtr == global::System.IntPtr.Zero) ? null : new Property_Deprecated(cPtr, false);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual Property_Deprecated contains(string aName) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertySet_contains(swigCPtr, aName);
    Property_Deprecated ret = (cPtr == global::System.IntPtr.Zero) ? null : new Property_Deprecated(cPtr, false);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void append(Property_Deprecated aProperty) {
    osimwrapPINVOKE.PropertySet_append__SWIG_0(swigCPtr, Property_Deprecated.getCPtr(aProperty));
  }

  public virtual void append(Property_Deprecated aProperty, string aName) {
    osimwrapPINVOKE.PropertySet_append__SWIG_1(swigCPtr, Property_Deprecated.getCPtr(aProperty), aName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void remove(string aName) {
    osimwrapPINVOKE.PropertySet_remove(swigCPtr, aName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void clear() {
    osimwrapPINVOKE.PropertySet_clear(swigCPtr);
  }

  public PropertyGroup addGroup(string aGroupName) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertySet_addGroup(swigCPtr, aGroupName);
    PropertyGroup ret = (cPtr == global::System.IntPtr.Zero) ? null : new PropertyGroup(cPtr, false);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addPropertyToGroup(string aGroupName, string aPropertyName) {
    osimwrapPINVOKE.PropertySet_addPropertyToGroup__SWIG_0(swigCPtr, aGroupName, aPropertyName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addPropertyToGroup(PropertyGroup aGroup, string aPropertyName) {
    osimwrapPINVOKE.PropertySet_addPropertyToGroup__SWIG_1(swigCPtr, PropertyGroup.getCPtr(aGroup), aPropertyName);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addPropertyToGroup(PropertyGroup aGroup, Property_Deprecated aProperty) {
    osimwrapPINVOKE.PropertySet_addPropertyToGroup__SWIG_2(swigCPtr, PropertyGroup.getCPtr(aGroup), Property_Deprecated.getCPtr(aProperty));
  }

  public void addPropertyToGroup(string aGroupName, Property_Deprecated aProperty) {
    osimwrapPINVOKE.PropertySet_addPropertyToGroup__SWIG_3(swigCPtr, aGroupName, Property_Deprecated.getCPtr(aProperty));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_OpenSim__ArrayPtrsT_OpenSim__PropertyGroup_t getGroups() {
    SWIGTYPE_p_OpenSim__ArrayPtrsT_OpenSim__PropertyGroup_t ret = new SWIGTYPE_p_OpenSim__ArrayPtrsT_OpenSim__PropertyGroup_t(osimwrapPINVOKE.PropertySet_getGroups(swigCPtr), false);
    return ret;
  }

  public PropertyGroup getGroupContaining(Property_Deprecated aProperty) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.PropertySet_getGroupContaining(swigCPtr, Property_Deprecated.getCPtr(aProperty));
    PropertyGroup ret = (cPtr == global::System.IntPtr.Zero) ? null : new PropertyGroup(cPtr, false);
    return ret;
  }

  public int getGroupIndexContaining(Property_Deprecated aProperty) {
    int ret = osimwrapPINVOKE.PropertySet_getGroupIndexContaining(swigCPtr, Property_Deprecated.getCPtr(aProperty));
    return ret;
  }

}

}
