//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class StateVector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StateVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StateVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~StateVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_StateVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StateVector(double aT, int aN, SWIGTYPE_p_double aData) : this(osimwrapPINVOKE.new_StateVector__SWIG_0(aT, aN, SWIGTYPE_p_double.getCPtr(aData)), true) {
  }

  public StateVector(double aT, int aN) : this(osimwrapPINVOKE.new_StateVector__SWIG_1(aT, aN), true) {
  }

  public StateVector(double aT) : this(osimwrapPINVOKE.new_StateVector__SWIG_2(aT), true) {
  }

  public StateVector() : this(osimwrapPINVOKE.new_StateVector__SWIG_3(), true) {
  }

  public StateVector(StateVector aVector) : this(osimwrapPINVOKE.new_StateVector__SWIG_4(StateVector.getCPtr(aVector)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setStates(double aT, int aN, SWIGTYPE_p_double aY) {
    osimwrapPINVOKE.StateVector_setStates(swigCPtr, aT, aN, SWIGTYPE_p_double.getCPtr(aY));
  }

  public int getSize() {
    int ret = osimwrapPINVOKE.StateVector_getSize(swigCPtr);
    return ret;
  }

  public void setTime(double aT) {
    osimwrapPINVOKE.StateVector_setTime(swigCPtr, aT);
  }

  public double getTime() {
    double ret = osimwrapPINVOKE.StateVector_getTime(swigCPtr);
    return ret;
  }

  public int getDataValue(int aIndex, SWIGTYPE_p_double rValue) {
    int ret = osimwrapPINVOKE.StateVector_getDataValue(swigCPtr, aIndex, SWIGTYPE_p_double.getCPtr(rValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDataValue(int aIndex, SWIGTYPE_p_double aValue) {
    osimwrapPINVOKE.StateVector_setDataValue(swigCPtr, aIndex, SWIGTYPE_p_double.getCPtr(aValue));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_OpenSim__ArrayT_double_t getData() {
    SWIGTYPE_p_OpenSim__ArrayT_double_t ret = new SWIGTYPE_p_OpenSim__ArrayT_double_t(osimwrapPINVOKE.StateVector_getData(swigCPtr), false);
    return ret;
  }

  public void shiftTime(double aValue) {
    osimwrapPINVOKE.StateVector_shiftTime(swigCPtr, aValue);
  }

  public void scaleTime(double aValue) {
    osimwrapPINVOKE.StateVector_scaleTime(swigCPtr, aValue);
  }

  public void add(double aValue) {
    osimwrapPINVOKE.StateVector_add__SWIG_0(swigCPtr, aValue);
  }

  public void add(int aN, SWIGTYPE_p_double aY) {
    osimwrapPINVOKE.StateVector_add__SWIG_1(swigCPtr, aN, SWIGTYPE_p_double.getCPtr(aY));
  }

  public void add(int aN, double aValue) {
    osimwrapPINVOKE.StateVector_add__SWIG_2(swigCPtr, aN, aValue);
  }

  public void add(StateVector aStateVector) {
    osimwrapPINVOKE.StateVector_add__SWIG_3(swigCPtr, StateVector.getCPtr(aStateVector));
  }

  public void subtract(double aValue) {
    osimwrapPINVOKE.StateVector_subtract__SWIG_0(swigCPtr, aValue);
  }

  public void subtract(int aN, SWIGTYPE_p_double aY) {
    osimwrapPINVOKE.StateVector_subtract__SWIG_1(swigCPtr, aN, SWIGTYPE_p_double.getCPtr(aY));
  }

  public void subtract(StateVector aStateVector) {
    osimwrapPINVOKE.StateVector_subtract__SWIG_2(swigCPtr, StateVector.getCPtr(aStateVector));
  }

  public void multiply(double aValue) {
    osimwrapPINVOKE.StateVector_multiply__SWIG_0(swigCPtr, aValue);
  }

  public void multiply(int aN, SWIGTYPE_p_double aY) {
    osimwrapPINVOKE.StateVector_multiply__SWIG_1(swigCPtr, aN, SWIGTYPE_p_double.getCPtr(aY));
  }

  public void multiply(StateVector aStateVector) {
    osimwrapPINVOKE.StateVector_multiply__SWIG_2(swigCPtr, StateVector.getCPtr(aStateVector));
  }

  public void divide(double aValue) {
    osimwrapPINVOKE.StateVector_divide__SWIG_0(swigCPtr, aValue);
  }

  public void divide(int aN, SWIGTYPE_p_double aY) {
    osimwrapPINVOKE.StateVector_divide__SWIG_1(swigCPtr, aN, SWIGTYPE_p_double.getCPtr(aY));
  }

  public void divide(StateVector aStateVector) {
    osimwrapPINVOKE.StateVector_divide__SWIG_2(swigCPtr, StateVector.getCPtr(aStateVector));
  }

}

}
