//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class Thelen2003Muscle : ActivationFiberLengthMuscle {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Thelen2003Muscle(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.Thelen2003Muscle_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Thelen2003Muscle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Thelen2003Muscle() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_Thelen2003Muscle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static Thelen2003Muscle safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.Thelen2003Muscle_safeDownCast(Object.getCPtr(obj));
    Thelen2003Muscle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Thelen2003Muscle(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.Thelen2003Muscle_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.Thelen2003Muscle_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.Thelen2003Muscle_clone(swigCPtr);
    Thelen2003Muscle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Thelen2003Muscle(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.Thelen2003Muscle_getConcreteClassName(swigCPtr);
    return ret;
  }

  public void copyProperty_activation_time_constant(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_activation_time_constant(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_activation_time_constant(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_activation_time_constant__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_activation_time_constant(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_activation_time_constant__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_activation_time_constant(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_activation_time_constant__SWIG_0(swigCPtr, i, value);
  }

  public int append_activation_time_constant(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_activation_time_constant(swigCPtr, value);
    return ret;
  }

  public void constructProperty_activation_time_constant(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_activation_time_constant(swigCPtr, initValue);
  }

  public double get_activation_time_constant() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_activation_time_constant__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_activation_time_constant() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_activation_time_constant__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_activation_time_constant(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_activation_time_constant__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_deactivation_time_constant(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_deactivation_time_constant(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_deactivation_time_constant(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_deactivation_time_constant__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_deactivation_time_constant(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_deactivation_time_constant__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_deactivation_time_constant(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_deactivation_time_constant__SWIG_0(swigCPtr, i, value);
  }

  public int append_deactivation_time_constant(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_deactivation_time_constant(swigCPtr, value);
    return ret;
  }

  public void constructProperty_deactivation_time_constant(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_deactivation_time_constant(swigCPtr, initValue);
  }

  public double get_deactivation_time_constant() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_deactivation_time_constant__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_deactivation_time_constant() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_deactivation_time_constant__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_deactivation_time_constant(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_deactivation_time_constant__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_FmaxTendonStrain(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_FmaxTendonStrain(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_FmaxTendonStrain(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_FmaxTendonStrain__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_FmaxTendonStrain(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_FmaxTendonStrain__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_FmaxTendonStrain(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_FmaxTendonStrain__SWIG_0(swigCPtr, i, value);
  }

  public int append_FmaxTendonStrain(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_FmaxTendonStrain(swigCPtr, value);
    return ret;
  }

  public void constructProperty_FmaxTendonStrain(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_FmaxTendonStrain(swigCPtr, initValue);
  }

  public double get_FmaxTendonStrain() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_FmaxTendonStrain__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_FmaxTendonStrain() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_FmaxTendonStrain__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_FmaxTendonStrain(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_FmaxTendonStrain__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_FmaxMuscleStrain(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_FmaxMuscleStrain(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_FmaxMuscleStrain(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_FmaxMuscleStrain__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_FmaxMuscleStrain(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_FmaxMuscleStrain__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_FmaxMuscleStrain(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_FmaxMuscleStrain__SWIG_0(swigCPtr, i, value);
  }

  public int append_FmaxMuscleStrain(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_FmaxMuscleStrain(swigCPtr, value);
    return ret;
  }

  public void constructProperty_FmaxMuscleStrain(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_FmaxMuscleStrain(swigCPtr, initValue);
  }

  public double get_FmaxMuscleStrain() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_FmaxMuscleStrain__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_FmaxMuscleStrain() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_FmaxMuscleStrain__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_FmaxMuscleStrain(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_FmaxMuscleStrain__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_KshapeActive(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_KshapeActive(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_KshapeActive(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_KshapeActive__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_KshapeActive(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_KshapeActive__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_KshapeActive(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_KshapeActive__SWIG_0(swigCPtr, i, value);
  }

  public int append_KshapeActive(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_KshapeActive(swigCPtr, value);
    return ret;
  }

  public void constructProperty_KshapeActive(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_KshapeActive(swigCPtr, initValue);
  }

  public double get_KshapeActive() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_KshapeActive__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_KshapeActive() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_KshapeActive__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_KshapeActive(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_KshapeActive__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_KshapePassive(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_KshapePassive(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_KshapePassive(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_KshapePassive__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_KshapePassive(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_KshapePassive__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_KshapePassive(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_KshapePassive__SWIG_0(swigCPtr, i, value);
  }

  public int append_KshapePassive(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_KshapePassive(swigCPtr, value);
    return ret;
  }

  public void constructProperty_KshapePassive(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_KshapePassive(swigCPtr, initValue);
  }

  public double get_KshapePassive() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_KshapePassive__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_KshapePassive() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_KshapePassive__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_KshapePassive(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_KshapePassive__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_Af(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_Af(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_Af(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_Af__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_Af(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_Af__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_Af(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_Af__SWIG_0(swigCPtr, i, value);
  }

  public int append_Af(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_Af(swigCPtr, value);
    return ret;
  }

  public void constructProperty_Af(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_Af(swigCPtr, initValue);
  }

  public double get_Af() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_Af__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_Af() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_Af__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_Af(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_Af__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_Flen(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_Flen(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_Flen(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_Flen__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_Flen(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_Flen__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_Flen(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_Flen__SWIG_0(swigCPtr, i, value);
  }

  public int append_Flen(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_Flen(swigCPtr, value);
    return ret;
  }

  public void constructProperty_Flen(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_Flen(swigCPtr, initValue);
  }

  public double get_Flen() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_Flen__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_Flen() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_Flen__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_Flen(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_Flen__SWIG_1(swigCPtr, value);
  }

  public void copyProperty_fv_linear_extrap_threshold(Thelen2003Muscle source) {
    osimwrapPINVOKE.Thelen2003Muscle_copyProperty_fv_linear_extrap_threshold(swigCPtr, Thelen2003Muscle.getCPtr(source));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_fv_linear_extrap_threshold(int i) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_fv_linear_extrap_threshold__SWIG_0(swigCPtr, i);
    return ret;
  }

  public SWIGTYPE_p_double upd_fv_linear_extrap_threshold(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_fv_linear_extrap_threshold__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public void set_fv_linear_extrap_threshold(int i, double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_fv_linear_extrap_threshold__SWIG_0(swigCPtr, i, value);
  }

  public int append_fv_linear_extrap_threshold(double value) {
    int ret = osimwrapPINVOKE.Thelen2003Muscle_append_fv_linear_extrap_threshold(swigCPtr, value);
    return ret;
  }

  public void constructProperty_fv_linear_extrap_threshold(double initValue) {
    osimwrapPINVOKE.Thelen2003Muscle_constructProperty_fv_linear_extrap_threshold(swigCPtr, initValue);
  }

  public double get_fv_linear_extrap_threshold() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_get_fv_linear_extrap_threshold__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double upd_fv_linear_extrap_threshold() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(osimwrapPINVOKE.Thelen2003Muscle_upd_fv_linear_extrap_threshold__SWIG_1(swigCPtr), false);
    return ret;
  }

  public void set_fv_linear_extrap_threshold(double value) {
    osimwrapPINVOKE.Thelen2003Muscle_set_fv_linear_extrap_threshold__SWIG_1(swigCPtr, value);
  }

  public Thelen2003Muscle() : this(osimwrapPINVOKE.new_Thelen2003Muscle__SWIG_0(), true) {
  }

  public Thelen2003Muscle(string aName, double aMaxIsometricForce, double aOptimalFiberLength, double aTendonSlackLength, double aPennationAngle) : this(osimwrapPINVOKE.new_Thelen2003Muscle__SWIG_1(aName, aMaxIsometricForce, aOptimalFiberLength, aTendonSlackLength, aPennationAngle), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getActivationTimeConstant() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getActivationTimeConstant(swigCPtr);
    return ret;
  }

  public double getMinimumActivation() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getMinimumActivation(swigCPtr);
    return ret;
  }

  public double getDeactivationTimeConstant() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getDeactivationTimeConstant(swigCPtr);
    return ret;
  }

  public double getFmaxTendonStrain() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getFmaxTendonStrain(swigCPtr);
    return ret;
  }

  public double getFmaxMuscleStrain() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getFmaxMuscleStrain(swigCPtr);
    return ret;
  }

  public double getKshapeActive() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getKshapeActive(swigCPtr);
    return ret;
  }

  public double getKshapePassive() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getKshapePassive(swigCPtr);
    return ret;
  }

  public double getAf() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getAf(swigCPtr);
    return ret;
  }

  public double getFlen() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getFlen(swigCPtr);
    return ret;
  }

  public double getForceVelocityExtrapolationThreshold() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getForceVelocityExtrapolationThreshold(swigCPtr);
    return ret;
  }

  public double getMinimumFiberLength() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getMinimumFiberLength(swigCPtr);
    return ret;
  }

  public double getMaximumPennationAngle() {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_getMaximumPennationAngle(swigCPtr);
    return ret;
  }

  public bool setActivationTimeConstant(double aActivationTimeConstant) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setActivationTimeConstant(swigCPtr, aActivationTimeConstant);
    return ret;
  }

  public bool setDeactivationTimeConstant(double aDeactivationTimeConstant) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setDeactivationTimeConstant(swigCPtr, aDeactivationTimeConstant);
    return ret;
  }

  public bool setMinimumActivation(double aActivationMinValue) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setMinimumActivation(swigCPtr, aActivationMinValue);
    return ret;
  }

  public bool setFmaxTendonStrain(double aFmaxTendonStrain) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setFmaxTendonStrain(swigCPtr, aFmaxTendonStrain);
    return ret;
  }

  public bool setFmaxFiberStrain(double aFmaxMuscleStrain) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setFmaxFiberStrain(swigCPtr, aFmaxMuscleStrain);
    return ret;
  }

  public bool setKshapeActive(double aKShapeActive) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setKshapeActive(swigCPtr, aKShapeActive);
    return ret;
  }

  public bool setKshapePassive(double aKshapePassive) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setKshapePassive(swigCPtr, aKshapePassive);
    return ret;
  }

  public bool setAf(double aAf) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setAf(swigCPtr, aAf);
    return ret;
  }

  public bool setFlen(double aFlen) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setFlen(swigCPtr, aFlen);
    return ret;
  }

  public bool setForceVelocityExtrapolationThreshold(double aFvThresh) {
    bool ret = osimwrapPINVOKE.Thelen2003Muscle_setForceVelocityExtrapolationThreshold(swigCPtr, aFvThresh);
    return ret;
  }

  public MuscleFirstOrderActivationDynamicModel getActivationModel() {
    MuscleFirstOrderActivationDynamicModel ret = new MuscleFirstOrderActivationDynamicModel(osimwrapPINVOKE.Thelen2003Muscle_getActivationModel(swigCPtr), false);
    return ret;
  }

  public MuscleFixedWidthPennationModel getPennationModel() {
    MuscleFixedWidthPennationModel ret = new MuscleFixedWidthPennationModel(osimwrapPINVOKE.Thelen2003Muscle_getPennationModel(swigCPtr), false);
    return ret;
  }

  public void printCurveToCSVFile(Thelen2003Muscle.CurveType ctype, string path) {
    osimwrapPINVOKE.Thelen2003Muscle_printCurveToCSVFile(swigCPtr, (int)ctype, path);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double computeActuation(SWIGTYPE_p_SimTK__State s) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_computeActuation(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void computeInitialFiberEquilibrium(SWIGTYPE_p_SimTK__State s) {
    osimwrapPINVOKE.Thelen2003Muscle_computeInitialFiberEquilibrium(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double calcActiveFiberForceAlongTendon(double activation, double fiberLength, double fiberVelocity) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_calcActiveFiberForceAlongTendon(swigCPtr, activation, fiberLength, fiberVelocity);
    return ret;
  }

  public override double calcInextensibleTendonActiveFiberForce(SWIGTYPE_p_SimTK__State s, double aActivation) {
    double ret = osimwrapPINVOKE.Thelen2003Muscle_calcInextensibleTendonActiveFiberForce(swigCPtr, SWIGTYPE_p_SimTK__State.getCPtr(s), aActivation);
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum CurveType {
    FiberActiveForceLength,
    FiberPassiveForceLength,
    FiberForceVelocity,
    TendonForceLength
  }

}

}
