//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class Units : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Units(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Units obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Units() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_Units(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Units() : this(osimwrapPINVOKE.new_Units__SWIG_0(), true) {
  }

  public Units(Units aUnits) : this(osimwrapPINVOKE.new_Units__SWIG_1(Units.getCPtr(aUnits)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Units(string aString) : this(osimwrapPINVOKE.new_Units__SWIG_2(aString), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Units(Units.UnitType aType) : this(osimwrapPINVOKE.new_Units__SWIG_3((int)aType), true) {
  }

  public double convertTo(Units.UnitType aType, double aValue) {
    double ret = osimwrapPINVOKE.Units_convertTo__SWIG_0(swigCPtr, (int)aType, aValue);
    return ret;
  }

  public double convertTo(Units.UnitType aType) {
    double ret = osimwrapPINVOKE.Units_convertTo__SWIG_1(swigCPtr, (int)aType);
    return ret;
  }

  public double convertTo(Units aUnit) {
    double ret = osimwrapPINVOKE.Units_convertTo__SWIG_2(swigCPtr, Units.getCPtr(aUnit));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Units.UnitType getType() {
    Units.UnitType ret = (Units.UnitType)osimwrapPINVOKE.Units_getType(swigCPtr);
    return ret;
  }

  public string getLabel() {
    string ret = osimwrapPINVOKE.Units_getLabel(swigCPtr);
    return ret;
  }

  public string getAbbreviation() {
    string ret = osimwrapPINVOKE.Units_getAbbreviation(swigCPtr);
    return ret;
  }

  public enum UnitType {
    UnknownUnits = 0,
    Radians,
    Degrees,
    Millimeters,
    Centimeters,
    Meters,
    Seconds,
    Milliseconds,
    Newtons
  }

}

}
