//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Osim {

public class WrapSphereObst : WrapObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal WrapSphereObst(global::System.IntPtr cPtr, bool cMemoryOwn) : base(osimwrapPINVOKE.WrapSphereObst_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WrapSphereObst obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~WrapSphereObst() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          osimwrapPINVOKE.delete_WrapSphereObst(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static WrapSphereObst safeDownCast(Object obj) {
    global::System.IntPtr cPtr = osimwrapPINVOKE.WrapSphereObst_safeDownCast(Object.getCPtr(obj));
    WrapSphereObst ret = (cPtr == global::System.IntPtr.Zero) ? null : new WrapSphereObst(cPtr, false);
    return ret;
  }

  public override void assign(Object aObject) {
    osimwrapPINVOKE.WrapSphereObst_assign(swigCPtr, Object.getCPtr(aObject));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public new static string getClassName() {
    string ret = osimwrapPINVOKE.WrapSphereObst_getClassName();
    return ret;
  }

  public override Object clone() {
    global::System.IntPtr cPtr = osimwrapPINVOKE.WrapSphereObst_clone(swigCPtr);
    WrapSphereObst ret = (cPtr == global::System.IntPtr.Zero) ? null : new WrapSphereObst(cPtr, false);
    return ret;
  }

  public override string getConcreteClassName() {
    string ret = osimwrapPINVOKE.WrapSphereObst_getConcreteClassName(swigCPtr);
    return ret;
  }

  public WrapSphereObst() : this(osimwrapPINVOKE.new_WrapSphereObst__SWIG_0(), true) {
  }

  public WrapSphereObst(WrapSphereObst aWrapSphereObst) : this(osimwrapPINVOKE.new_WrapSphereObst__SWIG_1(WrapSphereObst.getCPtr(aWrapSphereObst)), true) {
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyData(WrapSphereObst aWrapSphereObst) {
    osimwrapPINVOKE.WrapSphereObst_copyData(swigCPtr, WrapSphereObst.getCPtr(aWrapSphereObst));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getRadius() {
    double ret = osimwrapPINVOKE.WrapSphereObst_getRadius(swigCPtr);
    return ret;
  }

  public void setRadius(double aRadius) {
    osimwrapPINVOKE.WrapSphereObst_setRadius(swigCPtr, aRadius);
  }

  public double getLength() {
    double ret = osimwrapPINVOKE.WrapSphereObst_getLength(swigCPtr);
    return ret;
  }

  public void setLength(double aLength) {
    osimwrapPINVOKE.WrapSphereObst_setLength(swigCPtr, aLength);
  }

  public override string getWrapTypeName() {
    string ret = osimwrapPINVOKE.WrapSphereObst_getWrapTypeName(swigCPtr);
    return ret;
  }

  public override string getDimensionsString() {
    string ret = osimwrapPINVOKE.WrapSphereObst_getDimensionsString(swigCPtr);
    return ret;
  }

  public override void scale(SWIGTYPE_p_SimTK__Vec3 aScaleFactors) {
    osimwrapPINVOKE.WrapSphereObst_scale(swigCPtr, SWIGTYPE_p_SimTK__Vec3.getCPtr(aScaleFactors));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void connectToModelAndBody(Model aModel, Body aBody) {
    osimwrapPINVOKE.WrapSphereObst_connectToModelAndBody(swigCPtr, Model.getCPtr(aModel), Body.getCPtr(aBody));
    if (osimwrapPINVOKE.SWIGPendingException.Pending) throw osimwrapPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
