/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class AnalyticCylinder : AnalyticGeometry {
  private HandleRef swigCPtr;

  internal AnalyticCylinder(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.AnalyticCylinder_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AnalyticCylinder obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AnalyticCylinder() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_AnalyticCylinder(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe AnalyticCylinder() : this(CSharpWrapOpenSimPINVOKE.new_AnalyticCylinder__SWIG_0(), true) {
  }

  public unsafe AnalyticCylinder(double radius, double height) : this(CSharpWrapOpenSimPINVOKE.new_AnalyticCylinder__SWIG_1(radius, height), true) {
  }

  public unsafe void getCylinderParams(SWIGTYPE_p_double arg0) {
    CSharpWrapOpenSimPINVOKE.AnalyticCylinder_getCylinderParams(swigCPtr, SWIGTYPE_p_double.getCPtr(arg0));
  }

  public unsafe static AnalyticCylinder dynamic_cast(Geometry geometry) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.AnalyticCylinder_dynamic_cast(Geometry.getCPtr(geometry));
    AnalyticCylinder ret = (cPtr == IntPtr.Zero) ? null : new AnalyticCylinder(cPtr, false);
    return ret;
  }

}

}
