/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class ArrowGeometry : LineGeometry {
  private HandleRef swigCPtr;

  internal ArrowGeometry(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.ArrowGeometry_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ArrowGeometry obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArrowGeometry() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_ArrowGeometry(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe ArrowGeometry(Vec3 aPoint1, Vec3 aUnitDirTo, double aLength) : this(CSharpWrapOpenSimPINVOKE.new_ArrowGeometry(Vec3.getCPtr(aPoint1), Vec3.getCPtr(aUnitDirTo), aLength), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
