/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class Body : ModelComponent {
  private HandleRef swigCPtr;

  internal Body(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.Body_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Body obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Body() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_Body(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static Body safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Body_safeDownCast(OpenSimObject.getCPtr(obj));
    Body ret = (cPtr == IntPtr.Zero) ? null : new Body(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.Body_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.Body_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Body_clone(swigCPtr);
    Body ret = (cPtr == IntPtr.Zero) ? null : new Body(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.Body_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe Body() : this(CSharpWrapOpenSimPINVOKE.new_Body__SWIG_0(), true) {
  }

  public unsafe Body(string aName, double aMass, Vec3 aMassCenter, Inertia aInertia) : this(CSharpWrapOpenSimPINVOKE.new_Body__SWIG_1(aName, aMass, Vec3.getCPtr(aMassCenter), Inertia.getCPtr(aInertia)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Body(Body aBody) : this(CSharpWrapOpenSimPINVOKE.new_Body__SWIG_2(Body.getCPtr(aBody)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyData(Body aBody) {
    CSharpWrapOpenSimPINVOKE.Body_copyData(swigCPtr, Body.getCPtr(aBody));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addDisplayGeometry(string aGeometryFileName) {
    CSharpWrapOpenSimPINVOKE.Body_addDisplayGeometry(swigCPtr, aGeometryFileName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double getMass() {
    double ret = CSharpWrapOpenSimPINVOKE.Body_getMass(swigCPtr);
    return ret;
  }

  public unsafe bool setMass(double aMass) {
    bool ret = CSharpWrapOpenSimPINVOKE.Body_setMass(swigCPtr, aMass);
    return ret;
  }

  public unsafe void getMassCenter(Vec3 rVec) {
    CSharpWrapOpenSimPINVOKE.Body_getMassCenter(swigCPtr, Vec3.getCPtr(rVec));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool setMassCenter(Vec3 aVec) {
    bool ret = CSharpWrapOpenSimPINVOKE.Body_setMassCenter(swigCPtr, Vec3.getCPtr(aVec));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getInertia(Mat33 rInertia) {
    CSharpWrapOpenSimPINVOKE.Body_getInertia__SWIG_0(swigCPtr, Mat33.getCPtr(rInertia));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool setInertia(Inertia aInertia) {
    bool ret = CSharpWrapOpenSimPINVOKE.Body_setInertia__SWIG_0(swigCPtr, Inertia.getCPtr(aInertia));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool hasJoint() {
    bool ret = CSharpWrapOpenSimPINVOKE.Body_hasJoint(swigCPtr);
    return ret;
  }

  public unsafe Joint getJoint() {
    Joint ret = new Joint(CSharpWrapOpenSimPINVOKE.Body_getJoint(swigCPtr), false);
    return ret;
  }

  public unsafe void setJoint(Joint aJoint) {
    CSharpWrapOpenSimPINVOKE.Body_setJoint(swigCPtr, Joint.getCPtr(aJoint));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void scale(Vec3 aScaleFactors, bool aScaleMass) {
    CSharpWrapOpenSimPINVOKE.Body_scale__SWIG_0(swigCPtr, Vec3.getCPtr(aScaleFactors), aScaleMass);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void scale(Vec3 aScaleFactors) {
    CSharpWrapOpenSimPINVOKE.Body_scale__SWIG_1(swigCPtr, Vec3.getCPtr(aScaleFactors));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void scaleInertialProperties(Vec3 aScaleFactors, bool aScaleMass) {
    CSharpWrapOpenSimPINVOKE.Body_scaleInertialProperties__SWIG_0(swigCPtr, Vec3.getCPtr(aScaleFactors), aScaleMass);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void scaleInertialProperties(Vec3 aScaleFactors) {
    CSharpWrapOpenSimPINVOKE.Body_scaleInertialProperties__SWIG_1(swigCPtr, Vec3.getCPtr(aScaleFactors));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void scaleMass(double aScaleFactor) {
    CSharpWrapOpenSimPINVOKE.Body_scaleMass(swigCPtr, aScaleFactor);
  }

  public unsafe VisibleObject getDisplayer() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Body_getDisplayer(swigCPtr);
    VisibleObject ret = (cPtr == IntPtr.Zero) ? null : new VisibleObject(cPtr, false);
    return ret;
  }

  public unsafe VisibleObject updDisplayer() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Body_updDisplayer(swigCPtr);
    VisibleObject ret = (cPtr == IntPtr.Zero) ? null : new VisibleObject(cPtr, false);
    return ret;
  }

  public unsafe int getIndex() {
    int ret = CSharpWrapOpenSimPINVOKE.Body_getIndex(swigCPtr);
    return ret;
  }

  public unsafe void getScaleFactors(Vec3 aScaleFactors) {
    CSharpWrapOpenSimPINVOKE.Body_getScaleFactors(swigCPtr, Vec3.getCPtr(aScaleFactors));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addWrapObject(WrapObject wrapObject) {
    CSharpWrapOpenSimPINVOKE.Body_addWrapObject(swigCPtr, WrapObject.getCPtr(wrapObject));
  }

  public unsafe WrapObject getWrapObject(string aName) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Body_getWrapObject(swigCPtr, aName);
    WrapObject ret = (cPtr == IntPtr.Zero) ? null : new WrapObject(cPtr, false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe WrapObjectSet getWrapObjectSet() {
    WrapObjectSet ret = new WrapObjectSet(CSharpWrapOpenSimPINVOKE.Body_getWrapObjectSet(swigCPtr), false);
    return ret;
  }

  public unsafe MassProperties getMassProperties() {
    MassProperties ret = new MassProperties(CSharpWrapOpenSimPINVOKE.Body_getMassProperties(swigCPtr), true);
    return ret;
  }

  public unsafe int getNumStateVariables() {
    int ret = CSharpWrapOpenSimPINVOKE.Body_getNumStateVariables(swigCPtr);
    return ret;
  }

  public unsafe void getCenterOfMass(SWIGTYPE_p_double dCom) {
    CSharpWrapOpenSimPINVOKE.Body_getCenterOfMass(swigCPtr, SWIGTYPE_p_double.getCPtr(dCom));
  }

  public unsafe void getInertia(ArrayDouble rInertia) {
    CSharpWrapOpenSimPINVOKE.Body_getInertia__SWIG_1(swigCPtr, ArrayDouble.getCPtr(rInertia));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setInertia(ArrayDouble aInertia) {
    CSharpWrapOpenSimPINVOKE.Body_setInertia__SWIG_1(swigCPtr, ArrayDouble.getCPtr(aInertia));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
