/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class CMC_Point : CMC_Task {
  private HandleRef swigCPtr;

  internal CMC_Point(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.CMC_Point_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CMC_Point obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CMC_Point() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_CMC_Point(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static CMC_Point safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CMC_Point_safeDownCast(OpenSimObject.getCPtr(obj));
    CMC_Point ret = (cPtr == IntPtr.Zero) ? null : new CMC_Point(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.CMC_Point_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CMC_Point_clone(swigCPtr);
    CMC_Point ret = (cPtr == IntPtr.Zero) ? null : new CMC_Point(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.CMC_Point_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe CMC_Point(Vec3 aPoint) : this(CSharpWrapOpenSimPINVOKE.new_CMC_Point__SWIG_0(Vec3.getCPtr(aPoint)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe CMC_Point() : this(CSharpWrapOpenSimPINVOKE.new_CMC_Point__SWIG_1(), true) {
  }

  public unsafe CMC_Point(CMC_Point aTask) : this(CSharpWrapOpenSimPINVOKE.new_CMC_Point__SWIG_2(CMC_Point.getCPtr(aTask)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setModel(Model aModel) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_setModel(swigCPtr, Model.getCPtr(aModel));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setPoint(Vec3 aPoint) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_setPoint(swigCPtr, Vec3.getCPtr(aPoint));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vec3 getPoint() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.CMC_Point_getPoint(swigCPtr), true);
    return ret;
  }

  public unsafe void computeErrors(State s, double aT) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_computeErrors(swigCPtr, State.getCPtr(s), aT);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeDesiredAccelerations(State s, double aT) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_computeDesiredAccelerations__SWIG_0(swigCPtr, State.getCPtr(s), aT);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeDesiredAccelerations(State s, double aTI, double aTF) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_computeDesiredAccelerations__SWIG_1(swigCPtr, State.getCPtr(s), aTI, aTF);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeAccelerations(State s) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_computeAccelerations(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode, int versionNumber) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_updateFromXMLNode__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode), versionNumber);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode) {
    CSharpWrapOpenSimPINVOKE.CMC_Point_updateFromXMLNode__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
