/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class CMC_Task : TrackingTask {
  private HandleRef swigCPtr;

  internal CMC_Task(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.CMC_Task_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CMC_Task obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CMC_Task() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_CMC_Task(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static CMC_Task safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CMC_Task_safeDownCast(OpenSimObject.getCPtr(obj));
    CMC_Task ret = (cPtr == IntPtr.Zero) ? null : new CMC_Task(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CMC_Task_clone(swigCPtr);
    CMC_Task ret = (cPtr == IntPtr.Zero) ? null : new CMC_Task(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe void setWRTBodyName(string aBodyName) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setWRTBodyName(swigCPtr, aBodyName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string getWRTBodyName() {
    string ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getWRTBodyName(swigCPtr);
    return ret;
  }

  public unsafe void setExpressBodyName(string aBodyName) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setExpressBodyName(swigCPtr, aBodyName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string getExpressBodyName() {
    string ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getExpressBodyName(swigCPtr);
    return ret;
  }

  public unsafe void setActive(bool a0, bool a1, bool a2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setActive__SWIG_0(swigCPtr, a0, a1, a2);
  }

  public unsafe void setActive(bool a0, bool a1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setActive__SWIG_1(swigCPtr, a0, a1);
  }

  public unsafe void setActive(bool a0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setActive__SWIG_2(swigCPtr, a0);
  }

  public unsafe bool getActive(int aWhich) {
    bool ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getActive(swigCPtr, aWhich);
    return ret;
  }

  public unsafe void setWeight(double aW0, double aW1, double aW2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setWeight__SWIG_0(swigCPtr, aW0, aW1, aW2);
  }

  public unsafe void setWeight(double aW0, double aW1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setWeight__SWIG_1(swigCPtr, aW0, aW1);
  }

  public unsafe void setWeight(double aW0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setWeight__SWIG_2(swigCPtr, aW0);
  }

  public unsafe double getWeight(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getWeight(swigCPtr, aWhich);
    return ret;
  }

  public unsafe void setKP(double aK0, double aK1, double aK2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKP__SWIG_0(swigCPtr, aK0, aK1, aK2);
  }

  public unsafe void setKP(double aK0, double aK1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKP__SWIG_1(swigCPtr, aK0, aK1);
  }

  public unsafe void setKP(double aK0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKP__SWIG_2(swigCPtr, aK0);
  }

  public unsafe double getKP(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getKP(swigCPtr, aWhich);
    return ret;
  }

  public unsafe void setKV(double aK0, double aK1, double aK2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKV__SWIG_0(swigCPtr, aK0, aK1, aK2);
  }

  public unsafe void setKV(double aK0, double aK1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKV__SWIG_1(swigCPtr, aK0, aK1);
  }

  public unsafe void setKV(double aK0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKV__SWIG_2(swigCPtr, aK0);
  }

  public unsafe double getKV(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getKV(swigCPtr, aWhich);
    return ret;
  }

  public unsafe void setKA(double aK0, double aK1, double aK2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKA__SWIG_0(swigCPtr, aK0, aK1, aK2);
  }

  public unsafe void setKA(double aK0, double aK1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKA__SWIG_1(swigCPtr, aK0, aK1);
  }

  public unsafe void setKA(double aK0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setKA__SWIG_2(swigCPtr, aK0);
  }

  public unsafe double getKA(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getKA(swigCPtr, aWhich);
    return ret;
  }

  public unsafe void setDirection_0(Vec3 aR) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setDirection_0(swigCPtr, Vec3.getCPtr(aR));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getDirection_0(Vec3 rR) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_getDirection_0(swigCPtr, Vec3.getCPtr(rR));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setDirection_1(Vec3 aR) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setDirection_1(swigCPtr, Vec3.getCPtr(aR));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getDirection_1(Vec3 rR) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_getDirection_1(swigCPtr, Vec3.getCPtr(rR));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setDirection_2(Vec3 aR) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setDirection_2(swigCPtr, Vec3.getCPtr(aR));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getDirection_2(Vec3 rR) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_getDirection_2(swigCPtr, Vec3.getCPtr(rR));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Function getTaskFunction(int aWhich) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CMC_Task_getTaskFunction(swigCPtr, aWhich);
    Function ret = (cPtr == IntPtr.Zero) ? null : new Function(cPtr, false);
    return ret;
  }

  public unsafe void setTaskFunctionsForVelocity(Function aF0, Function aF1, Function aF2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setTaskFunctionsForVelocity__SWIG_0(swigCPtr, Function.getCPtr(aF0), Function.getCPtr(aF1), Function.getCPtr(aF2));
  }

  public unsafe void setTaskFunctionsForVelocity(Function aF0, Function aF1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setTaskFunctionsForVelocity__SWIG_1(swigCPtr, Function.getCPtr(aF0), Function.getCPtr(aF1));
  }

  public unsafe void setTaskFunctionsForVelocity(Function aF0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setTaskFunctionsForVelocity__SWIG_2(swigCPtr, Function.getCPtr(aF0));
  }

  public unsafe Function getTaskFunctionForVelocity(int aWhich) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CMC_Task_getTaskFunctionForVelocity(swigCPtr, aWhich);
    Function ret = (cPtr == IntPtr.Zero) ? null : new Function(cPtr, false);
    return ret;
  }

  public unsafe void setTaskFunctionsForAcceleration(Function aF0, Function aF1, Function aF2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setTaskFunctionsForAcceleration__SWIG_0(swigCPtr, Function.getCPtr(aF0), Function.getCPtr(aF1), Function.getCPtr(aF2));
  }

  public unsafe void setTaskFunctionsForAcceleration(Function aF0, Function aF1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setTaskFunctionsForAcceleration__SWIG_1(swigCPtr, Function.getCPtr(aF0), Function.getCPtr(aF1));
  }

  public unsafe void setTaskFunctionsForAcceleration(Function aF0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setTaskFunctionsForAcceleration__SWIG_2(swigCPtr, Function.getCPtr(aF0));
  }

  public unsafe Function getTaskFunctionForAcceleration(int aWhich) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CMC_Task_getTaskFunctionForAcceleration(swigCPtr, aWhich);
    Function ret = (cPtr == IntPtr.Zero) ? null : new Function(cPtr, false);
    return ret;
  }

  public unsafe double getTaskPosition(int aWhich, double aT) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getTaskPosition(swigCPtr, aWhich, aT);
    return ret;
  }

  public unsafe double getTaskVelocity(int aWhich, double aT) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getTaskVelocity(swigCPtr, aWhich, aT);
    return ret;
  }

  public unsafe double getTaskAcceleration(int aWhich, double aT) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getTaskAcceleration(swigCPtr, aWhich, aT);
    return ret;
  }

  public unsafe void setPositionErrorLast(double aE0, double aE1, double aE2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setPositionErrorLast__SWIG_0(swigCPtr, aE0, aE1, aE2);
  }

  public unsafe void setPositionErrorLast(double aE0, double aE1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setPositionErrorLast__SWIG_1(swigCPtr, aE0, aE1);
  }

  public unsafe void setPositionErrorLast(double aE0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setPositionErrorLast__SWIG_2(swigCPtr, aE0);
  }

  public unsafe double getPositionErrorLast(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getPositionErrorLast(swigCPtr, aWhich);
    return ret;
  }

  public unsafe void setVelocityErrorLast(double aE0, double aE1, double aE2) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setVelocityErrorLast__SWIG_0(swigCPtr, aE0, aE1, aE2);
  }

  public unsafe void setVelocityErrorLast(double aE0, double aE1) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setVelocityErrorLast__SWIG_1(swigCPtr, aE0, aE1);
  }

  public unsafe void setVelocityErrorLast(double aE0) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_setVelocityErrorLast__SWIG_2(swigCPtr, aE0);
  }

  public unsafe double getVelocityErrorLast(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getVelocityErrorLast(swigCPtr, aWhich);
    return ret;
  }

  public unsafe double getPositionError(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getPositionError(swigCPtr, aWhich);
    return ret;
  }

  public unsafe double getVelocityError(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getVelocityError(swigCPtr, aWhich);
    return ret;
  }

  public unsafe double getDesiredAcceleration(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getDesiredAcceleration(swigCPtr, aWhich);
    return ret;
  }

  public unsafe double getAcceleration(int aWhich) {
    double ret = CSharpWrapOpenSimPINVOKE.CMC_Task_getAcceleration(swigCPtr, aWhich);
    return ret;
  }

  public unsafe void computeErrors(State s, double aT) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_computeErrors(swigCPtr, State.getCPtr(s), aT);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeDesiredAccelerations(State s, double aT) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_computeDesiredAccelerations__SWIG_0(swigCPtr, State.getCPtr(s), aT);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeDesiredAccelerations(State s, double aTI, double aTF) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_computeDesiredAccelerations__SWIG_1(swigCPtr, State.getCPtr(s), aTI, aTF);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeAccelerations(State s) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_computeAccelerations(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeJacobian() {
    CSharpWrapOpenSimPINVOKE.CMC_Task_computeJacobian(swigCPtr);
  }

  public unsafe void computeEffectiveMassMatrix() {
    CSharpWrapOpenSimPINVOKE.CMC_Task_computeEffectiveMassMatrix(swigCPtr);
  }

  public unsafe void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode, int versionNumber) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_updateFromXMLNode__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode), versionNumber);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode) {
    CSharpWrapOpenSimPINVOKE.CMC_Task_updateFromXMLNode__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
