/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class ContactHalfSpace : ContactGeometry {
  private HandleRef swigCPtr;

  internal ContactHalfSpace(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.ContactHalfSpace_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ContactHalfSpace obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ContactHalfSpace() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_ContactHalfSpace(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static ContactHalfSpace safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.ContactHalfSpace_safeDownCast(OpenSimObject.getCPtr(obj));
    ContactHalfSpace ret = (cPtr == IntPtr.Zero) ? null : new ContactHalfSpace(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.ContactHalfSpace_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.ContactHalfSpace_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.ContactHalfSpace_clone(swigCPtr);
    ContactHalfSpace ret = (cPtr == IntPtr.Zero) ? null : new ContactHalfSpace(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.ContactHalfSpace_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe ContactHalfSpace() : this(CSharpWrapOpenSimPINVOKE.new_ContactHalfSpace__SWIG_0(), true) {
  }

  public unsafe ContactHalfSpace(Vec3 location, Vec3 orientation, Body body) : this(CSharpWrapOpenSimPINVOKE.new_ContactHalfSpace__SWIG_1(Vec3.getCPtr(location), Vec3.getCPtr(orientation), Body.getCPtr(body)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ContactHalfSpace(Vec3 location, Vec3 orientation, Body body, string name) : this(CSharpWrapOpenSimPINVOKE.new_ContactHalfSpace__SWIG_2(Vec3.getCPtr(location), Vec3.getCPtr(orientation), Body.getCPtr(body), name), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ContactHalfSpace(ContactHalfSpace geom) : this(CSharpWrapOpenSimPINVOKE.new_ContactHalfSpace__SWIG_3(ContactHalfSpace.getCPtr(geom)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SWIGTYPE_p_SimTK__ContactGeometry createSimTKContactGeometry() {
    SWIGTYPE_p_SimTK__ContactGeometry ret = new SWIGTYPE_p_SimTK__ContactGeometry(CSharpWrapOpenSimPINVOKE.ContactHalfSpace_createSimTKContactGeometry(swigCPtr), true);
    return ret;
  }

}

}
