/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class CoordinateSet : ModelComponentSetCoordinates {
  private HandleRef swigCPtr;

  internal CoordinateSet(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.CoordinateSet_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CoordinateSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CoordinateSet() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_CoordinateSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static CoordinateSet safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CoordinateSet_safeDownCast(OpenSimObject.getCPtr(obj));
    CoordinateSet ret = (cPtr == IntPtr.Zero) ? null : new CoordinateSet(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.CoordinateSet_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.CoordinateSet_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.CoordinateSet_clone(swigCPtr);
    CoordinateSet ret = (cPtr == IntPtr.Zero) ? null : new CoordinateSet(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.CoordinateSet_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe CoordinateSet() : this(CSharpWrapOpenSimPINVOKE.new_CoordinateSet__SWIG_0(), true) {
  }

  public unsafe CoordinateSet(Model model) : this(CSharpWrapOpenSimPINVOKE.new_CoordinateSet__SWIG_1(Model.getCPtr(model)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe CoordinateSet(Model model, string aFileName, bool aUpdateFromXMLNode) : this(CSharpWrapOpenSimPINVOKE.new_CoordinateSet__SWIG_2(Model.getCPtr(model), aFileName, aUpdateFromXMLNode), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe CoordinateSet(Model model, string aFileName) : this(CSharpWrapOpenSimPINVOKE.new_CoordinateSet__SWIG_3(Model.getCPtr(model), aFileName), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe CoordinateSet(CoordinateSet aCoordinateSet) : this(CSharpWrapOpenSimPINVOKE.new_CoordinateSet__SWIG_4(CoordinateSet.getCPtr(aCoordinateSet)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void populate(Model model) {
    CSharpWrapOpenSimPINVOKE.CoordinateSet_populate(swigCPtr, Model.getCPtr(model));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getSpeedNames(ArrayStr rNames) {
    CSharpWrapOpenSimPINVOKE.CoordinateSet_getSpeedNames(swigCPtr, ArrayStr.getCPtr(rNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
