/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class DecorativeMesh : DecorativeGeometry {
  private HandleRef swigCPtr;

  internal DecorativeMesh(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.DecorativeMesh_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DecorativeMesh obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DecorativeMesh() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_DecorativeMesh(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe DecorativeMesh(SWIGTYPE_p_PolygonalMesh mesh) : this(CSharpWrapOpenSimPINVOKE.new_DecorativeMesh(SWIGTYPE_p_PolygonalMesh.getCPtr(mesh)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SWIGTYPE_p_PolygonalMesh getMesh() {
    SWIGTYPE_p_PolygonalMesh ret = new SWIGTYPE_p_PolygonalMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_getMesh(swigCPtr), false);
    return ret;
  }

  public unsafe DecorativeMesh setBodyId(int b) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setBodyId(swigCPtr, b), false);
    return ret;
  }

  public unsafe DecorativeMesh setTransform(Transform X_BD) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setTransform(swigCPtr, Transform.getCPtr(X_BD)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe DecorativeMesh setResolution(double r) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setResolution(swigCPtr, r), false);
    return ret;
  }

  public unsafe DecorativeMesh setScaleFactors(Vec3 s) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setScaleFactors(swigCPtr, Vec3.getCPtr(s)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe DecorativeMesh setColor(Vec3 rgb) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setColor(swigCPtr, Vec3.getCPtr(rgb)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe DecorativeMesh setOpacity(double o) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setOpacity(swigCPtr, o), false);
    return ret;
  }

  public unsafe DecorativeMesh setLineThickness(double t) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setLineThickness(swigCPtr, t), false);
    return ret;
  }

  public unsafe DecorativeMesh setRepresentation(DecorativeGeometry.Representation r) {
    DecorativeMesh ret = new DecorativeMesh(CSharpWrapOpenSimPINVOKE.DecorativeMesh_setRepresentation(swigCPtr, (int)r), false);
    return ret;
  }

}

}
