/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class DecorativeBrick : DecorativeGeometry {
  private HandleRef swigCPtr;

  internal DecorativeBrick(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.DecorativeBrick_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DecorativeBrick obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DecorativeBrick() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_DecorativeBrick(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe DecorativeBrick(Vec3 halfLengths) : this(CSharpWrapOpenSimPINVOKE.new_DecorativeBrick__SWIG_0(Vec3.getCPtr(halfLengths)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe DecorativeBrick() : this(CSharpWrapOpenSimPINVOKE.new_DecorativeBrick__SWIG_1(), true) {
  }

  public unsafe DecorativeBrick setHalfLengths(Vec3 arg0) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setHalfLengths(swigCPtr, Vec3.getCPtr(arg0)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe Vec3 getHalfLengths() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.DecorativeBrick_getHalfLengths(swigCPtr), false);
    return ret;
  }

  public unsafe DecorativeBrick setBodyId(int b) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setBodyId(swigCPtr, b), false);
    return ret;
  }

  public unsafe DecorativeBrick setTransform(Transform X_BD) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setTransform(swigCPtr, Transform.getCPtr(X_BD)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe DecorativeBrick setResolution(double r) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setResolution(swigCPtr, r), false);
    return ret;
  }

  public unsafe DecorativeBrick setScaleFactors(Vec3 s) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setScaleFactors(swigCPtr, Vec3.getCPtr(s)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe DecorativeBrick setColor(Vec3 rgb) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setColor(swigCPtr, Vec3.getCPtr(rgb)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe DecorativeBrick setOpacity(double o) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setOpacity(swigCPtr, o), false);
    return ret;
  }

  public unsafe DecorativeBrick setLineThickness(double t) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setLineThickness(swigCPtr, t), false);
    return ret;
  }

  public unsafe DecorativeBrick setRepresentation(DecorativeGeometry.Representation r) {
    DecorativeBrick ret = new DecorativeBrick(CSharpWrapOpenSimPINVOKE.DecorativeBrick_setRepresentation(swigCPtr, (int)r), false);
    return ret;
  }

}

}
