/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class ExpressionBasedPointToPointForce : Force {
  private HandleRef swigCPtr;

  internal ExpressionBasedPointToPointForce(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ExpressionBasedPointToPointForce obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ExpressionBasedPointToPointForce() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_ExpressionBasedPointToPointForce(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static ExpressionBasedPointToPointForce safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_safeDownCast(OpenSimObject.getCPtr(obj));
    ExpressionBasedPointToPointForce ret = (cPtr == IntPtr.Zero) ? null : new ExpressionBasedPointToPointForce(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_clone(swigCPtr);
    ExpressionBasedPointToPointForce ret = (cPtr == IntPtr.Zero) ? null : new ExpressionBasedPointToPointForce(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe void copyProperty_body1(ExpressionBasedPointToPointForce source) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_copyProperty_body1(swigCPtr, ExpressionBasedPointToPointForce.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string get_body1(int i) {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_body1__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_std__string upd_body1(int i) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_body1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_body1(int i, string value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_body1__SWIG_0(swigCPtr, i, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_body1(string value) {
    int ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_append_body1(swigCPtr, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_body1() {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_constructProperty_body1__SWIG_0(swigCPtr);
  }

  public unsafe void constructProperty_body1(string initValue) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_constructProperty_body1__SWIG_1(swigCPtr, initValue);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string get_body1() {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_body1__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_std__string upd_body1() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_body1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_body1(string value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_body1__SWIG_1(swigCPtr, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_body2(ExpressionBasedPointToPointForce source) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_copyProperty_body2(swigCPtr, ExpressionBasedPointToPointForce.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string get_body2(int i) {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_body2__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_std__string upd_body2(int i) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_body2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_body2(int i, string value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_body2__SWIG_0(swigCPtr, i, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_body2(string value) {
    int ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_append_body2(swigCPtr, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_body2() {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_constructProperty_body2__SWIG_0(swigCPtr);
  }

  public unsafe void constructProperty_body2(string initValue) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_constructProperty_body2__SWIG_1(swigCPtr, initValue);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string get_body2() {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_body2__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_std__string upd_body2() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_body2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_body2(string value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_body2__SWIG_1(swigCPtr, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_point1(ExpressionBasedPointToPointForce source) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_copyProperty_point1(swigCPtr, ExpressionBasedPointToPointForce.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vec3 get_point1(int i) {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_point1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe Vec3 upd_point1(int i) {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_point1__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_point1(int i, Vec3 value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_point1__SWIG_0(swigCPtr, i, Vec3.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_point1(Vec3 value) {
    int ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_append_point1(swigCPtr, Vec3.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_point1(Vec3 initValue) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_constructProperty_point1(swigCPtr, Vec3.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vec3 get_point1() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_point1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe Vec3 upd_point1() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_point1__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_point1(Vec3 value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_point1__SWIG_1(swigCPtr, Vec3.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_point2(ExpressionBasedPointToPointForce source) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_copyProperty_point2(swigCPtr, ExpressionBasedPointToPointForce.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vec3 get_point2(int i) {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_point2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe Vec3 upd_point2(int i) {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_point2__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_point2(int i, Vec3 value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_point2__SWIG_0(swigCPtr, i, Vec3.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_point2(Vec3 value) {
    int ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_append_point2(swigCPtr, Vec3.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_point2(Vec3 initValue) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_constructProperty_point2(swigCPtr, Vec3.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vec3 get_point2() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_point2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe Vec3 upd_point2() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_point2__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_point2(Vec3 value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_point2__SWIG_1(swigCPtr, Vec3.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_expression(ExpressionBasedPointToPointForce source) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_copyProperty_expression(swigCPtr, ExpressionBasedPointToPointForce.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string get_expression(int i) {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_expression__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_std__string upd_expression(int i) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_expression__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_expression(int i, string value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_expression__SWIG_0(swigCPtr, i, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_expression(string value) {
    int ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_append_expression(swigCPtr, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_expression(string initValue) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_constructProperty_expression(swigCPtr, initValue);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string get_expression() {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_get_expression__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_std__string upd_expression() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_upd_expression__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_expression(string value) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_set_expression__SWIG_1(swigCPtr, value);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ExpressionBasedPointToPointForce() : this(CSharpWrapOpenSimPINVOKE.new_ExpressionBasedPointToPointForce__SWIG_0(), true) {
  }

  public unsafe ExpressionBasedPointToPointForce(string body1Name, Vec3 point1, string body2Name, Vec3 point2, string expression) : this(CSharpWrapOpenSimPINVOKE.new_ExpressionBasedPointToPointForce__SWIG_1(body1Name, Vec3.getCPtr(point1), body2Name, Vec3.getCPtr(point2), expression), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setBody1Name(string body1Name) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_setBody1Name(swigCPtr, body1Name);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setBody2Name(string body2Name) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_setBody2Name(swigCPtr, body2Name);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string getBody1Name() {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getBody1Name(swigCPtr);
    return ret;
  }

  public unsafe string getBody2Name() {
    string ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getBody2Name(swigCPtr);
    return ret;
  }

  public unsafe void setPoint1(Vec3 aPosition) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_setPoint1(swigCPtr, Vec3.getCPtr(aPosition));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vec3 getPoint1() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getPoint1(swigCPtr), false);
    return ret;
  }

  public unsafe void setPoint2(Vec3 aPosition) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_setPoint2(swigCPtr, Vec3.getCPtr(aPosition));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vec3 getPoint2() {
    Vec3 ret = new Vec3(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getPoint2(swigCPtr), false);
    return ret;
  }

  public unsafe void setExpression(string expression) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_setExpression(swigCPtr, expression);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double getForceMagnitude(State state) {
    double ret = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getForceMagnitude(swigCPtr, State.getCPtr(state));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void computeForce(State state, VectorOfSpatialVec bodyForces, Vector generalizedForces) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_computeForce(swigCPtr, State.getCPtr(state), VectorOfSpatialVec.getCPtr(bodyForces), Vector.getCPtr(generalizedForces));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ArrayStr getRecordLabels() {
    ArrayStr ret = new ArrayStr(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getRecordLabels(swigCPtr), true);
    return ret;
  }

  public unsafe ArrayDouble getRecordValues(State state) {
    ArrayDouble ret = new ArrayDouble(CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getRecordValues(swigCPtr, State.getCPtr(state)), true);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe VisibleObject getDisplayer() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_getDisplayer(swigCPtr);
    VisibleObject ret = (cPtr == IntPtr.Zero) ? null : new VisibleObject(cPtr, false);
    return ret;
  }

  public unsafe void updateDisplayer(State s) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_updateDisplayer(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void updateGeometry(State s) {
    CSharpWrapOpenSimPINVOKE.ExpressionBasedPointToPointForce_updateGeometry(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
