/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class ForwardTool : AbstractTool {
  private HandleRef swigCPtr;

  internal ForwardTool(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.ForwardTool_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ForwardTool obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ForwardTool() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_ForwardTool(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static ForwardTool safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.ForwardTool_safeDownCast(OpenSimObject.getCPtr(obj));
    ForwardTool ret = (cPtr == IntPtr.Zero) ? null : new ForwardTool(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.ForwardTool_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.ForwardTool_clone(swigCPtr);
    ForwardTool ret = (cPtr == IntPtr.Zero) ? null : new ForwardTool(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.ForwardTool_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe ForwardTool() : this(CSharpWrapOpenSimPINVOKE.new_ForwardTool__SWIG_0(), true) {
  }

  public unsafe ForwardTool(string aFileName, bool aUpdateFromXMLNode, bool aLoadModel) : this(CSharpWrapOpenSimPINVOKE.new_ForwardTool__SWIG_1(aFileName, aUpdateFromXMLNode, aLoadModel), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ForwardTool(string aFileName, bool aUpdateFromXMLNode) : this(CSharpWrapOpenSimPINVOKE.new_ForwardTool__SWIG_2(aFileName, aUpdateFromXMLNode), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ForwardTool(string aFileName) : this(CSharpWrapOpenSimPINVOKE.new_ForwardTool__SWIG_3(aFileName), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ForwardTool(ForwardTool aObject) : this(CSharpWrapOpenSimPINVOKE.new_ForwardTool__SWIG_4(ForwardTool.getCPtr(aObject)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode, int versionNumber) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_updateFromXMLNode__SWIG_0(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode), versionNumber);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_updateFromXMLNode__SWIG_1(swigCPtr, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setManager(Manager m) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_setManager(swigCPtr, Manager.getCPtr(m));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Manager getManager() {
    Manager ret = new Manager(CSharpWrapOpenSimPINVOKE.ForwardTool_getManager(swigCPtr), false);
    return ret;
  }

  public unsafe string getStatesFileName() {
    string ret = CSharpWrapOpenSimPINVOKE.ForwardTool_getStatesFileName(swigCPtr);
    return ret;
  }

  public unsafe void setStatesFileName(string aFileName) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_setStatesFileName(swigCPtr, aFileName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool getUseSpecifiedDt() {
    bool ret = CSharpWrapOpenSimPINVOKE.ForwardTool_getUseSpecifiedDt(swigCPtr);
    return ret;
  }

  public unsafe void setUseSpecifiedDt(bool aUseSpecifiedDt) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_setUseSpecifiedDt(swigCPtr, aUseSpecifiedDt);
  }

  public unsafe void setPrintResultFiles(bool aToWrite) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_setPrintResultFiles(swigCPtr, aToWrite);
  }

  public unsafe bool run() {
    bool ret = CSharpWrapOpenSimPINVOKE.ForwardTool_run(swigCPtr);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void printResults() {
    CSharpWrapOpenSimPINVOKE.ForwardTool_printResults(swigCPtr);
  }

  public unsafe static double Step(double t, double t0, double t1) {
    double ret = CSharpWrapOpenSimPINVOKE.ForwardTool_Step(t, t0, t1);
    return ret;
  }

  public unsafe static double SigmaUp(double tau, double to, double t) {
    double ret = CSharpWrapOpenSimPINVOKE.ForwardTool_SigmaUp(tau, to, t);
    return ret;
  }

  public unsafe static double SigmaDn(double tau, double to, double t) {
    double ret = CSharpWrapOpenSimPINVOKE.ForwardTool_SigmaDn(tau, to, t);
    return ret;
  }

  public unsafe void loadStatesStorage(SWIGTYPE_p_std__string statesFileName, SWIGTYPE_p_p_OpenSim__Storage rYStore) {
    CSharpWrapOpenSimPINVOKE.ForwardTool_loadStatesStorage(swigCPtr, SWIGTYPE_p_std__string.getCPtr(statesFileName), SWIGTYPE_p_p_OpenSim__Storage.getCPtr(rYStore));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string getParsingLog() {
    string ret = CSharpWrapOpenSimPINVOKE.ForwardTool_getParsingLog(swigCPtr);
    return ret;
  }

}

}
