/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class InverseDynamicsSolver : Solver {
  private HandleRef swigCPtr;

  internal InverseDynamicsSolver(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(InverseDynamicsSolver obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~InverseDynamicsSolver() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_InverseDynamicsSolver(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static InverseDynamicsSolver safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_safeDownCast(OpenSimObject.getCPtr(obj));
    InverseDynamicsSolver ret = (cPtr == IntPtr.Zero) ? null : new InverseDynamicsSolver(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_clone(swigCPtr);
    InverseDynamicsSolver ret = (cPtr == IntPtr.Zero) ? null : new InverseDynamicsSolver(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe InverseDynamicsSolver(Model model) : this(CSharpWrapOpenSimPINVOKE.new_InverseDynamicsSolver(Model.getCPtr(model)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Vector solve(State s, Vector udot) {
    Vector ret = new Vector(CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_solve__SWIG_0(swigCPtr, State.getCPtr(s), Vector.getCPtr(udot)), true);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe Vector solve(State s) {
    Vector ret = new Vector(CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_solve__SWIG_1(swigCPtr, State.getCPtr(s)), true);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe Vector solve(State s, Vector udot, Vector appliedMobilityForces, VectorOfSpatialVec appliedBodyForces) {
    Vector ret = new Vector(CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_solve__SWIG_2(swigCPtr, State.getCPtr(s), Vector.getCPtr(udot), Vector.getCPtr(appliedMobilityForces), VectorOfSpatialVec.getCPtr(appliedBodyForces)), true);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe Vector solve(State s, FunctionSet Qs, double time) {
    Vector ret = new Vector(CSharpWrapOpenSimPINVOKE.InverseDynamicsSolver_solve__SWIG_3(swigCPtr, State.getCPtr(s), FunctionSet.getCPtr(Qs), time), true);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
