/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class Manager : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Manager(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Manager obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Manager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_Manager(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public unsafe Manager(Model arg0, SWIGTYPE_p_SimTK__Integrator arg1) : this(CSharpWrapOpenSimPINVOKE.new_Manager__SWIG_0(Model.getCPtr(arg0), SWIGTYPE_p_SimTK__Integrator.getCPtr(arg1)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Manager(Model aModel) : this(CSharpWrapOpenSimPINVOKE.new_Manager__SWIG_1(Model.getCPtr(aModel)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Manager() : this(CSharpWrapOpenSimPINVOKE.new_Manager__SWIG_2(), true) {
  }

  public unsafe void setSessionName(string name) {
    CSharpWrapOpenSimPINVOKE.Manager_setSessionName(swigCPtr, name);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setModel(Model aModel) {
    CSharpWrapOpenSimPINVOKE.Manager_setModel(swigCPtr, Model.getCPtr(aModel));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe string getSessionName() {
    string ret = CSharpWrapOpenSimPINVOKE.Manager_getSessionName(swigCPtr);
    return ret;
  }

  public unsafe string toString() {
    string ret = CSharpWrapOpenSimPINVOKE.Manager_toString(swigCPtr);
    return ret;
  }

  public unsafe void setPerformAnalyses(bool performAnalyses) {
    CSharpWrapOpenSimPINVOKE.Manager_setPerformAnalyses(swigCPtr, performAnalyses);
  }

  public unsafe void setWriteToStorage(bool writeToStorage) {
    CSharpWrapOpenSimPINVOKE.Manager_setWriteToStorage(swigCPtr, writeToStorage);
  }

  public unsafe SWIGTYPE_p_SimTK__Integrator getIntegrator() {
    SWIGTYPE_p_SimTK__Integrator ret = new SWIGTYPE_p_SimTK__Integrator(CSharpWrapOpenSimPINVOKE.Manager_getIntegrator(swigCPtr), false);
    return ret;
  }

  public unsafe void setIntegrator(SWIGTYPE_p_SimTK__Integrator arg0) {
    CSharpWrapOpenSimPINVOKE.Manager_setIntegrator(swigCPtr, SWIGTYPE_p_SimTK__Integrator.getCPtr(arg0));
  }

  public unsafe void setInitialTime(double aTI) {
    CSharpWrapOpenSimPINVOKE.Manager_setInitialTime(swigCPtr, aTI);
  }

  public unsafe double getInitialTime() {
    double ret = CSharpWrapOpenSimPINVOKE.Manager_getInitialTime(swigCPtr);
    return ret;
  }

  public unsafe void setFinalTime(double aTF) {
    CSharpWrapOpenSimPINVOKE.Manager_setFinalTime(swigCPtr, aTF);
  }

  public unsafe double getFinalTime() {
    double ret = CSharpWrapOpenSimPINVOKE.Manager_getFinalTime(swigCPtr);
    return ret;
  }

  public unsafe void setFirstDT(double aDT) {
    CSharpWrapOpenSimPINVOKE.Manager_setFirstDT(swigCPtr, aDT);
  }

  public unsafe double getFirstDT() {
    double ret = CSharpWrapOpenSimPINVOKE.Manager_getFirstDT(swigCPtr);
    return ret;
  }

  public unsafe void setUseSpecifiedDT(bool aTrueFalse) {
    CSharpWrapOpenSimPINVOKE.Manager_setUseSpecifiedDT(swigCPtr, aTrueFalse);
  }

  public unsafe bool getUseSpecifiedDT() {
    bool ret = CSharpWrapOpenSimPINVOKE.Manager_getUseSpecifiedDT(swigCPtr);
    return ret;
  }

  public unsafe void setUseConstantDT(bool aTrueFalse) {
    CSharpWrapOpenSimPINVOKE.Manager_setUseConstantDT(swigCPtr, aTrueFalse);
  }

  public unsafe bool getUseConstantDT() {
    bool ret = CSharpWrapOpenSimPINVOKE.Manager_getUseConstantDT(swigCPtr);
    return ret;
  }

  public unsafe ArrayDouble getDTArray() {
    ArrayDouble ret = new ArrayDouble(CSharpWrapOpenSimPINVOKE.Manager_getDTArray(swigCPtr), false);
    return ret;
  }

  public unsafe void setDTArray(int aN, SWIGTYPE_p_double aDT, double aTI) {
    CSharpWrapOpenSimPINVOKE.Manager_setDTArray__SWIG_0(swigCPtr, aN, SWIGTYPE_p_double.getCPtr(aDT), aTI);
  }

  public unsafe void setDTArray(int aN, SWIGTYPE_p_double aDT) {
    CSharpWrapOpenSimPINVOKE.Manager_setDTArray__SWIG_1(swigCPtr, aN, SWIGTYPE_p_double.getCPtr(aDT));
  }

  public unsafe double getDTArrayDT(int aStep) {
    double ret = CSharpWrapOpenSimPINVOKE.Manager_getDTArrayDT(swigCPtr, aStep);
    return ret;
  }

  public unsafe void printDTArray(string aFileName) {
    CSharpWrapOpenSimPINVOKE.Manager_printDTArray__SWIG_0(swigCPtr, aFileName);
  }

  public unsafe void printDTArray() {
    CSharpWrapOpenSimPINVOKE.Manager_printDTArray__SWIG_1(swigCPtr);
  }

  public unsafe ArrayDouble getTimeArray() {
    ArrayDouble ret = new ArrayDouble(CSharpWrapOpenSimPINVOKE.Manager_getTimeArray(swigCPtr), false);
    return ret;
  }

  public unsafe double getTimeArrayTime(int aStep) {
    double ret = CSharpWrapOpenSimPINVOKE.Manager_getTimeArrayTime(swigCPtr, aStep);
    return ret;
  }

  public unsafe int getTimeArrayStep(double aTime) {
    int ret = CSharpWrapOpenSimPINVOKE.Manager_getTimeArrayStep(swigCPtr, aTime);
    return ret;
  }

  public unsafe void printTimeArray(string aFileName) {
    CSharpWrapOpenSimPINVOKE.Manager_printTimeArray__SWIG_0(swigCPtr, aFileName);
  }

  public unsafe void printTimeArray() {
    CSharpWrapOpenSimPINVOKE.Manager_printTimeArray__SWIG_1(swigCPtr);
  }

  public unsafe void resetTimeAndDTArrays(double aTime) {
    CSharpWrapOpenSimPINVOKE.Manager_resetTimeAndDTArrays(swigCPtr, aTime);
  }

  public unsafe double getNextTimeArrayTime(double aTime) {
    double ret = CSharpWrapOpenSimPINVOKE.Manager_getNextTimeArrayTime(swigCPtr, aTime);
    return ret;
  }

  public unsafe void setSystem(SWIGTYPE_p_SimTK__System system) {
    CSharpWrapOpenSimPINVOKE.Manager_setSystem(swigCPtr, SWIGTYPE_p_SimTK__System.getCPtr(system));
  }

  public unsafe bool integrate(State s, double dtFirst) {
    bool ret = CSharpWrapOpenSimPINVOKE.Manager_integrate__SWIG_0(swigCPtr, State.getCPtr(s), dtFirst);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool integrate(State s) {
    bool ret = CSharpWrapOpenSimPINVOKE.Manager_integrate__SWIG_1(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool doIntegration(State s, int step, double dtFirst) {
    bool ret = CSharpWrapOpenSimPINVOKE.Manager_doIntegration(swigCPtr, State.getCPtr(s), step, dtFirst);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void initialize(State s, double dt) {
    CSharpWrapOpenSimPINVOKE.Manager_initialize(swigCPtr, State.getCPtr(s), dt);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void finalize(State s) {
    CSharpWrapOpenSimPINVOKE.Manager_finalize(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double getFixedStepSize(int tArrayStep) {
    double ret = CSharpWrapOpenSimPINVOKE.Manager_getFixedStepSize(swigCPtr, tArrayStep);
    return ret;
  }

  public unsafe bool hasStateStorage() {
    bool ret = CSharpWrapOpenSimPINVOKE.Manager_hasStateStorage(swigCPtr);
    return ret;
  }

  public unsafe void setStateStorage(SWIGTYPE_p_OpenSim__Storage aStorage) {
    CSharpWrapOpenSimPINVOKE.Manager_setStateStorage(swigCPtr, SWIGTYPE_p_OpenSim__Storage.getCPtr(aStorage));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SWIGTYPE_p_OpenSim__Storage getStateStorage() {
    SWIGTYPE_p_OpenSim__Storage ret = new SWIGTYPE_p_OpenSim__Storage(CSharpWrapOpenSimPINVOKE.Manager_getStateStorage(swigCPtr), false);
    return ret;
  }

  public unsafe void halt() {
    CSharpWrapOpenSimPINVOKE.Manager_halt(swigCPtr);
  }

  public unsafe void clearHalt() {
    CSharpWrapOpenSimPINVOKE.Manager_clearHalt(swigCPtr);
  }

  public unsafe bool checkHalt() {
    bool ret = CSharpWrapOpenSimPINVOKE.Manager_checkHalt(swigCPtr);
    return ret;
  }

}

}
