/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class Millard2012EquilibriumMuscle : Muscle {
  private HandleRef swigCPtr;

  internal Millard2012EquilibriumMuscle(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Millard2012EquilibriumMuscle obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Millard2012EquilibriumMuscle() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_Millard2012EquilibriumMuscle(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static Millard2012EquilibriumMuscle safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_safeDownCast(OpenSimObject.getCPtr(obj));
    Millard2012EquilibriumMuscle ret = (cPtr == IntPtr.Zero) ? null : new Millard2012EquilibriumMuscle(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_clone(swigCPtr);
    Millard2012EquilibriumMuscle ret = (cPtr == IntPtr.Zero) ? null : new Millard2012EquilibriumMuscle(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe void copyProperty_fiber_damping(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_fiber_damping(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_fiber_damping(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_fiber_damping__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_damping(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_fiber_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_fiber_damping(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_fiber_damping__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_fiber_damping(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_fiber_damping(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_fiber_damping(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_fiber_damping(swigCPtr, initValue);
  }

  public unsafe double get_fiber_damping() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_fiber_damping__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_damping() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_fiber_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_fiber_damping(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_fiber_damping__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_default_activation(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_default_activation(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_default_activation(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_default_activation__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_activation(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_default_activation__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_default_activation(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_default_activation__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_default_activation(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_default_activation(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_default_activation(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_default_activation(swigCPtr, initValue);
  }

  public unsafe double get_default_activation() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_default_activation__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_activation() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_default_activation__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_default_activation(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_default_activation__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_default_fiber_length(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_default_fiber_length(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_default_fiber_length(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_default_fiber_length__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_fiber_length(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_default_fiber_length__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_default_fiber_length(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_default_fiber_length__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_default_fiber_length(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_default_fiber_length(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_default_fiber_length(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_default_fiber_length(swigCPtr, initValue);
  }

  public unsafe double get_default_fiber_length() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_default_fiber_length__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_fiber_length() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_default_fiber_length__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_default_fiber_length(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_default_fiber_length__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_activation_time_constant(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_activation_time_constant(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_activation_time_constant(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_activation_time_constant__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_activation_time_constant(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_activation_time_constant__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_activation_time_constant(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_activation_time_constant__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_activation_time_constant(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_activation_time_constant(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_activation_time_constant(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_activation_time_constant(swigCPtr, initValue);
  }

  public unsafe double get_activation_time_constant() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_activation_time_constant__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_activation_time_constant() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_activation_time_constant__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_activation_time_constant(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_activation_time_constant__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_deactivation_time_constant(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_deactivation_time_constant(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_deactivation_time_constant(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_deactivation_time_constant__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_deactivation_time_constant(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_deactivation_time_constant__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_deactivation_time_constant(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_deactivation_time_constant__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_deactivation_time_constant(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_deactivation_time_constant(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_deactivation_time_constant(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_deactivation_time_constant(swigCPtr, initValue);
  }

  public unsafe double get_deactivation_time_constant() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_deactivation_time_constant__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_deactivation_time_constant() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_deactivation_time_constant__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_deactivation_time_constant(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_deactivation_time_constant__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_minimum_activation(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_minimum_activation(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_minimum_activation(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_minimum_activation__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_minimum_activation(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_minimum_activation__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_minimum_activation(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_minimum_activation__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_minimum_activation(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_minimum_activation(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_minimum_activation(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_minimum_activation(swigCPtr, initValue);
  }

  public unsafe double get_minimum_activation() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_minimum_activation__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_minimum_activation() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_minimum_activation__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_minimum_activation(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_minimum_activation__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_ActiveForceLengthCurve(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_ActiveForceLengthCurve(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ActiveForceLengthCurve get_ActiveForceLengthCurve(int i) {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_ActiveForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe ActiveForceLengthCurve upd_ActiveForceLengthCurve(int i) {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_ActiveForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_ActiveForceLengthCurve(int i, ActiveForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_ActiveForceLengthCurve__SWIG_0(swigCPtr, i, ActiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_ActiveForceLengthCurve(ActiveForceLengthCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_ActiveForceLengthCurve(swigCPtr, ActiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_ActiveForceLengthCurve(ActiveForceLengthCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_ActiveForceLengthCurve(swigCPtr, ActiveForceLengthCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ActiveForceLengthCurve get_ActiveForceLengthCurve() {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_ActiveForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe ActiveForceLengthCurve upd_ActiveForceLengthCurve() {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_ActiveForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_ActiveForceLengthCurve(ActiveForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_ActiveForceLengthCurve__SWIG_1(swigCPtr, ActiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_ForceVelocityCurve(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_ForceVelocityCurve(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ForceVelocityCurve get_ForceVelocityCurve(int i) {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_ForceVelocityCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe ForceVelocityCurve upd_ForceVelocityCurve(int i) {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_ForceVelocityCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_ForceVelocityCurve(int i, ForceVelocityCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_ForceVelocityCurve__SWIG_0(swigCPtr, i, ForceVelocityCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_ForceVelocityCurve(ForceVelocityCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_ForceVelocityCurve(swigCPtr, ForceVelocityCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_ForceVelocityCurve(ForceVelocityCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_ForceVelocityCurve(swigCPtr, ForceVelocityCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ForceVelocityCurve get_ForceVelocityCurve() {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_ForceVelocityCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe ForceVelocityCurve upd_ForceVelocityCurve() {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_ForceVelocityCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_ForceVelocityCurve(ForceVelocityCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_ForceVelocityCurve__SWIG_1(swigCPtr, ForceVelocityCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_FiberForceLengthCurve(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_FiberForceLengthCurve(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberForceLengthCurve get_FiberForceLengthCurve(int i) {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_FiberForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe FiberForceLengthCurve upd_FiberForceLengthCurve(int i) {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_FiberForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_FiberForceLengthCurve(int i, FiberForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_FiberForceLengthCurve__SWIG_0(swigCPtr, i, FiberForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_FiberForceLengthCurve(FiberForceLengthCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_FiberForceLengthCurve(swigCPtr, FiberForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_FiberForceLengthCurve(FiberForceLengthCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_FiberForceLengthCurve(swigCPtr, FiberForceLengthCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberForceLengthCurve get_FiberForceLengthCurve() {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_FiberForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe FiberForceLengthCurve upd_FiberForceLengthCurve() {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_FiberForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_FiberForceLengthCurve(FiberForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_FiberForceLengthCurve__SWIG_1(swigCPtr, FiberForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_TendonForceLengthCurve(Millard2012EquilibriumMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_copyProperty_TendonForceLengthCurve(swigCPtr, Millard2012EquilibriumMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe TendonForceLengthCurve get_TendonForceLengthCurve(int i) {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_TendonForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe TendonForceLengthCurve upd_TendonForceLengthCurve(int i) {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_TendonForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_TendonForceLengthCurve(int i, TendonForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_TendonForceLengthCurve__SWIG_0(swigCPtr, i, TendonForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_TendonForceLengthCurve(TendonForceLengthCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_append_TendonForceLengthCurve(swigCPtr, TendonForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_TendonForceLengthCurve(TendonForceLengthCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_constructProperty_TendonForceLengthCurve(swigCPtr, TendonForceLengthCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe TendonForceLengthCurve get_TendonForceLengthCurve() {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_get_TendonForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe TendonForceLengthCurve upd_TendonForceLengthCurve() {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_upd_TendonForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_TendonForceLengthCurve(TendonForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_set_TendonForceLengthCurve__SWIG_1(swigCPtr, TendonForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe Millard2012EquilibriumMuscle() : this(CSharpWrapOpenSimPINVOKE.new_Millard2012EquilibriumMuscle__SWIG_0(), true) {
  }

  public unsafe Millard2012EquilibriumMuscle(string aName, double aMaxIsometricForce, double aOptimalFiberLength, double aTendonSlackLength, double aPennationAngle) : this(CSharpWrapOpenSimPINVOKE.new_Millard2012EquilibriumMuscle__SWIG_1(aName, aMaxIsometricForce, aOptimalFiberLength, aTendonSlackLength, aPennationAngle), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool getUseFiberDamping() {
    bool ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getUseFiberDamping(swigCPtr);
    return ret;
  }

  public unsafe double getFiberDamping() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getFiberDamping(swigCPtr);
    return ret;
  }

  public unsafe double getDefaultActivation() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getDefaultActivation(swigCPtr);
    return ret;
  }

  public unsafe double getDefaultFiberLength() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getDefaultFiberLength(swigCPtr);
    return ret;
  }

  public unsafe double getActivationTimeConstant() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getActivationTimeConstant(swigCPtr);
    return ret;
  }

  public unsafe double getDeactivationTimeConstant() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getDeactivationTimeConstant(swigCPtr);
    return ret;
  }

  public unsafe double getMinimumActivation() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getMinimumActivation(swigCPtr);
    return ret;
  }

  public unsafe ActiveForceLengthCurve getActiveForceLengthCurve() {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getActiveForceLengthCurve(swigCPtr), false);
    return ret;
  }

  public unsafe ForceVelocityCurve getForceVelocityCurve() {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getForceVelocityCurve(swigCPtr), false);
    return ret;
  }

  public unsafe FiberForceLengthCurve getFiberForceLengthCurve() {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getFiberForceLengthCurve(swigCPtr), false);
    return ret;
  }

  public unsafe TendonForceLengthCurve getTendonForceLengthCurve() {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getTendonForceLengthCurve(swigCPtr), false);
    return ret;
  }

  public unsafe MuscleFixedWidthPennationModel getPennationModel() {
    MuscleFixedWidthPennationModel ret = new MuscleFixedWidthPennationModel(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getPennationModel(swigCPtr), false);
    return ret;
  }

  public unsafe double getMaximumPennationAngle() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getMaximumPennationAngle(swigCPtr);
    return ret;
  }

  public unsafe double getMinimumFiberLength() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getMinimumFiberLength(swigCPtr);
    return ret;
  }

  public unsafe double getMinimumFiberLengthAlongTendon() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getMinimumFiberLengthAlongTendon(swigCPtr);
    return ret;
  }

  public unsafe double getTendonForceMultiplier(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getTendonForceMultiplier(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getFiberStiffnessAlongTendon(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getFiberStiffnessAlongTendon(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getFiberVelocity(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getFiberVelocity(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getActivationDerivative(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getActivationDerivative(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe ArrayStr getStateVariableNames() {
    ArrayStr ret = new ArrayStr(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getStateVariableNames(swigCPtr), true);
    return ret;
  }

  public unsafe int getStateVariableSystemIndex(string stateVariableName) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_getStateVariableSystemIndex(swigCPtr, stateVariableName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setMuscleConfiguration(bool ignoreTendonCompliance, bool ignoreActivationDynamics, double dampingCoefficient) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setMuscleConfiguration(swigCPtr, ignoreTendonCompliance, ignoreActivationDynamics, dampingCoefficient);
  }

  public unsafe void setFiberDamping(double dampingCoefficient) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setFiberDamping(swigCPtr, dampingCoefficient);
  }

  public unsafe void setDefaultActivation(double activation) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setDefaultActivation(swigCPtr, activation);
  }

  public unsafe void setActivation(State s, double activation) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setActivation(swigCPtr, State.getCPtr(s), activation);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setDefaultFiberLength(double fiberLength) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setDefaultFiberLength(swigCPtr, fiberLength);
  }

  public unsafe void setActivationTimeConstant(double activationTimeConstant) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setActivationTimeConstant(swigCPtr, activationTimeConstant);
  }

  public unsafe void setDeactivationTimeConstant(double deactivationTimeConstant) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setDeactivationTimeConstant(swigCPtr, deactivationTimeConstant);
  }

  public unsafe void setMinimumActivation(double minimumActivation) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setMinimumActivation(swigCPtr, minimumActivation);
  }

  public unsafe void setActiveForceLengthCurve(ActiveForceLengthCurve aActiveForceLengthCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setActiveForceLengthCurve(swigCPtr, ActiveForceLengthCurve.getCPtr(aActiveForceLengthCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setForceVelocityCurve(ForceVelocityCurve aForceVelocityCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setForceVelocityCurve(swigCPtr, ForceVelocityCurve.getCPtr(aForceVelocityCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setFiberForceLengthCurve(FiberForceLengthCurve aFiberForceLengthCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setFiberForceLengthCurve(swigCPtr, FiberForceLengthCurve.getCPtr(aFiberForceLengthCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setTendonForceLengthCurve(TendonForceLengthCurve aTendonForceLengthCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setTendonForceLengthCurve(swigCPtr, TendonForceLengthCurve.getCPtr(aTendonForceLengthCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setFiberLength(State s, double fiberLength) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_setFiberLength(swigCPtr, State.getCPtr(s), fiberLength);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double computeActuation(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_computeActuation(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void computeInitialFiberEquilibrium(State s) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_computeInitialFiberEquilibrium(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void computeFiberEquilibriumAtZeroVelocity(State s) {
    CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_computeFiberEquilibriumAtZeroVelocity(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double calcActiveFiberForceAlongTendon(double activation, double fiberLength, double fiberVelocity) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_calcActiveFiberForceAlongTendon(swigCPtr, activation, fiberLength, fiberVelocity);
    return ret;
  }

  public unsafe Vec4 calcFiberStateGivenBoundaryCond(double lengthMT, double velocityMT, double tendonForce, double dTendonForceDT) {
    Vec4 ret = new Vec4(CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_calcFiberStateGivenBoundaryCond(swigCPtr, lengthMT, velocityMT, tendonForce, dTendonForceDT), true);
    return ret;
  }

  public unsafe double calcInextensibleTendonActiveFiberForce(State s, double aActivation) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012EquilibriumMuscle_calcInextensibleTendonActiveFiberForce(swigCPtr, State.getCPtr(s), aActivation);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
