/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class Millard2012AccelerationMuscle : Muscle {
  private HandleRef swigCPtr;

  internal Millard2012AccelerationMuscle(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Millard2012AccelerationMuscle obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Millard2012AccelerationMuscle() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_Millard2012AccelerationMuscle(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static Millard2012AccelerationMuscle safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_safeDownCast(OpenSimObject.getCPtr(obj));
    Millard2012AccelerationMuscle ret = (cPtr == IntPtr.Zero) ? null : new Millard2012AccelerationMuscle(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_clone(swigCPtr);
    Millard2012AccelerationMuscle ret = (cPtr == IntPtr.Zero) ? null : new Millard2012AccelerationMuscle(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe void copyProperty_default_activation(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_default_activation(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_default_activation(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_default_activation__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_activation(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_default_activation__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_default_activation(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_default_activation__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_default_activation(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_default_activation(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_default_activation(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_default_activation(swigCPtr, initValue);
  }

  public unsafe double get_default_activation() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_default_activation__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_activation() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_default_activation__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_default_activation(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_default_activation__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_default_fiber_length(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_default_fiber_length(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_default_fiber_length(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_default_fiber_length__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_fiber_length(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_default_fiber_length__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_default_fiber_length(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_default_fiber_length__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_default_fiber_length(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_default_fiber_length(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_default_fiber_length(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_default_fiber_length(swigCPtr, initValue);
  }

  public unsafe double get_default_fiber_length() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_default_fiber_length__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_fiber_length() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_default_fiber_length__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_default_fiber_length(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_default_fiber_length__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_default_fiber_velocity(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_default_fiber_velocity(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_default_fiber_velocity(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_default_fiber_velocity__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_fiber_velocity(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_default_fiber_velocity__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_default_fiber_velocity(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_default_fiber_velocity__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_default_fiber_velocity(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_default_fiber_velocity(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_default_fiber_velocity(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_default_fiber_velocity(swigCPtr, initValue);
  }

  public unsafe double get_default_fiber_velocity() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_default_fiber_velocity__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_default_fiber_velocity() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_default_fiber_velocity__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_default_fiber_velocity(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_default_fiber_velocity__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_MuscleFirstOrderActivationDynamicModel(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_MuscleFirstOrderActivationDynamicModel(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe MuscleFirstOrderActivationDynamicModel get_MuscleFirstOrderActivationDynamicModel(int i) {
    MuscleFirstOrderActivationDynamicModel ret = new MuscleFirstOrderActivationDynamicModel(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_MuscleFirstOrderActivationDynamicModel__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe MuscleFirstOrderActivationDynamicModel upd_MuscleFirstOrderActivationDynamicModel(int i) {
    MuscleFirstOrderActivationDynamicModel ret = new MuscleFirstOrderActivationDynamicModel(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_MuscleFirstOrderActivationDynamicModel__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_MuscleFirstOrderActivationDynamicModel(int i, MuscleFirstOrderActivationDynamicModel value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_MuscleFirstOrderActivationDynamicModel__SWIG_0(swigCPtr, i, MuscleFirstOrderActivationDynamicModel.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_MuscleFirstOrderActivationDynamicModel(MuscleFirstOrderActivationDynamicModel value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_MuscleFirstOrderActivationDynamicModel(swigCPtr, MuscleFirstOrderActivationDynamicModel.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_MuscleFirstOrderActivationDynamicModel(MuscleFirstOrderActivationDynamicModel initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_MuscleFirstOrderActivationDynamicModel(swigCPtr, MuscleFirstOrderActivationDynamicModel.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe MuscleFirstOrderActivationDynamicModel get_MuscleFirstOrderActivationDynamicModel() {
    MuscleFirstOrderActivationDynamicModel ret = new MuscleFirstOrderActivationDynamicModel(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_MuscleFirstOrderActivationDynamicModel__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe MuscleFirstOrderActivationDynamicModel upd_MuscleFirstOrderActivationDynamicModel() {
    MuscleFirstOrderActivationDynamicModel ret = new MuscleFirstOrderActivationDynamicModel(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_MuscleFirstOrderActivationDynamicModel__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_MuscleFirstOrderActivationDynamicModel(MuscleFirstOrderActivationDynamicModel value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_MuscleFirstOrderActivationDynamicModel__SWIG_1(swigCPtr, MuscleFirstOrderActivationDynamicModel.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_ActiveForceLengthCurve(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_ActiveForceLengthCurve(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ActiveForceLengthCurve get_ActiveForceLengthCurve(int i) {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_ActiveForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe ActiveForceLengthCurve upd_ActiveForceLengthCurve(int i) {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_ActiveForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_ActiveForceLengthCurve(int i, ActiveForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_ActiveForceLengthCurve__SWIG_0(swigCPtr, i, ActiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_ActiveForceLengthCurve(ActiveForceLengthCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_ActiveForceLengthCurve(swigCPtr, ActiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_ActiveForceLengthCurve(ActiveForceLengthCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_ActiveForceLengthCurve(swigCPtr, ActiveForceLengthCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ActiveForceLengthCurve get_ActiveForceLengthCurve() {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_ActiveForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe ActiveForceLengthCurve upd_ActiveForceLengthCurve() {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_ActiveForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_ActiveForceLengthCurve(ActiveForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_ActiveForceLengthCurve__SWIG_1(swigCPtr, ActiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_ForceVelocityCurve(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_ForceVelocityCurve(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ForceVelocityCurve get_ForceVelocityCurve(int i) {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_ForceVelocityCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe ForceVelocityCurve upd_ForceVelocityCurve(int i) {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_ForceVelocityCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_ForceVelocityCurve(int i, ForceVelocityCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_ForceVelocityCurve__SWIG_0(swigCPtr, i, ForceVelocityCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_ForceVelocityCurve(ForceVelocityCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_ForceVelocityCurve(swigCPtr, ForceVelocityCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_ForceVelocityCurve(ForceVelocityCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_ForceVelocityCurve(swigCPtr, ForceVelocityCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ForceVelocityCurve get_ForceVelocityCurve() {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_ForceVelocityCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe ForceVelocityCurve upd_ForceVelocityCurve() {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_ForceVelocityCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_ForceVelocityCurve(ForceVelocityCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_ForceVelocityCurve__SWIG_1(swigCPtr, ForceVelocityCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_FiberForceLengthCurve(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_FiberForceLengthCurve(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberForceLengthCurve get_FiberForceLengthCurve(int i) {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_FiberForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe FiberForceLengthCurve upd_FiberForceLengthCurve(int i) {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_FiberForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_FiberForceLengthCurve(int i, FiberForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_FiberForceLengthCurve__SWIG_0(swigCPtr, i, FiberForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_FiberForceLengthCurve(FiberForceLengthCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_FiberForceLengthCurve(swigCPtr, FiberForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_FiberForceLengthCurve(FiberForceLengthCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_FiberForceLengthCurve(swigCPtr, FiberForceLengthCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberForceLengthCurve get_FiberForceLengthCurve() {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_FiberForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe FiberForceLengthCurve upd_FiberForceLengthCurve() {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_FiberForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_FiberForceLengthCurve(FiberForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_FiberForceLengthCurve__SWIG_1(swigCPtr, FiberForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_TendonForceLengthCurve(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_TendonForceLengthCurve(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe TendonForceLengthCurve get_TendonForceLengthCurve(int i) {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_TendonForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe TendonForceLengthCurve upd_TendonForceLengthCurve(int i) {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_TendonForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_TendonForceLengthCurve(int i, TendonForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_TendonForceLengthCurve__SWIG_0(swigCPtr, i, TendonForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_TendonForceLengthCurve(TendonForceLengthCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_TendonForceLengthCurve(swigCPtr, TendonForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_TendonForceLengthCurve(TendonForceLengthCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_TendonForceLengthCurve(swigCPtr, TendonForceLengthCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe TendonForceLengthCurve get_TendonForceLengthCurve() {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_TendonForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe TendonForceLengthCurve upd_TendonForceLengthCurve() {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_TendonForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_TendonForceLengthCurve(TendonForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_TendonForceLengthCurve__SWIG_1(swigCPtr, TendonForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_FiberCompressiveForceLengthCurve(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_FiberCompressiveForceLengthCurve(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberCompressiveForceLengthCurve get_FiberCompressiveForceLengthCurve(int i) {
    FiberCompressiveForceLengthCurve ret = new FiberCompressiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_FiberCompressiveForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe FiberCompressiveForceLengthCurve upd_FiberCompressiveForceLengthCurve(int i) {
    FiberCompressiveForceLengthCurve ret = new FiberCompressiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_FiberCompressiveForceLengthCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_FiberCompressiveForceLengthCurve(int i, FiberCompressiveForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_FiberCompressiveForceLengthCurve__SWIG_0(swigCPtr, i, FiberCompressiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_FiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_FiberCompressiveForceLengthCurve(swigCPtr, FiberCompressiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_FiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_FiberCompressiveForceLengthCurve(swigCPtr, FiberCompressiveForceLengthCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberCompressiveForceLengthCurve get_FiberCompressiveForceLengthCurve() {
    FiberCompressiveForceLengthCurve ret = new FiberCompressiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_FiberCompressiveForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe FiberCompressiveForceLengthCurve upd_FiberCompressiveForceLengthCurve() {
    FiberCompressiveForceLengthCurve ret = new FiberCompressiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_FiberCompressiveForceLengthCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_FiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_FiberCompressiveForceLengthCurve__SWIG_1(swigCPtr, FiberCompressiveForceLengthCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_FiberCompressiveForceCosPennationCurve(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_FiberCompressiveForceCosPennationCurve(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberCompressiveForceCosPennationCurve get_FiberCompressiveForceCosPennationCurve(int i) {
    FiberCompressiveForceCosPennationCurve ret = new FiberCompressiveForceCosPennationCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_FiberCompressiveForceCosPennationCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe FiberCompressiveForceCosPennationCurve upd_FiberCompressiveForceCosPennationCurve(int i) {
    FiberCompressiveForceCosPennationCurve ret = new FiberCompressiveForceCosPennationCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_FiberCompressiveForceCosPennationCurve__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_FiberCompressiveForceCosPennationCurve(int i, FiberCompressiveForceCosPennationCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_FiberCompressiveForceCosPennationCurve__SWIG_0(swigCPtr, i, FiberCompressiveForceCosPennationCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int append_FiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_FiberCompressiveForceCosPennationCurve(swigCPtr, FiberCompressiveForceCosPennationCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void constructProperty_FiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_FiberCompressiveForceCosPennationCurve(swigCPtr, FiberCompressiveForceCosPennationCurve.getCPtr(initValue));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe FiberCompressiveForceCosPennationCurve get_FiberCompressiveForceCosPennationCurve() {
    FiberCompressiveForceCosPennationCurve ret = new FiberCompressiveForceCosPennationCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_FiberCompressiveForceCosPennationCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe FiberCompressiveForceCosPennationCurve upd_FiberCompressiveForceCosPennationCurve() {
    FiberCompressiveForceCosPennationCurve ret = new FiberCompressiveForceCosPennationCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_FiberCompressiveForceCosPennationCurve__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_FiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_FiberCompressiveForceCosPennationCurve__SWIG_1(swigCPtr, FiberCompressiveForceCosPennationCurve.getCPtr(value));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyProperty_fiber_damping(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_fiber_damping(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_fiber_damping(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_damping__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_damping(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_fiber_damping(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_damping__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_fiber_damping(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_fiber_damping(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_fiber_damping(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_fiber_damping(swigCPtr, initValue);
  }

  public unsafe double get_fiber_damping() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_damping__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_damping() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_fiber_damping(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_damping__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_fiber_force_length_damping(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_fiber_force_length_damping(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_fiber_force_length_damping(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_force_length_damping__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_force_length_damping(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_force_length_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_fiber_force_length_damping(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_force_length_damping__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_fiber_force_length_damping(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_fiber_force_length_damping(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_fiber_force_length_damping(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_fiber_force_length_damping(swigCPtr, initValue);
  }

  public unsafe double get_fiber_force_length_damping() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_force_length_damping__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_force_length_damping() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_force_length_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_fiber_force_length_damping(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_force_length_damping__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_fiber_compressive_force_length_damping(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_fiber_compressive_force_length_damping(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_fiber_compressive_force_length_damping(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_compressive_force_length_damping__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_compressive_force_length_damping(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_compressive_force_length_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_fiber_compressive_force_length_damping(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_compressive_force_length_damping__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_fiber_compressive_force_length_damping(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_fiber_compressive_force_length_damping(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_fiber_compressive_force_length_damping(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_fiber_compressive_force_length_damping(swigCPtr, initValue);
  }

  public unsafe double get_fiber_compressive_force_length_damping() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_compressive_force_length_damping__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_compressive_force_length_damping() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_compressive_force_length_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_fiber_compressive_force_length_damping(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_compressive_force_length_damping__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_fiber_compressive_force_cos_pennation_damping(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_fiber_compressive_force_cos_pennation_damping(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_fiber_compressive_force_cos_pennation_damping(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_compressive_force_cos_pennation_damping__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_compressive_force_cos_pennation_damping(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_compressive_force_cos_pennation_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_fiber_compressive_force_cos_pennation_damping(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_compressive_force_cos_pennation_damping__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_fiber_compressive_force_cos_pennation_damping(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_fiber_compressive_force_cos_pennation_damping(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_fiber_compressive_force_cos_pennation_damping(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_fiber_compressive_force_cos_pennation_damping(swigCPtr, initValue);
  }

  public unsafe double get_fiber_compressive_force_cos_pennation_damping() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_fiber_compressive_force_cos_pennation_damping__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_fiber_compressive_force_cos_pennation_damping() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_fiber_compressive_force_cos_pennation_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_fiber_compressive_force_cos_pennation_damping(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_fiber_compressive_force_cos_pennation_damping__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_tendon_force_length_damping(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_tendon_force_length_damping(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_tendon_force_length_damping(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_tendon_force_length_damping__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_tendon_force_length_damping(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_tendon_force_length_damping__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_tendon_force_length_damping(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_tendon_force_length_damping__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_tendon_force_length_damping(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_tendon_force_length_damping(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_tendon_force_length_damping(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_tendon_force_length_damping(swigCPtr, initValue);
  }

  public unsafe double get_tendon_force_length_damping() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_tendon_force_length_damping__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_tendon_force_length_damping() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_tendon_force_length_damping__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_tendon_force_length_damping(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_tendon_force_length_damping__SWIG_1(swigCPtr, value);
  }

  public unsafe void copyProperty_mass(Millard2012AccelerationMuscle source) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_copyProperty_mass(swigCPtr, Millard2012AccelerationMuscle.getCPtr(source));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double get_mass(int i) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_mass__SWIG_0(swigCPtr, i);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_mass(int i) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_mass__SWIG_0(swigCPtr, i), false);
    return ret;
  }

  public unsafe void set_mass(int i, double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_mass__SWIG_0(swigCPtr, i, value);
  }

  public unsafe int append_mass(double value) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_append_mass(swigCPtr, value);
    return ret;
  }

  public unsafe void constructProperty_mass(double initValue) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_constructProperty_mass(swigCPtr, initValue);
  }

  public unsafe double get_mass() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_get_mass__SWIG_1(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_double upd_mass() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_upd_mass__SWIG_1(swigCPtr), false);
    return ret;
  }

  public unsafe void set_mass(double value) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_set_mass__SWIG_1(swigCPtr, value);
  }

  public unsafe Millard2012AccelerationMuscle() : this(CSharpWrapOpenSimPINVOKE.new_Millard2012AccelerationMuscle__SWIG_0(), true) {
  }

  public unsafe Millard2012AccelerationMuscle(string aName, double aMaxIsometricForce, double aOptimalFiberLength, double aTendonSlackLength, double aPennationAngle) : this(CSharpWrapOpenSimPINVOKE.new_Millard2012AccelerationMuscle__SWIG_1(aName, aMaxIsometricForce, aOptimalFiberLength, aTendonSlackLength, aPennationAngle), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double getFiberCompressiveForceLengthMultiplier(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberCompressiveForceLengthMultiplier(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getFiberCompressiveForceCosPennationMultiplier(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberCompressiveForceCosPennationMultiplier(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getTendonForceMultiplier(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getTendonForceMultiplier(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getMass() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getMass(swigCPtr);
    return ret;
  }

  public unsafe MuscleFirstOrderActivationDynamicModel getActivationModel() {
    MuscleFirstOrderActivationDynamicModel ret = new MuscleFirstOrderActivationDynamicModel(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getActivationModel(swigCPtr), false);
    return ret;
  }

  public unsafe MuscleFixedWidthPennationModel getPennationModel() {
    MuscleFixedWidthPennationModel ret = new MuscleFixedWidthPennationModel(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getPennationModel(swigCPtr), false);
    return ret;
  }

  public unsafe ActiveForceLengthCurve getActiveForceLengthCurve() {
    ActiveForceLengthCurve ret = new ActiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getActiveForceLengthCurve(swigCPtr), false);
    return ret;
  }

  public unsafe ForceVelocityCurve getForceVelocityCurve() {
    ForceVelocityCurve ret = new ForceVelocityCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getForceVelocityCurve(swigCPtr), false);
    return ret;
  }

  public unsafe FiberForceLengthCurve getFiberForceLengthCurve() {
    FiberForceLengthCurve ret = new FiberForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberForceLengthCurve(swigCPtr), false);
    return ret;
  }

  public unsafe TendonForceLengthCurve getTendonForceLengthCurve() {
    TendonForceLengthCurve ret = new TendonForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getTendonForceLengthCurve(swigCPtr), false);
    return ret;
  }

  public unsafe FiberCompressiveForceLengthCurve getFiberCompressiveForceLengthCurve() {
    FiberCompressiveForceLengthCurve ret = new FiberCompressiveForceLengthCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberCompressiveForceLengthCurve(swigCPtr), false);
    return ret;
  }

  public unsafe FiberCompressiveForceCosPennationCurve getFiberCompressiveForceCosPennationCurve() {
    FiberCompressiveForceCosPennationCurve ret = new FiberCompressiveForceCosPennationCurve(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberCompressiveForceCosPennationCurve(swigCPtr), false);
    return ret;
  }

  public unsafe double getFiberStiffnessAlongTendon(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberStiffnessAlongTendon(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setActivationModel(MuscleFirstOrderActivationDynamicModel aActivationMdl) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setActivationModel(swigCPtr, MuscleFirstOrderActivationDynamicModel.getCPtr(aActivationMdl));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setActiveForceLengthCurve(ActiveForceLengthCurve aActiveForceLengthCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setActiveForceLengthCurve(swigCPtr, ActiveForceLengthCurve.getCPtr(aActiveForceLengthCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setForceVelocityCurve(ForceVelocityCurve aForceVelocityCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setForceVelocityCurve(swigCPtr, ForceVelocityCurve.getCPtr(aForceVelocityCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setFiberForceLengthCurve(FiberForceLengthCurve aFiberForceLengthCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setFiberForceLengthCurve(swigCPtr, FiberForceLengthCurve.getCPtr(aFiberForceLengthCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setTendonForceLengthCurve(TendonForceLengthCurve aTendonForceLengthCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setTendonForceLengthCurve(swigCPtr, TendonForceLengthCurve.getCPtr(aTendonForceLengthCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setFiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve aFiberCompressiveForceLengthCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setFiberCompressiveForceLengthCurve(swigCPtr, FiberCompressiveForceLengthCurve.getCPtr(aFiberCompressiveForceLengthCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setFiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve aFiberCompressiveForceCosPennationCurve) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setFiberCompressiveForceCosPennationCurve(swigCPtr, FiberCompressiveForceCosPennationCurve.getCPtr(aFiberCompressiveForceCosPennationCurve));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setMass(double mass) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setMass(swigCPtr, mass);
  }

  public unsafe double getDefaultActivation() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getDefaultActivation(swigCPtr);
    return ret;
  }

  public unsafe double getDefaultFiberLength() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getDefaultFiberLength(swigCPtr);
    return ret;
  }

  public unsafe double getDefaultFiberVelocity() {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getDefaultFiberVelocity(swigCPtr);
    return ret;
  }

  public unsafe double getActivationRate(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getActivationRate(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getFiberVelocity(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberVelocity(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getFiberAcceleration(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getFiberAcceleration(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setDefaultActivation(double activation) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setDefaultActivation(swigCPtr, activation);
  }

  public unsafe void setDefaultFiberLength(double fiberLength) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setDefaultFiberLength(swigCPtr, fiberLength);
  }

  public unsafe void setDefaultFiberVelocity(double fiberVelocity) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setDefaultFiberVelocity(swigCPtr, fiberVelocity);
  }

  public unsafe void setActivation(State s, double activation) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setActivation(swigCPtr, State.getCPtr(s), activation);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setFiberLength(State s, double fiberLength) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setFiberLength(swigCPtr, State.getCPtr(s), fiberLength);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setFiberVelocity(State s, double fiberVelocity) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_setFiberVelocity(swigCPtr, State.getCPtr(s), fiberVelocity);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ArrayStr getStateVariableNames() {
    ArrayStr ret = new ArrayStr(CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getStateVariableNames(swigCPtr), true);
    return ret;
  }

  public unsafe int getStateVariableSystemIndex(string stateVariableName) {
    int ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_getStateVariableSystemIndex(swigCPtr, stateVariableName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double computeActuation(State s) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_computeActuation(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void computeInitialFiberEquilibrium(State s) {
    CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_computeInitialFiberEquilibrium(swigCPtr, State.getCPtr(s));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double calcInextensibleTendonActiveFiberForce(State s, double aActivation) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_calcInextensibleTendonActiveFiberForce(swigCPtr, State.getCPtr(s), aActivation);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double calcActiveFiberForceAlongTendon(double activation, double fiberLength, double fiberVelocity) {
    double ret = CSharpWrapOpenSimPINVOKE.Millard2012AccelerationMuscle_calcActiveFiberForceAlongTendon(swigCPtr, activation, fiberLength, fiberVelocity);
    return ret;
  }

}

}
