/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class OpenSimContext : OpenSimObject {
  private HandleRef swigCPtr;

  internal OpenSimContext(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.OpenSimContext_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OpenSimContext obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpenSimContext() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_OpenSimContext(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static OpenSimContext safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.OpenSimContext_safeDownCast(OpenSimObject.getCPtr(obj));
    OpenSimContext ret = (cPtr == IntPtr.Zero) ? null : new OpenSimContext(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.OpenSimContext_clone(swigCPtr);
    OpenSimContext ret = (cPtr == IntPtr.Zero) ? null : new OpenSimContext(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe OpenSimContext(State s, Model model) : this(CSharpWrapOpenSimPINVOKE.new_OpenSimContext(State.getCPtr(s), Model.getCPtr(model)), true) {
  }

  public unsafe void setState(State s) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setState(swigCPtr, State.getCPtr(s));
  }

  public unsafe void setModel(Model m) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setModel(swigCPtr, Model.getCPtr(m));
  }

  public unsafe void setStates(ArrayDouble states) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setStates__SWIG_0(swigCPtr, ArrayDouble.getCPtr(states));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setStates(SWIGTYPE_p_double statesBuffer) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setStates__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(statesBuffer));
  }

  public unsafe void computeConstrainedCoordinates(SWIGTYPE_p_double statesBuffer) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_computeConstrainedCoordinates(swigCPtr, SWIGTYPE_p_double.getCPtr(statesBuffer));
  }

  public unsafe void getStates(SWIGTYPE_p_double statesBuffer) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_getStates__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(statesBuffer));
  }

  public unsafe void getStates(ArrayDouble rStates) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_getStates__SWIG_1(swigCPtr, ArrayDouble.getCPtr(rStates));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe State getCurrentStateRef() {
    State ret = new State(CSharpWrapOpenSimPINVOKE.OpenSimContext_getCurrentStateRef(swigCPtr), false);
    return ret;
  }

  public unsafe State getCurrentStateCopy() {
    State ret = new State(CSharpWrapOpenSimPINVOKE.OpenSimContext_getCurrentStateCopy(swigCPtr), true);
    return ret;
  }

  public unsafe void recreateSystemAfterSystemExistsKeepStage() {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_recreateSystemAfterSystemExistsKeepStage(swigCPtr);
  }

  public unsafe void recreateSystemAfterSystemExists() {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_recreateSystemAfterSystemExists(swigCPtr);
  }

  public unsafe void resetStateToDefault() {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_resetStateToDefault(swigCPtr);
  }

  public unsafe void transformPosition(Body body, SWIGTYPE_p_double offset, SWIGTYPE_p_double gOffset) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_transformPosition(swigCPtr, Body.getCPtr(body), SWIGTYPE_p_double.getCPtr(offset), SWIGTYPE_p_double.getCPtr(gOffset));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SWIGTYPE_p_Transform getTransform(Body body) {
    SWIGTYPE_p_Transform ret = new SWIGTYPE_p_Transform(CSharpWrapOpenSimPINVOKE.OpenSimContext_getTransform(swigCPtr, Body.getCPtr(body)), true);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void transform(Body ground, SWIGTYPE_p_double d, Body body, SWIGTYPE_p_double dragVectorBody) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_transform(swigCPtr, Body.getCPtr(ground), SWIGTYPE_p_double.getCPtr(d), Body.getCPtr(body), SWIGTYPE_p_double.getCPtr(dragVectorBody));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double getValue(Coordinate coord) {
    double ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getValue(swigCPtr, Coordinate.getCPtr(coord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool getLocked(Coordinate coord) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getLocked(swigCPtr, Coordinate.getCPtr(coord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setValue(Coordinate coord, double d, bool enforceConstraints) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setValue__SWIG_0(swigCPtr, Coordinate.getCPtr(coord), d, enforceConstraints);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setValue(Coordinate coord, double d) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setValue__SWIG_1(swigCPtr, Coordinate.getCPtr(coord), d);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setClamped(Coordinate coord, bool newValue) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setClamped(swigCPtr, Coordinate.getCPtr(coord), newValue);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool getClamped(Coordinate coord) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getClamped(swigCPtr, Coordinate.getCPtr(coord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setLocked(Coordinate coord, bool newValue) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setLocked(swigCPtr, Coordinate.getCPtr(coord), newValue);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool isPrescribed(Coordinate coord) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_isPrescribed(swigCPtr, Coordinate.getCPtr(coord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool isConstrained(Coordinate coord) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_isConstrained(swigCPtr, Coordinate.getCPtr(coord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool isDisabled(Constraint constraint) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_isDisabled__SWIG_0(swigCPtr, Constraint.getCPtr(constraint));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setDisabled(Constraint constraint, bool disable) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setDisabled__SWIG_0(swigCPtr, Constraint.getCPtr(constraint), disable);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool isDisabled(Force force) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_isDisabled__SWIG_1(swigCPtr, Force.getCPtr(force));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setDisabled(Force force, bool disable) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setDisabled__SWIG_1(swigCPtr, Force.getCPtr(force), disable);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe double getActivation(Muscle act) {
    double ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getActivation(swigCPtr, Muscle.getCPtr(act));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double getMuscleLength(Muscle act) {
    double ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getMuscleLength(swigCPtr, Muscle.getCPtr(act));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe ArrayPathPoint getCurrentPath(Muscle act) {
    ArrayPathPoint ret = new ArrayPathPoint(CSharpWrapOpenSimPINVOKE.OpenSimContext_getCurrentPath(swigCPtr, Muscle.getCPtr(act)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe ArrayPathPoint getCurrentDisplayPath(GeometryPath path) {
    ArrayPathPoint ret = new ArrayPathPoint(CSharpWrapOpenSimPINVOKE.OpenSimContext_getCurrentDisplayPath(swigCPtr, GeometryPath.getCPtr(path)), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void updateDisplayer(Force f) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_updateDisplayer(swigCPtr, Force.getCPtr(f));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void copyMuscle(Muscle from, Muscle to) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_copyMuscle(swigCPtr, Muscle.getCPtr(from), Muscle.getCPtr(to));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void replacePropertyFunction(OpenSimObject obj, Function aOldFunction, Function aNewFunction) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_replacePropertyFunction(swigCPtr, OpenSimObject.getCPtr(obj), Function.getCPtr(aOldFunction), Function.getCPtr(aNewFunction));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setXFunction(MovingPathPoint mmp, Function newFunction) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setXFunction(swigCPtr, MovingPathPoint.getCPtr(mmp), Function.getCPtr(newFunction));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setYFunction(MovingPathPoint mmp, Function newFunction) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setYFunction(swigCPtr, MovingPathPoint.getCPtr(mmp), Function.getCPtr(newFunction));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setZFunction(MovingPathPoint mmp, Function newFunction) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setZFunction(swigCPtr, MovingPathPoint.getCPtr(mmp), Function.getCPtr(newFunction));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setXCoordinate(MovingPathPoint mmp, Coordinate newCoord) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setXCoordinate(swigCPtr, MovingPathPoint.getCPtr(mmp), Coordinate.getCPtr(newCoord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setYCoordinate(MovingPathPoint mmp, Coordinate newCoord) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setYCoordinate(swigCPtr, MovingPathPoint.getCPtr(mmp), Coordinate.getCPtr(newCoord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setZCoordinate(MovingPathPoint mmp, Coordinate newCoord) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setZCoordinate(swigCPtr, MovingPathPoint.getCPtr(mmp), Coordinate.getCPtr(newCoord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setBody(PathPoint pathPoint, Body newBody) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setBody__SWIG_0(swigCPtr, PathPoint.getCPtr(pathPoint), Body.getCPtr(newBody));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setCoordinate(ConditionalPathPoint via, Coordinate newCoord) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setCoordinate(swigCPtr, ConditionalPathPoint.getCPtr(via), Coordinate.getCPtr(newCoord));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setRangeMin(ConditionalPathPoint via, double d) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setRangeMin(swigCPtr, ConditionalPathPoint.getCPtr(via), d);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setRangeMax(ConditionalPathPoint via, double d) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setRangeMax(swigCPtr, ConditionalPathPoint.getCPtr(via), d);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool replacePathPoint(GeometryPath p, PathPoint mp, PathPoint newPoint) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_replacePathPoint(swigCPtr, GeometryPath.getCPtr(p), PathPoint.getCPtr(mp), PathPoint.getCPtr(newPoint));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setLocation(PathPoint mp, int i, double d) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setLocation(swigCPtr, PathPoint.getCPtr(mp), i, d);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setEndPoint(PathWrap mw, int newEndPt) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setEndPoint(swigCPtr, PathWrap.getCPtr(mw), newEndPt);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addPathPoint(GeometryPath p, int menuChoice, Body body) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_addPathPoint(swigCPtr, GeometryPath.getCPtr(p), menuChoice, Body.getCPtr(body));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool deletePathPoint(GeometryPath p, int menuChoice) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_deletePathPoint(swigCPtr, GeometryPath.getCPtr(p), menuChoice);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool isActivePathPoint(PathPoint mp) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_isActivePathPoint(swigCPtr, PathPoint.getCPtr(mp));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setStartPoint(PathWrap mw, int newStartPt) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setStartPoint(swigCPtr, PathWrap.getCPtr(mw), newStartPt);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addPathWrap(GeometryPath p, WrapObject awo) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_addPathWrap(swigCPtr, GeometryPath.getCPtr(p), WrapObject.getCPtr(awo));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void moveUpPathWrap(GeometryPath p, int num) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_moveUpPathWrap(swigCPtr, GeometryPath.getCPtr(p), num);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void moveDownPathWrap(GeometryPath p, int num) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_moveDownPathWrap(swigCPtr, GeometryPath.getCPtr(p), num);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void deletePathWrap(GeometryPath p, int num) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_deletePathWrap(swigCPtr, GeometryPath.getCPtr(p), num);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setBody(Marker currentMarker, Body newBody, bool b) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setBody__SWIG_1(swigCPtr, Marker.getCPtr(currentMarker), Body.getCPtr(newBody), b);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int replaceMarkerSet(Model model, MarkerSet aMarkerSet) {
    int ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_replaceMarkerSet(swigCPtr, Model.getCPtr(model), MarkerSet.getCPtr(aMarkerSet));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getCenterOfMassInGround(SWIGTYPE_p_double com) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_getCenterOfMassInGround(swigCPtr, SWIGTYPE_p_double.getCPtr(com));
  }

  public unsafe int step(Analysis analysis) {
    int ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_step(swigCPtr, Analysis.getCPtr(analysis));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool solveInverseKinematics(InverseKinematicsTool ikTool) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_solveInverseKinematics(swigCPtr, InverseKinematicsTool.getCPtr(ikTool));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setStatesFromMotion(AnalyzeTool analyzeTool, SWIGTYPE_p_OpenSim__Storage aMotion, bool aInDegrees) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setStatesFromMotion(swigCPtr, AnalyzeTool.getCPtr(analyzeTool), SWIGTYPE_p_OpenSim__Storage.getCPtr(aMotion), aInDegrees);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void loadStatesFromFile(AnalyzeTool analyzeTool) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_loadStatesFromFile(swigCPtr, AnalyzeTool.getCPtr(analyzeTool));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool processModelScale(ModelScaler modelScaler, Model aModel, string aPathToSubject, double aFinalMass) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_processModelScale__SWIG_0(swigCPtr, ModelScaler.getCPtr(modelScaler), Model.getCPtr(aModel), aPathToSubject, aFinalMass);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool processModelScale(ModelScaler modelScaler, Model aModel, string aPathToSubject) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_processModelScale__SWIG_1(swigCPtr, ModelScaler.getCPtr(modelScaler), Model.getCPtr(aModel), aPathToSubject);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool processModelScale(ModelScaler modelScaler, Model aModel) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_processModelScale__SWIG_2(swigCPtr, ModelScaler.getCPtr(modelScaler), Model.getCPtr(aModel));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool processModelMarkerPlacer(MarkerPlacer markerPlacer, Model aModel, string aPathToSubject) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_processModelMarkerPlacer__SWIG_0(swigCPtr, MarkerPlacer.getCPtr(markerPlacer), Model.getCPtr(aModel), aPathToSubject);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool processModelMarkerPlacer(MarkerPlacer markerPlacer, Model aModel) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_processModelMarkerPlacer__SWIG_1(swigCPtr, MarkerPlacer.getCPtr(markerPlacer), Model.getCPtr(aModel));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe double computeMeasurementScaleFactor(ModelScaler modelScaler, Model aModel, MarkerData aMarkerData, Measurement aMeasurement) {
    double ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_computeMeasurementScaleFactor(swigCPtr, ModelScaler.getCPtr(modelScaler), Model.getCPtr(aModel), MarkerData.getCPtr(aMarkerData), Measurement.getCPtr(aMeasurement));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void replaceTransformAxisFunction(TransformAxis aDof, Function aFunction) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_replaceTransformAxisFunction(swigCPtr, TransformAxis.getCPtr(aDof), Function.getCPtr(aFunction));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static bool isNaN(double v) {
    bool ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_isNaN(v);
    return ret;
  }

  public unsafe double getTime() {
    double ret = CSharpWrapOpenSimPINVOKE.OpenSimContext_getTime(swigCPtr);
    return ret;
  }

  public unsafe static void getTransformAsDouble16(Transform aTransform, SWIGTYPE_p_double flattened) {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_getTransformAsDouble16(Transform.getCPtr(aTransform), SWIGTYPE_p_double.getCPtr(flattened));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setPropertiesFromState() {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_setPropertiesFromState(swigCPtr);
  }

  public unsafe void recreateSystemKeepStage() {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_recreateSystemKeepStage(swigCPtr);
  }

  public unsafe void realizePosition() {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_realizePosition(swigCPtr);
  }

  public unsafe void realizeVelocity() {
    CSharpWrapOpenSimPINVOKE.OpenSimContext_realizeVelocity(swigCPtr);
  }

}

}
