/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class SetBodies : OpenSimObject {
  private HandleRef swigCPtr;

  internal SetBodies(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.SetBodies_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SetBodies obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SetBodies() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_SetBodies(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static SetBodies safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetBodies_safeDownCast(OpenSimObject.getCPtr(obj));
    SetBodies ret = (cPtr == IntPtr.Zero) ? null : new SetBodies(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.SetBodies_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetBodies_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetBodies_clone(swigCPtr);
    SetBodies ret = (cPtr == IntPtr.Zero) ? null : new SetBodies(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetBodies_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe SetBodies() : this(CSharpWrapOpenSimPINVOKE.new_SetBodies__SWIG_0(), true) {
  }

  public unsafe SetBodies(string aFileName, bool aUpdateFromXMLNode) : this(CSharpWrapOpenSimPINVOKE.new_SetBodies__SWIG_1(aFileName, aUpdateFromXMLNode), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetBodies(string aFileName) : this(CSharpWrapOpenSimPINVOKE.new_SetBodies__SWIG_2(aFileName), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetBodies(SetBodies aSet) : this(CSharpWrapOpenSimPINVOKE.new_SetBodies__SWIG_3(SetBodies.getCPtr(aSet)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setupGroups() {
    CSharpWrapOpenSimPINVOKE.SetBodies_setupGroups(swigCPtr);
  }

  public unsafe void setMemoryOwner(bool aTrueFalse) {
    CSharpWrapOpenSimPINVOKE.SetBodies_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public unsafe bool setSize(int aSize) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_setSize(swigCPtr, aSize);
    return ret;
  }

  public unsafe int getSize() {
    int ret = CSharpWrapOpenSimPINVOKE.SetBodies_getSize(swigCPtr);
    return ret;
  }

  public unsafe int getIndex(Body aObject, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetBodies_getIndex__SWIG_0(swigCPtr, Body.getCPtr(aObject), aStartIndex);
    return ret;
  }

  public unsafe int getIndex(Body aObject) {
    int ret = CSharpWrapOpenSimPINVOKE.SetBodies_getIndex__SWIG_1(swigCPtr, Body.getCPtr(aObject));
    return ret;
  }

  public unsafe int getIndex(string aName, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetBodies_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int getIndex(string aName) {
    int ret = CSharpWrapOpenSimPINVOKE.SetBodies_getIndex__SWIG_3(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getGroupNamesContaining(string aObjectName, ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetBodies_getGroupNamesContaining(swigCPtr, aObjectName, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool adoptAndAppend(Body aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_adoptAndAppend(swigCPtr, Body.getCPtr(aObject));
    return ret;
  }

  public unsafe bool cloneAndAppend(Body aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_cloneAndAppend(swigCPtr, Body.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool insert(int aIndex, Body aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_insert(swigCPtr, aIndex, Body.getCPtr(aObject));
    return ret;
  }

  public unsafe bool remove(int aIndex) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_remove__SWIG_0(swigCPtr, aIndex);
    return ret;
  }

  public unsafe bool remove(Body aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_remove__SWIG_1(swigCPtr, Body.getCPtr(aObject));
    return ret;
  }

  public unsafe void clearAndDestroy() {
    CSharpWrapOpenSimPINVOKE.SetBodies_clearAndDestroy(swigCPtr);
  }

  public unsafe bool set(int aIndex, Body aObject, bool preserveGroups) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_set__SWIG_0(swigCPtr, aIndex, Body.getCPtr(aObject), preserveGroups);
    return ret;
  }

  public unsafe bool set(int aIndex, Body aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_set__SWIG_1(swigCPtr, aIndex, Body.getCPtr(aObject));
    return ret;
  }

  public unsafe Body get(int aIndex) {
    Body ret = new Body(CSharpWrapOpenSimPINVOKE.SetBodies_get__SWIG_0(swigCPtr, aIndex), false);
    return ret;
  }

  public unsafe Body get(string aName) {
    Body ret = new Body(CSharpWrapOpenSimPINVOKE.SetBodies_get__SWIG_1(swigCPtr, aName), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool contains(string aName) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetBodies_contains(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getNames(ArrayStr rNames) {
    CSharpWrapOpenSimPINVOKE.SetBodies_getNames(swigCPtr, ArrayStr.getCPtr(rNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int getNumGroups() {
    int ret = CSharpWrapOpenSimPINVOKE.SetBodies_getNumGroups(swigCPtr);
    return ret;
  }

  public unsafe void addGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetBodies_addGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void removeGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetBodies_removeGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void renameGroup(string oldGroupName, string newGroupName) {
    CSharpWrapOpenSimPINVOKE.SetBodies_renameGroup(swigCPtr, oldGroupName, newGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addObjectToGroup(string aGroupName, string aObjectName) {
    CSharpWrapOpenSimPINVOKE.SetBodies_addObjectToGroup(swigCPtr, aGroupName, aObjectName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getGroupNames(ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetBodies_getGroupNames(swigCPtr, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ObjectGroup getGroup(string aGroupName) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetBodies_getGroup__SWIG_0(swigCPtr, aGroupName);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe ObjectGroup getGroup(int aIndex) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetBodies_getGroup__SWIG_1(swigCPtr, aIndex);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    return ret;
  }

}

}
