/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class SetCoordinates : OpenSimObject {
  private HandleRef swigCPtr;

  internal SetCoordinates(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.SetCoordinates_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SetCoordinates obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SetCoordinates() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_SetCoordinates(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static SetCoordinates safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetCoordinates_safeDownCast(OpenSimObject.getCPtr(obj));
    SetCoordinates ret = (cPtr == IntPtr.Zero) ? null : new SetCoordinates(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetCoordinates_clone(swigCPtr);
    SetCoordinates ret = (cPtr == IntPtr.Zero) ? null : new SetCoordinates(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe SetCoordinates() : this(CSharpWrapOpenSimPINVOKE.new_SetCoordinates__SWIG_0(), true) {
  }

  public unsafe SetCoordinates(string aFileName, bool aUpdateFromXMLNode) : this(CSharpWrapOpenSimPINVOKE.new_SetCoordinates__SWIG_1(aFileName, aUpdateFromXMLNode), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetCoordinates(string aFileName) : this(CSharpWrapOpenSimPINVOKE.new_SetCoordinates__SWIG_2(aFileName), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetCoordinates(SetCoordinates aSet) : this(CSharpWrapOpenSimPINVOKE.new_SetCoordinates__SWIG_3(SetCoordinates.getCPtr(aSet)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setupGroups() {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_setupGroups(swigCPtr);
  }

  public unsafe void setMemoryOwner(bool aTrueFalse) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public unsafe bool setSize(int aSize) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_setSize(swigCPtr, aSize);
    return ret;
  }

  public unsafe int getSize() {
    int ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getSize(swigCPtr);
    return ret;
  }

  public unsafe int getIndex(Coordinate aObject, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getIndex__SWIG_0(swigCPtr, Coordinate.getCPtr(aObject), aStartIndex);
    return ret;
  }

  public unsafe int getIndex(Coordinate aObject) {
    int ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getIndex__SWIG_1(swigCPtr, Coordinate.getCPtr(aObject));
    return ret;
  }

  public unsafe int getIndex(string aName, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int getIndex(string aName) {
    int ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getIndex__SWIG_3(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getGroupNamesContaining(string aObjectName, ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_getGroupNamesContaining(swigCPtr, aObjectName, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool adoptAndAppend(Coordinate aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_adoptAndAppend(swigCPtr, Coordinate.getCPtr(aObject));
    return ret;
  }

  public unsafe bool cloneAndAppend(Coordinate aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_cloneAndAppend(swigCPtr, Coordinate.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool insert(int aIndex, Coordinate aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_insert(swigCPtr, aIndex, Coordinate.getCPtr(aObject));
    return ret;
  }

  public unsafe bool remove(int aIndex) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_remove__SWIG_0(swigCPtr, aIndex);
    return ret;
  }

  public unsafe bool remove(Coordinate aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_remove__SWIG_1(swigCPtr, Coordinate.getCPtr(aObject));
    return ret;
  }

  public unsafe void clearAndDestroy() {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_clearAndDestroy(swigCPtr);
  }

  public unsafe bool set(int aIndex, Coordinate aObject, bool preserveGroups) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_set__SWIG_0(swigCPtr, aIndex, Coordinate.getCPtr(aObject), preserveGroups);
    return ret;
  }

  public unsafe bool set(int aIndex, Coordinate aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_set__SWIG_1(swigCPtr, aIndex, Coordinate.getCPtr(aObject));
    return ret;
  }

  public unsafe Coordinate get(int aIndex) {
    Coordinate ret = new Coordinate(CSharpWrapOpenSimPINVOKE.SetCoordinates_get__SWIG_0(swigCPtr, aIndex), false);
    return ret;
  }

  public unsafe Coordinate get(string aName) {
    Coordinate ret = new Coordinate(CSharpWrapOpenSimPINVOKE.SetCoordinates_get__SWIG_1(swigCPtr, aName), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool contains(string aName) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_contains(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getNames(ArrayStr rNames) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_getNames(swigCPtr, ArrayStr.getCPtr(rNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int getNumGroups() {
    int ret = CSharpWrapOpenSimPINVOKE.SetCoordinates_getNumGroups(swigCPtr);
    return ret;
  }

  public unsafe void addGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_addGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void removeGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_removeGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void renameGroup(string oldGroupName, string newGroupName) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_renameGroup(swigCPtr, oldGroupName, newGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addObjectToGroup(string aGroupName, string aObjectName) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_addObjectToGroup(swigCPtr, aGroupName, aObjectName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getGroupNames(ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetCoordinates_getGroupNames(swigCPtr, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ObjectGroup getGroup(string aGroupName) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetCoordinates_getGroup__SWIG_0(swigCPtr, aGroupName);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe ObjectGroup getGroup(int aIndex) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetCoordinates_getGroup__SWIG_1(swigCPtr, aIndex);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    return ret;
  }

}

}
