/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class SetMeasurements : OpenSimObject {
  private HandleRef swigCPtr;

  internal SetMeasurements(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.SetMeasurements_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SetMeasurements obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SetMeasurements() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_SetMeasurements(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static SetMeasurements safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetMeasurements_safeDownCast(OpenSimObject.getCPtr(obj));
    SetMeasurements ret = (cPtr == IntPtr.Zero) ? null : new SetMeasurements(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetMeasurements_clone(swigCPtr);
    SetMeasurements ret = (cPtr == IntPtr.Zero) ? null : new SetMeasurements(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe SetMeasurements() : this(CSharpWrapOpenSimPINVOKE.new_SetMeasurements__SWIG_0(), true) {
  }

  public unsafe SetMeasurements(string aFileName, bool aUpdateFromXMLNode) : this(CSharpWrapOpenSimPINVOKE.new_SetMeasurements__SWIG_1(aFileName, aUpdateFromXMLNode), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetMeasurements(string aFileName) : this(CSharpWrapOpenSimPINVOKE.new_SetMeasurements__SWIG_2(aFileName), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetMeasurements(SetMeasurements aSet) : this(CSharpWrapOpenSimPINVOKE.new_SetMeasurements__SWIG_3(SetMeasurements.getCPtr(aSet)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setupGroups() {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_setupGroups(swigCPtr);
  }

  public unsafe void setMemoryOwner(bool aTrueFalse) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public unsafe bool setSize(int aSize) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_setSize(swigCPtr, aSize);
    return ret;
  }

  public unsafe int getSize() {
    int ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getSize(swigCPtr);
    return ret;
  }

  public unsafe int getIndex(Measurement aObject, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getIndex__SWIG_0(swigCPtr, Measurement.getCPtr(aObject), aStartIndex);
    return ret;
  }

  public unsafe int getIndex(Measurement aObject) {
    int ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getIndex__SWIG_1(swigCPtr, Measurement.getCPtr(aObject));
    return ret;
  }

  public unsafe int getIndex(string aName, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int getIndex(string aName) {
    int ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getIndex__SWIG_3(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getGroupNamesContaining(string aObjectName, ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_getGroupNamesContaining(swigCPtr, aObjectName, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool adoptAndAppend(Measurement aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_adoptAndAppend(swigCPtr, Measurement.getCPtr(aObject));
    return ret;
  }

  public unsafe bool cloneAndAppend(Measurement aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_cloneAndAppend(swigCPtr, Measurement.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool insert(int aIndex, Measurement aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_insert(swigCPtr, aIndex, Measurement.getCPtr(aObject));
    return ret;
  }

  public unsafe bool remove(int aIndex) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_remove__SWIG_0(swigCPtr, aIndex);
    return ret;
  }

  public unsafe bool remove(Measurement aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_remove__SWIG_1(swigCPtr, Measurement.getCPtr(aObject));
    return ret;
  }

  public unsafe void clearAndDestroy() {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_clearAndDestroy(swigCPtr);
  }

  public unsafe bool set(int aIndex, Measurement aObject, bool preserveGroups) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_set__SWIG_0(swigCPtr, aIndex, Measurement.getCPtr(aObject), preserveGroups);
    return ret;
  }

  public unsafe bool set(int aIndex, Measurement aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_set__SWIG_1(swigCPtr, aIndex, Measurement.getCPtr(aObject));
    return ret;
  }

  public unsafe Measurement get(int aIndex) {
    Measurement ret = new Measurement(CSharpWrapOpenSimPINVOKE.SetMeasurements_get__SWIG_0(swigCPtr, aIndex), false);
    return ret;
  }

  public unsafe Measurement get(string aName) {
    Measurement ret = new Measurement(CSharpWrapOpenSimPINVOKE.SetMeasurements_get__SWIG_1(swigCPtr, aName), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool contains(string aName) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_contains(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getNames(ArrayStr rNames) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_getNames(swigCPtr, ArrayStr.getCPtr(rNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int getNumGroups() {
    int ret = CSharpWrapOpenSimPINVOKE.SetMeasurements_getNumGroups(swigCPtr);
    return ret;
  }

  public unsafe void addGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_addGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void removeGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_removeGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void renameGroup(string oldGroupName, string newGroupName) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_renameGroup(swigCPtr, oldGroupName, newGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addObjectToGroup(string aGroupName, string aObjectName) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_addObjectToGroup(swigCPtr, aGroupName, aObjectName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getGroupNames(ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetMeasurements_getGroupNames(swigCPtr, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ObjectGroup getGroup(string aGroupName) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetMeasurements_getGroup__SWIG_0(swigCPtr, aGroupName);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe ObjectGroup getGroup(int aIndex) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetMeasurements_getGroup__SWIG_1(swigCPtr, aIndex);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    return ret;
  }

}

}
