/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class SetProbes : OpenSimObject {
  private HandleRef swigCPtr;

  internal SetProbes(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.SetProbes_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SetProbes obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SetProbes() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_SetProbes(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe static SetProbes safeDownCast(OpenSimObject obj) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetProbes_safeDownCast(OpenSimObject.getCPtr(obj));
    SetProbes ret = (cPtr == IntPtr.Zero) ? null : new SetProbes(cPtr, false);
    return ret;
  }

  public unsafe void assign(OpenSimObject aObject) {
    CSharpWrapOpenSimPINVOKE.SetProbes_assign(swigCPtr, OpenSimObject.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static string getClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetProbes_getClassName();
    return ret;
  }

  public unsafe OpenSimObject clone() {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetProbes_clone(swigCPtr);
    SetProbes ret = (cPtr == IntPtr.Zero) ? null : new SetProbes(cPtr, false);
    return ret;
  }

  public unsafe string getConcreteClassName() {
    string ret = CSharpWrapOpenSimPINVOKE.SetProbes_getConcreteClassName(swigCPtr);
    return ret;
  }

  public unsafe SetProbes() : this(CSharpWrapOpenSimPINVOKE.new_SetProbes__SWIG_0(), true) {
  }

  public unsafe SetProbes(string aFileName, bool aUpdateFromXMLNode) : this(CSharpWrapOpenSimPINVOKE.new_SetProbes__SWIG_1(aFileName, aUpdateFromXMLNode), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetProbes(string aFileName) : this(CSharpWrapOpenSimPINVOKE.new_SetProbes__SWIG_2(aFileName), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe SetProbes(SetProbes aSet) : this(CSharpWrapOpenSimPINVOKE.new_SetProbes__SWIG_3(SetProbes.getCPtr(aSet)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void setupGroups() {
    CSharpWrapOpenSimPINVOKE.SetProbes_setupGroups(swigCPtr);
  }

  public unsafe void setMemoryOwner(bool aTrueFalse) {
    CSharpWrapOpenSimPINVOKE.SetProbes_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public unsafe bool setSize(int aSize) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_setSize(swigCPtr, aSize);
    return ret;
  }

  public unsafe int getSize() {
    int ret = CSharpWrapOpenSimPINVOKE.SetProbes_getSize(swigCPtr);
    return ret;
  }

  public unsafe int getIndex(Probe aObject, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetProbes_getIndex__SWIG_0(swigCPtr, Probe.getCPtr(aObject), aStartIndex);
    return ret;
  }

  public unsafe int getIndex(Probe aObject) {
    int ret = CSharpWrapOpenSimPINVOKE.SetProbes_getIndex__SWIG_1(swigCPtr, Probe.getCPtr(aObject));
    return ret;
  }

  public unsafe int getIndex(string aName, int aStartIndex) {
    int ret = CSharpWrapOpenSimPINVOKE.SetProbes_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int getIndex(string aName) {
    int ret = CSharpWrapOpenSimPINVOKE.SetProbes_getIndex__SWIG_3(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getGroupNamesContaining(string aObjectName, ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetProbes_getGroupNamesContaining(swigCPtr, aObjectName, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe bool adoptAndAppend(Probe aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_adoptAndAppend(swigCPtr, Probe.getCPtr(aObject));
    return ret;
  }

  public unsafe bool cloneAndAppend(Probe aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_cloneAndAppend(swigCPtr, Probe.getCPtr(aObject));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool insert(int aIndex, Probe aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_insert(swigCPtr, aIndex, Probe.getCPtr(aObject));
    return ret;
  }

  public unsafe bool remove(int aIndex) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_remove__SWIG_0(swigCPtr, aIndex);
    return ret;
  }

  public unsafe bool remove(Probe aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_remove__SWIG_1(swigCPtr, Probe.getCPtr(aObject));
    return ret;
  }

  public unsafe void clearAndDestroy() {
    CSharpWrapOpenSimPINVOKE.SetProbes_clearAndDestroy(swigCPtr);
  }

  public unsafe bool set(int aIndex, Probe aObject, bool preserveGroups) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_set__SWIG_0(swigCPtr, aIndex, Probe.getCPtr(aObject), preserveGroups);
    return ret;
  }

  public unsafe bool set(int aIndex, Probe aObject) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_set__SWIG_1(swigCPtr, aIndex, Probe.getCPtr(aObject));
    return ret;
  }

  public unsafe Probe get(int aIndex) {
    Probe ret = new Probe(CSharpWrapOpenSimPINVOKE.SetProbes_get__SWIG_0(swigCPtr, aIndex), false);
    return ret;
  }

  public unsafe Probe get(string aName) {
    Probe ret = new Probe(CSharpWrapOpenSimPINVOKE.SetProbes_get__SWIG_1(swigCPtr, aName), false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe bool contains(string aName) {
    bool ret = CSharpWrapOpenSimPINVOKE.SetProbes_contains(swigCPtr, aName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void getNames(ArrayStr rNames) {
    CSharpWrapOpenSimPINVOKE.SetProbes_getNames(swigCPtr, ArrayStr.getCPtr(rNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int getNumGroups() {
    int ret = CSharpWrapOpenSimPINVOKE.SetProbes_getNumGroups(swigCPtr);
    return ret;
  }

  public unsafe void addGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetProbes_addGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void removeGroup(string aGroupName) {
    CSharpWrapOpenSimPINVOKE.SetProbes_removeGroup(swigCPtr, aGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void renameGroup(string oldGroupName, string newGroupName) {
    CSharpWrapOpenSimPINVOKE.SetProbes_renameGroup(swigCPtr, oldGroupName, newGroupName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void addObjectToGroup(string aGroupName, string aObjectName) {
    CSharpWrapOpenSimPINVOKE.SetProbes_addObjectToGroup(swigCPtr, aGroupName, aObjectName);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe void getGroupNames(ArrayStr rGroupNames) {
    CSharpWrapOpenSimPINVOKE.SetProbes_getGroupNames(swigCPtr, ArrayStr.getCPtr(rGroupNames));
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe ObjectGroup getGroup(string aGroupName) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetProbes_getGroup__SWIG_0(swigCPtr, aGroupName);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe ObjectGroup getGroup(int aIndex) {
    IntPtr cPtr = CSharpWrapOpenSimPINVOKE.SetProbes_getGroup__SWIG_1(swigCPtr, aIndex);
    ObjectGroup ret = (cPtr == IntPtr.Zero) ? null : new ObjectGroup(cPtr, false);
    return ret;
  }

}

}
