/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenSim {

using System;
using System.Runtime.InteropServices;

public class VectorBaseDouble : MatrixBaseDouble {
  private HandleRef swigCPtr;

  internal VectorBaseDouble(IntPtr cPtr, bool cMemoryOwn) : base(CSharpWrapOpenSimPINVOKE.VectorBaseDouble_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(VectorBaseDouble obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorBaseDouble() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapOpenSimPINVOKE.delete_VectorBaseDouble(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe VectorBaseDouble(int m) : this(CSharpWrapOpenSimPINVOKE.new_VectorBaseDouble__SWIG_0(m), true) {
  }

  public unsafe VectorBaseDouble() : this(CSharpWrapOpenSimPINVOKE.new_VectorBaseDouble__SWIG_1(), true) {
  }

  public unsafe VectorBaseDouble(VectorBaseDouble source) : this(CSharpWrapOpenSimPINVOKE.new_VectorBaseDouble__SWIG_2(VectorBaseDouble.getCPtr(source)), true) {
    if (CSharpWrapOpenSimPINVOKE.SWIGPendingException.Pending) throw CSharpWrapOpenSimPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int size() {
    int ret = CSharpWrapOpenSimPINVOKE.VectorBaseDouble_size(swigCPtr);
    return ret;
  }

  public unsafe int nrow() {
    int ret = CSharpWrapOpenSimPINVOKE.VectorBaseDouble_nrow(swigCPtr);
    return ret;
  }

  public unsafe int ncol() {
    int ret = CSharpWrapOpenSimPINVOKE.VectorBaseDouble_ncol(swigCPtr);
    return ret;
  }

  public unsafe VectorBaseDouble resize(int m) {
    VectorBaseDouble ret = new VectorBaseDouble(CSharpWrapOpenSimPINVOKE.VectorBaseDouble_resize(swigCPtr, m), false);
    return ret;
  }

  public unsafe VectorBaseDouble resizeKeep(int m) {
    VectorBaseDouble ret = new VectorBaseDouble(CSharpWrapOpenSimPINVOKE.VectorBaseDouble_resizeKeep(swigCPtr, m), false);
    return ret;
  }

  public unsafe void clear() {
    CSharpWrapOpenSimPINVOKE.VectorBaseDouble_clear(swigCPtr);
  }

  public unsafe double sum() {
    double ret = CSharpWrapOpenSimPINVOKE.VectorBaseDouble_sum(swigCPtr);
    return ret;
  }

}

}
